### ISSUE TITLE
Browser support?

### ISSUE THREAD

**Issue by pavlospolianidis** [lumapps/lumX#101]

**Comment by malexandre** [comment]
Hi!
We'll work on that soon, during our ergonomics and accessibility optimization.

**Comment by janmyler** [comment]
Hey guys, huge big ups for this project! As of today, it looks much better and it's more performing than the Material Design project.

I would have one question speaking of the browser support. Which browsers do you plan to support in this project, especially (as always) in the IE branch?

**Comment by kalicki** [comment]
News?

**Comment by badoet** [comment]
i see that u guys using the flexbox css for the flexbox component
http://caniuse.com/#feat=flexbox
so ie 8 - 10 easily out of the door. plus the older android browsers. 
gd thing that their global usage rather low

**Comment by badoet** [comment]
btw i did a test on my project using IE9, everything seems fine.
only the flexboxes become width 100%

**Comment by matmkian** [comment]
LumX supports IE11. But it should be ok on IE10 too :-)
