### ISSUE TITLE
Select without search filter

### ISSUE THREAD

**Issue by cranst0n** [lumapps/lumX#103]
Is it possible to create an ```<lx-select>``` without a search filter component?

**Comment by malexandre** [comment]
Hi!

For now it's not possible. But for a select with only a few local item, it might be better. I'll see with the team to make an option for this.

**Comment by MilosStanic** [comment]
+1 for this. I have a small select group of 10 local items. I really don't need a filter. It only makes my UI uglier.

**Comment by malexandre** [comment]
It's done. We just need to perfect the style a little before pushing it to
the master.

**Comment by MilosStanic** [comment]
cool, thanks!

**Comment by anoteboom** [comment]
any news on this issue?  on a small screen the searchfilter is unusable.

**Comment by wkeizer** [comment]
+1 for this enhancement.

**Comment by luclanet** [comment]
+1

**Comment by malexandre** [comment]
Just so you know, it's done here: https://github.com/lumapps/lumX/tree/feat/no-filter-select
I'm waiting on validation from @matmkian for the CSS & style.

**Comment by HeavenMonster** [comment]
+1 for this too!

**Comment by wkeizer** [comment]
Thanks Marc!
Op 18 mei 2015 5:34 PM schreef "Marc Alexandre" <notifications@github.com>:

**Comment by wkeizer** [comment]
Will this feature make it into the master any time soon? This will make upgrading to 'latest' LumX version easier.

**Comment by alexgerv** [comment]
+1, would be awesome

**Comment by wkeizer** [comment]
How can I use this enhancement in my project? I use bower in my build script. When I pull in the feature branch, I miss out on all the improvements in later versions of LumX. If I fork LumX, how can I use this fork in bower?

**Comment by matmkian** [comment]
In the last version, we've reworked and fixed a lot of things. If this issue is still happening, please re-open the issue. Thank you!
