### ISSUE TITLE
Date picker Range

### ISSUE THREAD

**Issue by dg1202** [lumapps/lumX#104]
Does the date picker support range selection? Glancing at the source, it didn't look so, just double checking though!

**Comment by malexandre** [comment]
Hi!

I forgot to add this to the roadmap, but it's not done for now. The datepicker is quite basic for the moment.

**Comment by dg1202** [comment]
Sure thing. Thanks for the quick answer.

**Comment by matmkian** [comment]
As Date Picker now have a year selector, I close the issue.
