### ISSUE TITLE
Datepicker : click problem on Firefox

### ISSUE THREAD

**Issue by ThomasCrvsr** [lumapps/lumX#106]
Hello,

I played with the lib and it's a great work :) 
I notice a little bug : when I'm on Firefox, it seems that the only way to open the datepicker modal is by clicking on the label. Clicking on the input field doesn't work.

**Comment by matmkian** [comment]
Ok, thanks for report! We'll take a look soon!

**Comment by ThomasCrvsr** [comment]
Ok ! I can take a look too, I'd be glad to help ^^

**Comment by matmkian** [comment]
With pleasure :-)

**Comment by ThomasCrvsr** [comment]
It comes from the fact that in Firefox, disabled inputs don't fire events... I'm trying to find a workaround but I'm not lucky for the moment. Has anyone has already solved a similar problem ?

**Comment by lovasoa** [comment]
Yes, the input should not be disabled, since [the goal of  `disabled` is to prevent click events from firing](http://www.w3.org/TR/html5/forms.html#concept-fe-disabled).

There could be an onFocus event associated to the input, with an event handler like `input.blur()`.

**Comment by rriemann** [comment]
I can confirm this for Firefox v36. Clicking on the label works.

**Comment by Emeegeemee** [comment]
I can also confirm this for Firefox 40 the date picker only opens if I click on the padding around the input not the input itself

![selection_area](https://cloud.githubusercontent.com/assets/4241156/8100460/a0f4a9c8-0fc0-11e5-8b96-6fe914e81f56.png)

The purple area is where I can click to open the date picker

**Comment by jmijmi** [comment]
The same here .. for Firefox 41

**Comment by solancer** [comment]
can the repo admin please check with the number of pull requests on this bug? this is a major bug and no one is bothered to even look at the pull requests.

**Comment by dizel3d** [comment]
I made PR with fix. You can use my fork until it is confirmed. Just set in your `bower.json`:
```javascript
"lumx": "https://github.com/ITGlobal/lumX.git#aebd3054374a68a7407982aba2b4154e07beefb9"
```
Or:
```javascript
"lumx": "https://github.com/ITGlobal/lumX.git#release"
```

**Comment by matmkian** [comment]
In the last version, we've reworked and fixed a lot of things. If this issue is still happening, please re-open the issue. Thank you!
