### ISSUE TITLE
Data table without icons

### ISSUE THREAD

**Issue by ThomasCrvsr** [lumapps/lumX#107]
Everything is said in the title : is it possible to have a data table without icons in the first column ?

When I try to remove the first column of your example I get this :
![screen shot 2015-01-13 at 00 29 50](https://cloud.githubusercontent.com/assets/4603973/5713347/7248798a-9abb-11e4-853e-b67f4e806b4e.png)

**Comment by Teeweetep** [comment]
Hello, 

Yes, you have to remove the class "data-table--has-primary" in the table.

**Comment by ThomasCrvsr** [comment]
Okay, thanks a lot !
