### ISSUE TITLE
lx-select buggy in IE11

### ISSUE THREAD

**Issue by rhllor** [lumapps/lumX#108]
Hi, 
Use IE11 generate error with lx-select directive.
When we select an item of the list we get this error.

![capture](https://cloud.githubusercontent.com/assets/1021565/5719657/a461cdae-9b1a-11e4-951a-e335f934a663.PNG)

ps: I get this error in demo-site

**Comment by malexandre** [comment]
Oh. I thought I tested the site on IE. We'll try to really test all the browser later in the roadmap, we have some core modification to do before. But we're going to check that at this time. Thanks for the report!

**Comment by matmkian** [comment]
Bug fixed!
