### ISSUE TITLE
Scss compilation fails

### ISSUE THREAD

**Issue by Xobb** [lumapps/lumX#109]
Sass newbie here.

For some reason gulp-sass cannot compile [buttons file](https://github.com/lumapps/lumX/blob/master/scss/main/objects/_objects.button.scss#L6).

    Error in plugin 'gulp-sass'
    Message:
    /home/vagrant/altclient/bower_components/lumx/dist/scss/main/objects/objects.button:6: error: error reading values after 'xs'

**Comment by malexandre** [comment]
Hi!

If I'm not mistaken, you have to use `gulp-ruby-sass`. `gulp-sass` doesn't use the official sass compiler. It uses the `lib-sass` C port which is behind with the versions. Using `gulp-ruby-sass`, you can compile the latest functionality, and we use some "advanced" one.

**Comment by Xobb** [comment]
I've tried gulp-ruby-sass and it failed with more errors than my pageup could handle in terminal.

**Comment by malexandre** [comment]
What version of Sass do you have? And if you got node-sass in your path, you must be sure that the version used is the real Sass.

**Comment by Xobb** [comment]
as per node sass I've got the following:

    ─┬ gulp-sass@1.1.0
   │ ├─┬ node-sass@0.9.6
     │ │ ├── node-sass-middleware@0.3.1

I will install gulp-ruby-sass once again and try to provide more details on that.

**Comment by Xobb** [comment]
Ok, I've installed the gulp-ruby-sass

    vagrant@vagrant-ubuntu-trusty-64:~/altclient$ npm list | grep sass
    ├─┬ gulp-ruby-sass@0.7.1

Running on lumx:

    vagrant@vagrant-ubuntu-trusty-64:~/altclient$ bower list | grep lumx
    ├─┬ lumx#0.2.48

and then I run:

     gulp serve 2> error.txt


[error.txt](https://gist.github.com/Xobb/e380b27b1aaab9c8a28a).

my scss file is not anything like fancy for now:

    .browsehappy {
      margin: 0.2em 0;
      background: #ccc;
      color: #000;
      padding: 0.2em 0;
    }
    @import "../../bower_components/lumx/dist/scss/main/lumx";

**Comment by Xobb** [comment]
If there are any more details I can provide you please let me know

**Comment by matmkian** [comment]
Hi ! Could you tell us what is the version os Sass? sass -v

**Comment by Xobb** [comment]
vagrant@vagrant-ubuntu-trusty-64:~/altclient$ sass -v
    Sass 3.4.4 (Selective Steve)

for bootstrapping I've used [generator-gulp-angular](https://github.com/Swiip/generator-gulp-angular).

**Comment by matmkian** [comment]
Hmmm... Your version os sass seems ok!
I'll let @malexandre help you.

**Comment by matmkian** [comment]
Still got the problem?

**Comment by matmkian** [comment]
In the last version, we've reworked and fixed a lot of things. If this issue is still happening, please re-open the issue. Thank you!
