### ISSUE TITLE
Overriding default settings

### ISSUE THREAD

**Issue by bshir** [lumapps/lumX#11]
I've just started to experiment with lumX and really like it.  The guidelines that you've been following for development are great.

On the customization page http://ui.lumapps.com/getting-started/customization it says:

"You can override lumX default settings (dist/scss/main/settings/_settings.common.scss) if you want to change sizes, colors, etc."

I don't see that file anywhere in the repository.  Should that be updated to (dist/scss/core/settings/_settings.defaults.css)?  Or are there other default settings available that I'm not seeing?

I have a few other questions regarding customization that I wanted to get your opinion on.

Do you have any recommendations for theming?  Such as setting base primary and secondary colors so that they don't require classes to be added throughout the site/app.  

http://www.google.com/design/spec/style/color.html#color-ui-color-application

A specific example:
http://ui.lumapps.com/css/toolbars
1.  Is there a class that can be added to change the color of this toolbar?  e.g.  the equivalent of a btn--red
2.  Is there a designed way to set the default primary and secondary colors of elements like in the material design spec?
Here the title bar is the primary color and the switch is the secondary.  
It would be very nice to be able to set a primary and secondary (or override defaults via theming css files) so that you can easily flip between themes and see it live in your app.  If you have a specific way that you would like to see this done I can work on an implementation
![image](https://cloud.githubusercontent.com/assets/1734579/5238026/fb3fbd4a-7877-11e4-80be-6c08de4c0d26.png)

I very well may be missing something (or many things).  Thanks for putting the time into this project!

**Comment by dhawken** [comment]
Could there be a way to override colors in an existing palette?  This might be not allowed and I should just write my own, but I do like the handy bgc-* classes that reference palette entries.  These are not overrideable so even though the palette colors are, none of these go along with the changes.  

I can override the base palette colors and that seems to work in places where there are utility classes, but not palette entries.

Example:
I can do this in a custom file:
`$red: #123456;`
`$red-400: #abccd;`

I'm now able to use classes like "btn--red " and get the new values, but things like "bgc-red-400" are not overridden.  Maybe the palette entries don't have !default on them on purpose, and the utility classes are easily reproduced, so maybe not a big deal.
