### ISSUE TITLE
Add a "direction" option to dropdown

### ISSUE THREAD

**Issue by ThomasCrvsr** [lumapps/lumX#111]
I included a dropdown in the footer of my app but the problem is that links of the dropdown will be hidden, as they will be right under the dropdown button.

Could it be interesting to add an option "direction" for the dropdown directive ? With two possible values ('up' and 'down') and 'down' used by default.

**Comment by sondreb** [comment]
+1! I really need this as I have some dropdown items at the bottom of my app. Until it's added, I'm "hacking" it with the floating action button instead: http://ui.lumapps.com/css/fab

**Comment by ThomasCrvsr** [comment]
I've made a PR regarding this issue. I'll let the team give me feedback if improvements are needed ^^

**Comment by malexandre** [comment]
It's merged, we'll make a new release soon. Thanks to Thomas!
