### ISSUE TITLE
Select - Reset value

### ISSUE THREAD

**Issue by tomalekoala** [lumapps/lumX#112]
I can dynamically change the choices, but I meet some problem to remove the selected value.
Setting the ng-model isn't enough, could you explain me how should I do ?

**Comment by malexandre** [comment]
Hi!

I'll get back to you soon. I think it's a bug that was already fixed, but it seems not that fixed. Are you on the last LumX version?

**Comment by tomalekoala** [comment]
Oh yup, my bad it's fixed, I used an old version (0.2.26)
