### ISSUE TITLE
ng-click event for lx-search-filter?

### ISSUE THREAD

**Issue by sondreb** [lumapps/lumX#113]
How I'm I suppose to bind up a function to the lx-search-filter? The ng-click or ng-search event should trigger on both ENTER and if the user clicks the SEARCH icon.

**Comment by malexandre** [comment]
Hi!

For now, it's the `model` parameter. You have to give the directive a variable, and then watch this variable. Later we'll add change management and others.

**Comment by jameswyse** [comment]
How about adding [ngModelOptions](https://docs.angularjs.org/api/ng/directive/ngModelOptions) in the mean time? Then we can at least debounce :)

**Comment by matmkian** [comment]
Yes you're right! We're gonna use ng-model in order to keep the original input and all binding functions associated.

**Comment by sondreb** [comment]
One workaround is to copy the actual template for the search-filter and override in your own code. Make sure you copy the latest template from source and not my example here, as the code might change. In the code below, I have added an ng-click handler on the search icon label, and I have my own custom direction on the input field named "ng-enter". Works like a charm :-)

	angular.module("lumx.search-filter").run(['$templateCache', function(a) { a.put('search-filter.html', '<div class="search-filter search-filter--{{ theme }}-theme"\n' +
    '     ng-class="{ \'search-filter--is-focused\': model,\n' +
    '                 \'search-filter--is-closed\': closed }">\n' +
    '    <div class="search-filter__container">\n' +
    '        <label class="search-filter__label" ng-click="$root.performSearch()"><i class="mdi mdi-magnify"></i></label>\n' +
    '        <input type="text" class="search-filter__input" placeholder="{{ placeholder }}" ng-enter="/search" ng-model="model">\n' +
    '        <span class="search-filter__cancel" ng-click="clear()"><i class="mdi mdi-close-circle"></i></span>\n' +
    '    </div>\n' +
    '</div>');
	 }]);

**Comment by ThomasCrvsr** [comment]
+1 for using ng-model and adding ngModelOptions ! (I'm currently in a case where I need to debounce ^^). Is someone working already on this ?

**Comment by cliren** [comment]
+1

**Comment by cliren** [comment]
I have to override the search-filter with the following changes to get it working. Is this an acceptable solution and if yes, I can push PR.

```
//usage
<lx-search-filter model="searchString" filter-width="100%" placeholder="Search" change="filter(newValue)"></lx-search-filter>

//directive

scope: {
        model: '=?',
        theme: '@',
        placeholder: '@',
        change: "&"
      },

scope.$watch('model', function(){
          scope.change({newValue: scope.model});
        });
```

**Comment by cliren** [comment]
For some reason the model has to be a object instead of just a string to get the $watch to fire as shown below. If the model if just a string like $scope.searchString, watch doesn't work.

```
$scope.searchFilter = {
  searchString: ''
}

<lx-search-filter model="searchFilter.searchString" filter-width="100%" placeholder="Search"></lx-search-filter>

$scope.$watch('searchFilter.searchString', function(newValue, oldValue) {
      console.log("change fired");
    }, true);
```

**Comment by zendo108** [comment]
thx Cliren I was struggling with this one.

**Comment by malexandre** [comment]
It's a javascript problem. You can search over the web, but it's well known. Like the Angular team said:

    If you are not using a . in your models you are doing it wrong.
