### ISSUE TITLE
Error: spawn ENOENT

### ISSUE THREAD

**Issue by simsketch** [lumapps/lumX#116]
After successfully running npm install && bower install with no errors, i tried running gulp but I received this error.

C:\Users\Rafael\Documents\football\lumX-0.2.49\lumX-0.2.49>gulp
[15:37:42] Using gulpfile ~\Documents\football\lumX-0.2.49\lumX-0.2.49\gulpfile.
js
[15:37:42] Starting 'auto-reload'...
[15:37:42] Finished 'auto-reload' after 16 ms
[15:37:42] Starting 'default'...
[15:37:42] Finished 'default' after 8.62 µs

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:998:11)
    at Process.ChildProcess._handle.onexit (child_process.js:789:34)

C:\Users\Rafael\Documents\football\lumX-0.2.49\lumX-0.2.49>

Any ideas?

**Comment by malexandre** [comment]
Hi!

It seems you're on windows. When typing `gulp`, a child process is created to be able to watch the gulpfile too and restart gulp in case it's changed. I think you've encounter a nodejs problem (cf https://github.com/joyent/node/issues/2318). You can just call `gulp watch`, it will be the same, but you'll have to restart gulp if you change the gulpfile.

**Comment by matmkian** [comment]
Is everything ok for you?

**Comment by malexandre** [comment]
No response, feel free to re-comment here if needed.

**Comment by simsketch** [comment]
Yeah that seemed to get it to build, but upon downloading the most recent repo, it seems to be running fine...thanks!
