### ISSUE TITLE
is this bug..?

### ISSUE THREAD

**Issue by YoungsoonLee** [lumapps/lumX#117]
i just try to use lumx for test..
i copied and pasted lumx tab to my html 
and bug happened like below.
i met this error  chrome ((based on Chromium 38.0.2125.104)) and firefox the lastest version.(not test IE)

TypeError: undefined is not a function
    at closeDropdownMenu (http://localhost:9000/bower_components/lumx/dist/js/lumx.js:1725:26)
    at linkList (http://localhost:9000/bower_components/lumx/dist/js/lumx.js:1613:13)
    at Object.fn (http://localhost:9000/bower_components/lumx/dist/js/lumx.js:1749:17)
    at Scope.$digest (http://localhost:9000/bower_components/angular/angular.js:14226:29)
    at Scope.$apply (http://localhost:9000/bower_components/angular/angular.js:14489:24)
    at done (http://localhost:9000/bower_components/angular/angular.js:9646:47)
    at completeRequest (http://localhost:9000/bower_components/angular/angular.js:9836:7)
    at XMLHttpRequest.requestLoaded (http://localhost:9000/bower_components/angular/angular.js:9777:9) 

is there any idea?

**Comment by malexandre** [comment]
Hi!
I think I'll need more context. The error is in the dropdown, but there isn't any dropdown in the example. I'd like to see some of your code just to be able to help you.

**Comment by YoungsoonLee** [comment]
sorry for lack of the context.
i use just jquery(v2.1.3) , angular(v1.3.9) , lumx(bower install).

1. filename : navbar_lumx.html
<div class="card">
    <div class="toolbar">
        <div class="toolbar__left mr">
            <button class="btn btn--l btn--black btn--icon" lx-ripple>
                <i class="mdi mdi--menu"></i>
            </button>
        </div>

        <span class="toolbar__label fs-title">Lorem Ipsum</span>

        <div class="toolbar__right">
            <lx-dropdown position="right" from-top>
                <button class="btn btn--l btn--black btn--icon" lx-ripple lx-dropdown-toggle>
                    <i class="mdi mdi--more-vert"></i>
                </button>

                <lx-dropdown-menu>
                    <ul>
                        <li><a class="dropdown-link">Action</a></li>
                        <li><a class="dropdown-link">Another action</a></li>
                        <li><a class="dropdown-link">Something else here</a></li>
                        <li class="dropdown-divider"></li>
                        <li><a class="dropdown-link dropdown-link--is-header">Header</a></li>
                        <li><a class="dropdown-link">Separated link</a></li>
                    </ul>
                </lx-dropdown-menu>
            </lx-dropdown>
            
            <lx-search-filter closed theme="dark"></lx-search-filter>
        </div>
    </div>
</div>

2. main.html
<div ng-include="'components/navbar/navbar_lumx.html'"></div>

<header class="hero-unit" id="banner">
  <div class="container">
    <h1>'Allo, 'Allo!</h1>
    <p class="lead">Kick-start your next web app with Angular Fullstack</p>
    <img src="assets/images/yeoman.png" alt="I'm Yeoman">
  </div>
</header>


3. index,html(include css and js )

<!doctype html>



 <html class="no-js"> 
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <base href="/">
    <title></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width">
    
    
      
      <link rel="stylesheet" href="bower_components/font-awesome/css/font-awesome.css" />
      
    
    
    <link rel="stylesheet" href="app/app.css">
      
      <link rel="stylesheet" href="app/account/login/login.css">
      <link rel="stylesheet" href="app/admin/admin.css">
      <link rel="stylesheet" href="app/app.css">
      
      
    

    
    <link rel="stylesheet" href="bower_components/lumx/dist/css/lumx.css">
    
  </head>
  <body ng-app="lumxtestApp">
    

    
    <div ng-view=""></div>

    
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-XXXXX-X');
      ga('send', 'pageview');
    </script>

    
    
      
      <script src="bower_components/angular/angular.js"></script>
      <script src="bower_components/angular-resource/angular-resource.js"></script>
      <script src="bower_components/angular-cookies/angular-cookies.js"></script>
      <script src="bower_components/angular-sanitize/angular-sanitize.js"></script>
      <script src="bower_components/angular-route/angular-route.js"></script>
      <script src="bower_components/lodash/dist/lodash.compat.js"></script>
      <script src="bower_components/angular-socket-io/socket.js"></script>
      <script src="bower_components/moment/moment.js"></script>
      
      <script src="socket.io-client/socket.io.js"></script>
    

        
        <script src="app/app.js"></script>
          
          <script src="app/account/account.js"></script>
          <script src="app/account/login/login.controller.js"></script>
          <script src="app/account/settings/settings.controller.js"></script>
          <script src="app/account/signup/signup.controller.js"></script>
          <script src="app/admin/admin.controller.js"></script>
          <script src="app/admin/admin.js"></script>
          <script src="app/main/main.controller.js"></script>
          <script src="app/main/main.js"></script>
          <script src="components/auth/auth.service.js"></script>
          <script src="components/auth/user.service.js"></script>
          <script src="components/mongoose-error/mongoose-error.directive.js"></script>
          <script src="components/navbar/navbar.controller.js"></script>
          <script src="components/socket/socket.service.js"></script>
          
        

      
      <script src="bower_components/jquery/dist/jquery.js"></script>
      <script src="bower_components/velocity/velocity.js"></script>
      <script src="bower_components/moment/min/moment-with-locales.min.js"></script>      
      <script src="bower_components/lumx/dist/js/lumx.js"></script>
</body>
</html>

4. js file..
angular.module( 'lumxtestApp', [
    'ngCookies',
    'ngResource',
    'ngSanitize',
    'ngRoute',
    'btford.socket-io',
    'lumx'
] )
    .config( function ( $routeProvider, $locationProvider, $httpProvider )
    {..................


i tested one more with clear project but same error happened
could you check again?

thanks a lot

**Comment by YoungsoonLee** [comment]
sorry for lack of the context.
i use just jquery(v2.1.3) , angular(v1.3.9) , lumx(bower install).
("--" just add for viewinf)

1. filename : navbar_lumx.html 


          <div class="card">
            <div class="toolbar">
             <div class="toolbar__left mr">
               <button class="btn btn--l btn--black btn--icon" lx-ripple>
                   <i class="mdi mdi--menu"></i>
               </button>
          </div>


        <span class="toolbar__label fs-title">Lorem Ipsum</span>


        <div class="toolbar__right">
            <lx-dropdown position="right" from-top>
                <button class="btn btn--l btn--black btn--icon" lx-ripple lx-dropdown-toggle>
                    <i class="mdi mdi--more-vert"></i>
                </button>

                <lx-dropdown-menu>
                    <ul>
                        <li><a class="dropdown-link">Action</a></li>
                        <li><a class="dropdown-link">Another action</a></li>
                        <li><a class="dropdown-link">Something else here</a></li>
                        <li class="dropdown-divider"></li>
                        <li><a class="dropdown-link dropdown-link--is-header">Header</a></li>
                        <li><a class="dropdown-link">Separated link</a></li>
                    </ul>
                </lx-dropdown-menu>
            </lx-dropdown>
            
            <lx-search-filter closed theme="dark"></lx-search-filter>
        </div>
    </div>
   </div>

2. main.html


        <div ng-include="'components/navbar/navbar_lumx.html'">

       </div>
     
           <header class="hero-unit" id="banner">
      
               <div class="container">
                 

                   <h1>'Allo, 'Allo!</h1>
                   

                        <p class="lead">Kick-start your next web app with Angular Fullstack</p>


                         <img src="assets/images/yeoman.png" alt="I'm Yeoman">


        </div>


        </header>


3. index,html(include css and js )

<!doctype html>



 <html class="no-js"> 
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <base href="/">
    <title></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width">
    
    
      
      <link rel="stylesheet" href="bower_components/font-awesome/css/font-awesome.css" />
      
    
    
    <link rel="stylesheet" href="app/app.css">
      
      <link rel="stylesheet" href="app/account/login/login.css">
      <link rel="stylesheet" href="app/admin/admin.css">
      <link rel="stylesheet" href="app/app.css">
      
      
    

    
    <link rel="stylesheet" href="bower_components/lumx/dist/css/lumx.css">
    
  </head>
  <body ng-app="lumxtestApp">
    

    
    <div ng-view=""></div>

    
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-XXXXX-X');
      ga('send', 'pageview');
    </script>

    
    
      
      <script src="bower_components/angular/angular.js"></script>
      <script src="bower_components/angular-resource/angular-resource.js"></script>
      <script src="bower_components/angular-cookies/angular-cookies.js"></script>
      <script src="bower_components/angular-sanitize/angular-sanitize.js"></script>
      <script src="bower_components/angular-route/angular-route.js"></script>
      <script src="bower_components/lodash/dist/lodash.compat.js"></script>
      <script src="bower_components/angular-socket-io/socket.js"></script>
      <script src="bower_components/moment/moment.js"></script>
      
      <script src="socket.io-client/socket.io.js"></script>
    

        
        <script src="app/app.js"></script>
          
          <script src="app/account/account.js"></script>
          <script src="app/account/login/login.controller.js"></script>
          <script src="app/account/settings/settings.controller.js"></script>
          <script src="app/account/signup/signup.controller.js"></script>
          <script src="app/admin/admin.controller.js"></script>
          <script src="app/admin/admin.js"></script>
          <script src="app/main/main.controller.js"></script>
          <script src="app/main/main.js"></script>
          <script src="components/auth/auth.service.js"></script>
          <script src="components/auth/user.service.js"></script>
          <script src="components/mongoose-error/mongoose-error.directive.js"></script>
          <script src="components/navbar/navbar.controller.js"></script>
          <script src="components/socket/socket.service.js"></script>
          
        

      
      <script src="bower_components/jquery/dist/jquery.js"></script>
      <script src="bower_components/velocity/velocity.js"></script>
      <script src="bower_components/moment/min/moment-with-locales.min.js"></script>      
      <script src="bower_components/lumx/dist/js/lumx.js"></script>
</body>
</html>

4. js file..

  angular.module( 'lumxtestApp', [
    'ngCookies',
    'ngResource',
    'ngSanitize',
    'ngRoute',
    'btford.socket-io',
    'lumx'
  ] )
    .config( function ( $routeProvider, $locationProvider, $httpProvider )
    {..................


i tested one more with clear project but same error happened
could you check again?

thanks a lot

**Comment by ThomasCrvsr** [comment]
Hum, could you import jquery before angular to force AngularJS using Jquery and not JQLite ? I'm not sure but the function ```appendTo``` may not be present in JQLite.

**Comment by YoungsoonLee** [comment]
i founded the answer of this problem. i make my project with angular-fullstack.
After making  the basic project with yo , jquery position should be changed before angular.js in index.html.

thank you for everyone~!
