### ISSUE TITLE
DatePicker: not according to material design

### ISSUE THREAD

**Issue by nishith29** [lumapps/lumX#118]
Material design says, result of action should come out of point of action. In current datepicker, clicking on data, it appears as dialogue and originates from top of the screen. This is usefull in mobile version of datepicker, but not the desktop version. Also, I have seen the range selection is in enhancement. I want to work on both this points if concerned person find it genuine.

**Comment by malexandre** [comment]
Hi!

The "Point of origin for animation" is in on the roadmap. It's not directly linked to the datepicker, it's more a core feature of the framework, and in that case applied to the dialog box. We're going to rework on most of the animations that need it, but not for now.

As for the range for the datepicker, we're not working on it currently, so feel free to start. I'm available to discuss anything regarding lumX on [Twitter](https://twitter.com/thagou) or [G+](https://plus.google.com/u/0/112017292931075994945). We also have official Lumapps account managed by @matmkian ([Twitter](https://twitter.com/lumapps) or [G+](https://plus.google.com/u/0/+LumApps/)).

**Comment by nishith29** [comment]
Hi

I have already forked the project and will start development on range. I don't find build directory, hence demanding scripts in index.html are not found and localhost behaves very wierdly. Can you guide me with setup? Can we have a chat on hangout or some?

**Comment by malexandre** [comment]
I'm available on chat.
Did you run `gulp`? Running this should create the `build` directory.

**Comment by nishith29** [comment]
yup, Thanks. Done. How do i find you on chat?

**Comment by malexandre** [comment]
You have my G+ in my previous post from an hour ago.

**Comment by matmkian** [comment]
Date picker has now a year selector. Still have to work globally about the "Point of origin for animation".
