### ISSUE TITLE
Select fired change event before update the scope... i think

### ISSUE THREAD

**Issue by olituks** [lumapps/lumX#120]
Hi, First I love this beautiful and most advanced framework.

If I use the change event on the select element the event is fired but the scope is not updated, it contain the last selection value in place of the current.

This image illustrate the case. I open for the first time the select component and I choose a value. The change event is fired and you can see the content of the scope = undefined in place of my selected value.

![image](https://cloud.githubusercontent.com/assets/144008/5820119/1a28c0f8-a0c3-11e4-8feb-4b39231d72cd.png)

This second image illustrate a second choose in the select element and the value in the scope.

![image](https://cloud.githubusercontent.com/assets/144008/5820198/93c39910-a0c3-11e4-8fdc-cfd888f4205f.png)

How I can react in the change event anf have a scope up-to-date with the current selected value?

**Comment by olituks** [comment]
OK I get the "problem". I use change event and not ng-change event. More explanation on each components are very welcome.

Have a good day.
Olivier

**Comment by malexandre** [comment]
Hi!
I really need to find the time to rework the docs site, a better API description would have help you to find the solution.
First, I will try to watch angular best practices to know if the change event must be launch after the effective change, but for now, this one is fired just before.
Knowing this, the change event is fired with the new and the old value. So if you declare your function like that in your DOM, you'll have the new and old value:

```html
<lx-select ng-model="selected" change="change(newValue, oldValue)" placeholder="Lorem Ipsum" choices="list">
            <lx-select-selected>
                {{ $selected.title }}
            </lx-select-selected>

            <lx-select-choices>
                {{ $choice.title }}
            </lx-select-choices>
        </lx-select>
```
