### ISSUE TITLE
Datepicker - display inline

### ISSUE THREAD

**Issue by acatcalledanarchy** [lumapps/lumX#121]
Hi there

Wonderful job on Lumx. This isn't an issue, more a request. Is it possible to display the datepicker directive inline rather than having it triggered by the field?

**Comment by malexandre** [comment]
Hi!

As said [previously](https://github.com/lumapps/lumX/issues/83#issuecomment-69350611), we're not going to make the datepicker in a non-modal way since we follow the Material Design specification.

**Comment by oidevelopment** [comment]
Cheers **malexandra**
