### ISSUE TITLE
Documentation should be improved 

### ISSUE THREAD

**Issue by alihalabyah** [lumapps/lumX#122]
I think there should be an example for each feature inside the UI for example how can I center a div?

**Comment by malexandre** [comment]
Hi!
We want that too. We just didn't find the time for now. But the whole documentation will be rework.

**Comment by maxsap** [comment]
+1 also for me, I am trying to find how this works and I keep deeging into code for finding out what happens and how components should work.

**Comment by FrancisPlaza** [comment]
+1 related to docu, would appreciate if you can include writeup about the grid system used. thanks

**Comment by yasminal** [comment]
+1 for the grid system. Had to revert back to Bootstrap in the meantime.

**Comment by matmkian** [comment]
Hi, we must find some time to provide full documentation, not easy... we're gonna have a talk with @malexandre about documentation very soon.

**Comment by Mavlarn** [comment]
+1, I am writing a mobile app with this, but I even can not create a tabs page. I created with <lx-tabs>, but the style is different with he demo site. There should some explanation about about how to use the css framework as a whole page.

**Comment by anonymoussc** [comment]
:+1: :hourglass_flowing_sand: :zap: :rocket:

**Comment by lfallet** [comment]
+1 for grid system and layout examples.
Is there a 12 columns layout ? For a responsive layout, is there some existing css classes or do we need to build it with @include media-query(desk) and @include media-query(portable) ?

**Comment by matmkian** [comment]
Soon, we'll provide a real documentation for LumX with a major release. Keep on eye on https://twitter.com/lumapps.
