### ISSUE TITLE
Forms and $setPristine();

### ISSUE THREAD

**Issue by oidevelopment** [lumapps/lumX#125]
How do you reset form field validation of ***lx-text-field*** ( in particular the ```valid``` and ```error``` attributes ) using ```$scope.formName.$setPristine();```

**Comment by tagazok** [comment]
Hi.

What I do in my projects. For each form, I have an empty object. When I want to clear the form and reset everything, I simply reset the object and set the pristine.

ex:
```javascript
function clear_form() {
      vm.role = angular.copy($scope.role_empty);
      $scope.roleEditForm.$setPristine();
}
```

**Comment by oidevelopment** [comment]
Cheers **tagazok** however this above approach doesn't reset the ```valid``` attribute of the ***lx-text-field*** attribute.

**Comment by malexandre** [comment]
Hi!
I do exactly the same as @tagazok. But what do you mean it doesn't reset the valid attribute? The valid attribute is supposed to be an expression, if you manage the pristine state and all in the expression, it should work. Can you give more context for us to help you?

**Comment by oidevelopment** [comment]
Of course **@malexandre**:


In view:

```
<lx-text-field
                data-label="First name"
                data-valid="vm.validField(profileForm.firstName.$error) && ( profileForm.firstName.$touched || profileForm.$submitted )"
                data-error="!vm.validField(profileForm.firstName.$error) && ( profileForm.firstName.$touched || profileForm.$submitted )">
                <input
                    type="text"
                    name="firstName"
                    data-ng-model="vm.user.first_name"
                    required>
            </lx-text-field>
            <ul class="form-error" data-ng-messages="profileForm.firstName.$error" data-ng-if="!vm.validField(profileForm.firstName.$error) && ( profileForm.firstName.$touched || profileForm.$submitted )">
                <li data-ng-message="required">Enter your first name</li>
            </ul>
````


In controller: 

```
function validField(errors) {
			if(_.isEmpty(errors)) {
				return true;
			} else {
				return false;
			}
		}
```

**Comment by malexandre** [comment]
I always used "$pristine", never "$touched". But it still should work. I'll try to see that later today.

**Comment by oidevelopment** [comment]
**@malexandre** thanks for your help, I will amend my code to use ```$pristine``` rather than ```$touched``` as that sounds like a sensible idea **;)**
