### ISSUE TITLE
Erro lumX with RequireJS

### ISSUE THREAD

**Issue by douglaslira** [lumapps/lumX#128]
Error: [$compile:tplrt] Template for directive 'lxTab' must have exactly one root element. lumx.tab.html

**Comment by malexandre** [comment]
Hi!
Do you use the bower version or the github version? In the github version, the templates are not converted into javascript, so I'm not sure it will work properly with it. But the `lumx.jsòr `lumx.min.js` in the dist folder (after a `gulp dist` or from the bower version) should contain all the templates.

**Comment by matmkian** [comment]
As the project architecture has changed, I close this issue.
