### ISSUE TITLE
Does not work on IE10

### ISSUE THREAD

**Issue by bseufert** [lumapps/lumX#129]
Input fields do not become editable on Internet Explorer 10.  see http://ui.lumapps.com/directives/text-fields  in Internet Explorer 10.

**Comment by bseufert** [comment]
Actually, it's the site, not the input fields.  

.sidebar-filter {
     position: fixed;
}

needs to change to 
position: relative;

**Comment by malexandre** [comment]
Hi! I'll manage the older verison of IE after some rework. I know most of the sutff works well under IE11.

**Comment by bseufert** [comment]
Hi.  It looks like the components all work on ie10.  It's just the demo website sidebar filter is overlaying the content. 

Thanks,  brent
