### ISSUE TITLE
Change font path

### ISSUE THREAD

**Issue by nolandubeau** [lumapps/lumX#131]
Hello,

I am trying to integrate with an existing Grunt build system to change the font path within dist/css/lumx.css. is the ../fonts/ path configurable in the scss files? Ultimately the build requires that all fonts and images reference 'assets/fonts/' etc. instead of ../fonts/. Alternatively can you recommend an appropriate grunt task to perform such a change?

Thanks in advance.

Nolan

**Comment by malexandre** [comment]
Hi!

By importing lumx into your sass file, you can just override the paths with this:

```scss
$roboto-font-path: "assets/fonts/roboto";
$md-icons-font-path: "assets/fonts/md-icons";

@import 'bower_components/lumx/dist/scss/main/_lumx.scss';
```

Without sass, as I don't use grunt, I'm not familiar with tasks to do this. I think [grunt-text-replace](https://github.com/yoniholmes/grunt-text-replace) might be what you're looking for, but there may be better solutions.

**Comment by matmkian** [comment]
As there is nor more font to include in the project, I close the issue.
