### ISSUE TITLE
no Button Ripple Effects On Click

### ISSUE THREAD

**Issue by RaedsLab** [lumapps/lumX#133]
i've installed using bower ... the buttons have no ripple effects On Click

**Comment by ThomasCrvsr** [comment]
Can you give more context ? Like how your button tags looks like in your code ?

**Comment by RaedsLab** [comment]
<html>
    <head>
        <link rel="stylesheet" href="bower_components/lumx/dist/css/lumx.css">
    </head>
    <body>
<button class="btn btn--xl btn--blue btn--raised" lx-ripple>Button</button>
<script src="bower_components/jquery/dist/jquery.js"></script>
<script src="bower_components/velocity/velocity.js"></script>
<script src="bower_components/moment/min/moment-with-locales.min.js"></script>
<script src="bower_components/angular/angular.js"></script>
<script src="bower_components/lumx/dist/js/lumx.js"></script>
    </body>
</html>

**Comment by malexandre** [comment]
Hi!

Is it all your code? There is no `app.js` or a module that you created to include? The `lx-ripple` is a directive that must be use inside your `ng-app`. If you don't create one depending on lumX, it won't do anything.

**Comment by matmkian** [comment]
In the end, did you success?

**Comment by RaedsLab** [comment]
I don't know my way around angular :/  I'm knind of lost here

**Comment by sethrubenstein** [comment]
Ditto. Some help would be appreciated. The documentation doesnt make it clear once you've included everything how to get the "directives" to work correctly.

**Comment by dhawken** [comment]
Did you add the 'lumx' dependency to your angular app?  Not having that would definitely cause the ripple to not work even though the button is displaying properly.

**Comment by sethrubenstein** [comment]
@dhawken I've added that in the footer of my page just `<script>angular.module('myModule', ['lumx']);</script>` and still none of the directives work correctly, including ripple.

**Comment by dhawken** [comment]
Do you have that module referenced in an ngapp directive on your html or body tag for the page?

`<body ng-app="myModule">`

**Comment by sethrubenstein** [comment]
@dhawken That did it. Thank you! Now I feel dumb.

**Comment by dhawken** [comment]
Sweet.

**Comment by RaedsLab** [comment]
Actually this issue is pretty awesome, it got me to finally start learning Angular
