### ISSUE TITLE
Responsive Datepicker too large for iPhone

### ISSUE THREAD

**Issue by lukeed** [lumapps/lumX#134]
The datepicker modal extends beyond the screen of iPhones 4 & 5. Without a close button at the top, or room to click on the backdrop, datepicker stays open until refresh.

**Comment by janmyler** [comment]
+1 for this. When I'm using the the native browser on my Xiaomi Mi4 and I get to a month with 6 rows of days, the OK button goes out of sight. The datepicker still can be closed taping away from it, but it's not the best ux.

**Comment by matmkian** [comment]
Hi, thanks for reporting, we'll take a look very soon.

**Comment by matmkian** [comment]
In the last version, we've reworked and fixed a lot of things. If this issue is still happening, please re-open the issue. Thank you!
