### ISSUE TITLE
Notification position

### ISSUE THREAD

**Issue by canemacchina** [lumapps/lumX#135]
Hi,

there's a way to change notification position?
In my application, I have a button in the bottom-right corner, and every time a notification is show, it overlap the button.
I would like to move notification from bottom-right corner to top-right.

**Comment by acatcalledanarchy** [comment]
I'm also curious about this - does it fit within Google Materials design specification?

**Comment by canemacchina** [comment]
Well, I don't know exactly what material design spec says about notification. But I'm pretty sure that normally they say that the main action button should be near the bottom-right corner, I suppose to be more accesible using mobile device with one hand...

**Comment by malexandre** [comment]
The button must be at the right bottom only on mobile display, and at the right "top" (at the jonction between the header and the background) for a desktop display.
I can't open the whiteframes from the spec, but if yo

**Comment by malexandre** [comment]
We did not manage the notification position for now, sorry. And I can't give you a CSS workaround as it's managed mainly by javascript. I'll try to make this tonight if I have the time since it should take me only a few minutes. The Notification service would have a `setPosition` with four values ('top-left', 'top-right', 'bottom-left', 'bottom-right'). I'll let you know once it will be available.

**Comment by malexandre** [comment]
And sorry for the misclick on the close isssue button. My touchpad does not always listen to me.

**Comment by acatcalledanarchy** [comment]
Ha ha **malexandre**

**Comment by malexandre** [comment]
Hmm, I can't think of a way to manage the piling with this. But we'll think on that. Not right now though.

**Comment by acatcalledanarchy** [comment]
No worries **malexandre**

**Comment by acatcalledanarchy** [comment]
```
position: fixed;
top: 50%;
left: 50%;
-webkit-transform: translate(-50%, -50%);
transform: translate(-50%, -50%);
```
