### ISSUE TITLE
Floating action button - icon not hidden

### ISSUE THREAD

**Issue by dominikbulaj** [lumapps/lumX#138]
Hi,
I just discovered that Floating action button when it's active (hovered) it hides initial icon (first i element). But after clicking on it (main big button) both icons are displayed on next hovers (screen attached). Also happens on http://ui.lumapps.com/css/fab

![screenshot_1](https://cloud.githubusercontent.com/assets/1233407/5983440/c135651a-a8cd-11e4-8741-3f2cc900c77e.png)

On screen you can see both icons from: 
```html
<button class="fab__primary btn btn--xl btn--blue btn--fab" lx-ripple lx-tooltip="Wylicz" tooltip-position="left">
    <i class="mdi mdi--add"></i>
    <i class="mdi mdi--redo"></i>
</button>
```

**Comment by matmkian** [comment]
Thanks for reporting, we'll fix it very soon!

**Comment by matmkian** [comment]
It's now fixed, i close the issue.
