### ISSUE TITLE
input[type=number] label issues

### ISSUE THREAD

**Issue by dominikbulaj** [lumapps/lumX#139]
Hi,
Another issue found. When I use `input[type=number]` and I input digits - it's ok. Label doesn't overwrite on input entry:

![screenshot_4](https://cloud.githubusercontent.com/assets/1233407/5984633/4a672fd0-a8d8-11e4-8d56-29126cc61a79.png)

But when I enter letters (you now - never trust user...) and move to another field I see label comes down and is over entered text:

![screenshot_3](https://cloud.githubusercontent.com/assets/1233407/5984651/75d1eea8-a8d8-11e4-98f2-95e736be6779.png)

`input[type=number]` is supported by almost all browsers on market: http://caniuse.com/#feat=input-number

**Comment by matmkian** [comment]
Hi, thanks for reporting. We'll take a look as soon as possible!

**Comment by jmls** [comment]
any news on this - it's biting me as well. thanks ;)

**Comment by wkeizer** [comment]
+1

**Comment by malexandre** [comment]
I'll try to fix it this week.

**Comment by matmkian** [comment]
In the last version, we've reworked and fixed a lot of things. If this issue is still happening, please re-open the issue. Thank you!
