### ISSUE TITLE
date-picker reset

### ISSUE THREAD

**Issue by olituks** [lumapps/lumX#141]
This is my date picker 
```html
<lx-date-picker model="filter.end_date" label="End date" class="margin-right-5"></lx-date-picker>
```
I would like to know how I can reset the value programmatically. Currently I set the value $scope.filter = {} but nothing happen.

**Comment by matmkian** [comment]
Hi, I think you should set your variable to undefined.

**Comment by malexandre** [comment]
No response, I'm closing. Feel free to add a comment here if needed.
