### ISSUE TITLE
ng-click, ui-sref not working in Tabs

### ISSUE THREAD

**Issue by cooljith91112** [lumapps/lumX#145]
I'm using ui-router for routing. I cannot swtich state with ui-sref so I tried ng-click. But even the ng-click is not working for tabs now. I checked whether this was a routing issue but its not. Routing are working as it should be, 

           <lx-tab heading="heading1" ui-sref="home.view1">
                <div ui-view="view1"></div>
            </lx-tab>

           <lx-tab heading="heading2" ng-click="switchState('home.view2')">
                <div ui-view="view2"></div>
            </lx-tab>
           

seems like events are not working properly or did I missed something else.

**Comment by cooljith91112** [comment]
bump!

**Comment by matmkian** [comment]
Interesting issue... We've not tested tabs with angular ui-router. As we use it on our projects, we're going to check it as soon as possible.

**Comment by jmls** [comment]
what was the findings ? ;)

**Comment by eclipse1985** [comment]
+1

**Comment by eclipse1985** [comment]
+1

**Comment by Toolito** [comment]
+1

**Comment by jmls** [comment]
hellooooo ? Does anyone from Lumx actually visit issues at all ?

**Comment by malexandre** [comment]
Hi, and sorry for the delay. We were really overflowed by our projects. We'll be giving more time for lumx now. So yeah, we'll try to update the tabs to manage state and/or click.

**Comment by alex-oliveira** [comment]
+1

**Comment by matmkian** [comment]
Sorry but won't fix.

**Comment by mgraszek** [comment]
Are you going to add ng-click to tabs?

**Comment by mgraszek** [comment]
+1
