### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by ekarlso** [lumapps/lumX#147]
Maybe a stupid question, but how does one do a navbar or nav with lumx?

**Comment by tagazok** [comment]
What do you call a navbar?
If this can help, you may find a toolbar in the documentation here : http://ui.lumapps.com/css/toolbars

**Comment by matmkian** [comment]
Hi, we're going to put some layouts in LumX website.
You'll find a navbar in one of them. Be patient, it will come soon :-)
