### ISSUE TITLE
Icons are not working in verson 0.3.2

### ISSUE THREAD

**Issue by theknightsky** [lumapps/lumX#148]
Suddenly the icons are not working at all in version 0.3.2. I was just using version 0.2.54 yesterday and everything was working fine. I starting working on a new project and installed lumx via bower today, and I can't get any of the icons to show up.

**Comment by naruraghavan** [comment]
(one - instead of --) mdi- as opposed to: mdi-- for an icon.

Try:

<i class="mdi mdi-menu"></i>

as opposed to:

<i class="mdi mdi--menu"></i>

**Comment by naruraghavan** [comment]
Make sure that you have:
```html
        <link rel="stylesheet" href="bower_components/mdi/materialdesignicons.css">
        <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:300,400,500,700">
```
in your index.html

**Comment by theknightsky** [comment]
This works. ^^ I included the stylesheets in my document and used one slash (-) instead of two (--). It was nice not having to directly include the styles before though. I hope the docs on the Lumx site are updated soon to include these changes. Thank you for your help.

**Comment by matmkian** [comment]
Yes, you're right, it was nice to have icons included to our framework.
The problem is that we don't have time to maintain such a library... So we decided to use material design icons from Austin Andrews as it seems to be very complete and updated frequently.

**Comment by theknightsky** [comment]
That's totally understandable, and probably better in the long run. Thanks for your help.
