### ISSUE TITLE
bower.json main css and js paths

### ISSUE THREAD

**Issue by priithansen** [lumapps/lumX#149]
Hi,

Not 100% sure but shouldn't the paths in bower.json "main" section be without the subfolders?
https://github.com/lumapps/lumX/blob/master/bower.json#L16-L17

**Comment by sondreb** [comment]
It appears they moved the CSS and JS files in one of the latest commits. Please update, as tasks such as "grunt-wiredep" now fails due to invalid bower configuration.

**Comment by priithansen** [comment]
Made a pull request https://github.com/lumapps/lumX/pull/150

**Comment by malexandre** [comment]
Hi! Sorry totally forgot to change those. I made the change in b09e04fe8424957cdf2dfdb6bcbac32a88e0e953 exactly like in you PR but with the right message to appear in the changelog. Thank for the help!
