### ISSUE TITLE
Icon Path Changes Coming Soon

### ISSUE THREAD

**Issue by Templarian** [lumapps/lumX#151]
I just wanted to give you a heads up. As I approach the `beta` release of the icon set there will be a breaking change. The paths are being modified to match the popular Font Awesome icon set.

https://github.com/Templarian/MaterialDesign/issues/126

Could be an issue for your users not using bower and just downloading the latest icon set manually.

I'll comment on this issue once this change is made.

**Comment by matmkian** [comment]
Hi, first of all, we'd like to thank for your work :-)
No problem for the breaking change, we'll update our documentation when it will be done.
We really appreciate.

**Comment by Templarian** [comment]
The changes went into `v0.9.21-alpha`.

Please tell users to reference `css/materialdesignicons.min.css`. This will be the only breaking update.

This release only contains the SASS files. LESS is being worked on for the next release. I'll leave this open for you to track the change in documentation.

**Comment by matmkian** [comment]
Thank you very much !
After updating  to v0.9.21-alpha, icons are rendering strangely.
On before pseudo element, icon is left-aligned whereas it was centered...

You can see an exemple in our buttons:
![buttons](https://cloud.githubusercontent.com/assets/2914789/6339212/9b85880a-bbb4-11e4-862a-966824f262bd.png)

**Comment by Templarian** [comment]
That was a fix in my stylesheet. I did my best to match how font-awesome does things. They appear to let the external CSS [user defined or framework] handle these things.

Is this something you can fix CSS? I'm trying to keep it keep it inlined with Font Awesome so it can be more plug and play.

**Comment by Templarian** [comment]
I just looked to see if you have any classes on the top level that identify it as a lumX app for a temporary fix, but I'm not seeing anything. That would have been the quickest fix until lumX released a version with CSS to handle the missing centering.

**Comment by matmkian** [comment]
Thanks for your quick answer :-)
I think i can't do anything with CSS.
The icon in pseudo element is left-aligned unlike font-awesome.

![capture d ecran 2015-02-24 a 00 00 09](https://cloud.githubusercontent.com/assets/2914789/6339643/23191842-bbb8-11e4-958c-5582651da0c3.png)
![capture d ecran 2015-02-24 a 00 01 53](https://cloud.githubusercontent.com/assets/2914789/6339658/5f0963f2-bbb8-11e4-89d6-fc06b4d0df65.png)

**Comment by Templarian** [comment]
.fa vs .mdi:
![image](https://cloud.githubusercontent.com/assets/338885/6339821/e8e5a5d4-bb7e-11e4-9661-3b068a182856.png) 

The pseudo element:
![image](https://cloud.githubusercontent.com/assets/338885/6339832/037cdf7a-bb7f-11e4-88d7-0fee90c3da9e.png)

![image](https://cloud.githubusercontent.com/assets/338885/6339880/7b7c184c-bb7f-11e4-957e-fa290dcb7875.png) ![image](https://cloud.githubusercontent.com/assets/338885/6339844/1fd572d6-bb7f-11e4-8819-470511856d91.png)

I'm not seeing any centering in Dave's FontAwesome CSS.

**Comment by matmkian** [comment]
Maybe it comes from the font ?
I'm going to invest tomorrow !

Le mardi 24 février 2015, Austin Andrews <notifications@github.com> a
écrit :

**Comment by matmkian** [comment]
Hi,
After deeper invest, it seems really impossible to fix it with CSS.
I really think it comes from the webfont...

**Comment by Templarian** [comment]
Your current HTML / CSS

```html
<i class="icon icon--l icon--grey icon--circled mdi mdi-android"></i>
```

Line 4793 in lumx.css
```css
.icon {
vertical-align: top;
text-align: center;
}
```

**Comment by Templarian** [comment]
I edited my message above to show both places the `text-align: center` is defined. This should be working... I've double checked the Material Design Icons [css](https://github.com/Templarian/MaterialDesign-Webfont/blob/master/css/materialdesignicons.css) does not define a `text-align`.

**Comment by Templarian** [comment]
I found the issue. The woff2 build is broken I believe. I'll  have to look into it after the bar tonight.

**Comment by Templarian** [comment]
I didn't understand what you meant by left aligning till I actually started to inspect the other icons. Not sure why the grunt-webfont is doing this. All previous builds have used the same configs. They must have changed something recently.

**Comment by Templarian** [comment]
I pushed a fix with a woff2 file that works. `v0.9.22-alpha`. I have to figure out what is going on with the `grunt-webfont` package still (I generated the woff2 with another solution).

Just got back from the bar, so I'll investigate what is going on with `grunt-webfont` tomorrow. I submitted a bug to their repo after running it again seeing the same results. :confused:

**Comment by matmkian** [comment]
Thank you very much !!
Works like a charm since last update :-)
