### ISSUE TITLE
Feature Request: Permanent Tooltip For Sub FABs

### ISSUE THREAD

**Issue by danielhickman** [lumapps/lumX#152]
Like in mobile material design apps, the children floating action buttons have a permanent tooltip for each one. This would be helpful for mobile users that won't be able to the the tool tips or a list of similar objects for certain uses on desktop.

![screenshot feb 8 2015 1-21-29 am](https://cloud.githubusercontent.com/assets/5341898/6096041/0f76f856-af31-11e4-9f92-e20747c66a7e.png)

**Comment by matmkian** [comment]
Yes you're right... LumX FAB is not optimized for mobile devices.
Soon it will be, as we have to use it in a responsive project :-)
