### ISSUE TITLE
lx-file-input example?

### ISSUE THREAD

**Issue by jimgeiger** [lumapps/lumX#153]
I love your file-input directive but is there an example on how to use it?   Thanks a lot

**Comment by matmkian** [comment]
Maybe this issue will help you?
https://github.com/lumapps/lumX/issues/44

**Comment by jimgeiger** [comment]
Thanks very much, that post does indeed explain the change handler which works fine.  But the problem I'm having is the file name label is not being updated after selecting a file.  My code is exactly like the example .  Do I need to do something about that in the change handler?
```javascript
<div flex-item>
   <lx-file-input label="Browse to APK File..." change="upload(e)"></lx-file-input>
</div>
```

**Comment by matmkian** [comment]
I let @floor0669 answer to you

**Comment by sumanthag** [comment]
Hi, I'm also pretty new to the framework and I simply cannot get it to work. How do I capture the file and submit that in a post request? I read the issue #44 and used the change attribute but I just cannot get the file to post.

var config = {headers: {'Content-Type': 'multipart/form-data;'}}
        $http.post('/upld', filein, config) // how do i get the file here?
            .success(function(data, status, headers, config) {
                console.log("file upload successful"); // nothing goes to the server after the post
               
            })

**Comment by matmkian** [comment]
In the last version, we've reworked and fixed a lot of things. If this issue is still happening, please re-open the issue. Thank you!
