### ISSUE TITLE
Search filter

### ISSUE THREAD

**Issue by ronnkriibi** [lumapps/lumX#154]
Hi.

I have a question about search filter, can it be used somehow like the [select](http://ui.lumapps.com/directives/selects) directive so that I would have dropdown with possible candidates ? 

Really sorry If it seems a stupid question, but I just could not find a way to implement a search box with selectable values.

**Comment by matmkian** [comment]
Maybe this component?
http://ui.lumapps.com/directives/selects

**Comment by malexandre** [comment]
I'm closing the issue because we have no news. Feel free to post a new message here as I won't lock the issue.
