### ISSUE TITLE
Incorrect position offset on stacking notifications with variant lengths content

### ISSUE THREAD

**Issue by gaga1227** [lumapps/lumX#156]
**Use Case:**
Correct position offsets on notifications are expected when triggering notifications with different lengths content.

**lumX Version(s):**
v0.3.3

**Browsers and Operating System:**
All browsers

**Reproduce the Error:**
1. Trigger multiple notifications with different lengths of content
2. The notifications in the stack show incorrect position offsets

**Fix/Solution:**
The offset margin calculation logic needs to be updated, I have done a fix and tested from my end, can I do a pull request?

**Screenshot:**
![incorrect-position-offset](https://cloud.githubusercontent.com/assets/740859/6147053/7a0c7e84-b247-11e4-9341-f5f9bb205551.png)

**Comment by malexandre** [comment]
Hi!

I thought this was working. But yeah, I'll be glad to check your PR. Think to follow the [contributing guidelines](https://github.com/lumapps/lumX/blob/master/CONTRIBUTING.md).

**Comment by gaga1227** [comment]
Yes, it was working when all your notifications have the same heights. Once you start giving them different contents, which resulted in different notification heights, the problem shows.

I have submitted the pull request, please kindly review :)
