### ISSUE TITLE
+sign, double minus, double underscore meaning in directive

### ISSUE THREAD

**Issue by reidlai** [lumapps/lumX#158]
Is there any document discussing the usage of  +, --, __ in directive?  Thanks

**Comment by malexandre** [comment]
Hi! As said in our contributing guidelines, we follow the [BEM notation](http://cssguidelin.es/#bem-like-naming), and mostly all of the guidelines by Harry Roberts I just linked.
The "+" is not documented for now, but it will be soon. It's part of some helpers:

- `p` for padding
- `m` for margin
- `t`, `b`, `l`, `r` for top, bottom, left, right (for example: `pt` means padding top, and `ml` margin left)
- `v`, `h` for vertical & horizontal (combine top/bottom and left/right).

By default each margin & padding are 8px with those helpers. `class="m pt"` means `margin: 8px; padding-top: 8px;`.
Using the + increment the value. `pt+` means `padding-top: 16px;`, `pt++` is `padding-top: 24px;` and `pt+++` is `padding-top: 36px;`. There is also `pt-` which is `padding-top: 4px;`.

And finally, there is the `0`. `class="m0 pt++ ph0"` means `margin: 0; padding-top: 24px; padding-right: 0; padding-left: 0;`.

If you want all the classes listed, they're here : https://github.com/lumapps/lumX/blob/master/core/scss/trumps/_spacing.scss.

**Comment by reidlai** [comment]
Can AngularJS support BEM notation?
2015/2/14 上午12:31 於 "Marc Alexandre" <notifications@github.com> 寫道：

**Comment by malexandre** [comment]
I don't really understand. BEM is only for the CSS. And the directives in angular can't really follow this convention because of the slug/camel case conversion.

**Comment by matmkian** [comment]
I agree with @malexandre.
Did this answer help you?

**Comment by reidlai** [comment]
Yes and thanks
2015/2/21 上午2:13 於 "matmkian" <notifications@github.com> 寫道：
