### ISSUE TITLE
Documentation for Selects needs updating

### ISSUE THREAD

**Issue by nolandubeau** [lumapps/lumX#159]
Hi,

The documentation is incorrect for the Selects directive.  It does not contain the functions for toModel or toSelection.  Just wasted two hours trying to figure out why the cbSelect wasn't firing, and finally figured it out by digging through the source code of the site.  The documentation should be updated to:   

// Single select with ajax and change handler
                                $scope.ajax = {
                                    selected: 'Inception',
                                    list: [],
                                    update: function(newFilter) {
                                        if (newFilter) {
                                            $scope.ajax.loading = true;
                                            $http.get('http://www.omdbapi.com/?s=' + escape(newFilter)).
                                            success(function(data) {
                                                $scope.ajax.list = data.Search;
                                                $scope.ajax.loading = false;
                                            }).
                                            error(function() {
                                                $scope.ajax.loading = false;
                                            });
                                        } else {
                                            $scope.ajax.list = false;
                                        }
                                    },
                                    toModel: function(data, callback) {
                                        if (data) {
                                            callback(data.Title);
                                        } else {
                                            callback();
                                        }
                                    },
                                    toSelection: function(data, callback) {
                                        if (data) {
                                            $http.get('http://www.omdbapi.com/?s=' + escape(data)).
                                            success(function(response) {
                                                callback(response.Search[0]);
                                            }).
                                            error(function() {
                                                callback();
                                            });
                                        } else {
                                            callback();
                                        }
                                    },
                                    loading: false
                                };

                                $scope.cbSelect = {
                                    exec: function(newVal, oldVal) {
                                        LxNotificationService.notify('Change detected!');
                                        console.log('oldVal: ', oldVal);
                                        console.log('newVal: ', newVal);
                                    }
                                };

**Comment by matmkian** [comment]
I let @malexandre answer to you
