### ISSUE TITLE
theme colours

### ISSUE THREAD

**Issue by jmls** [lumapps/lumX#160]
is it possible to set a colour "theme" ? Angular Material allows me to do this

```javascript
angular.module('myApp', ['ngMaterial'])
.config(function($mdThemingProvider) {
  $mdThemingProvider.theme('default')
    .primaryPalette('pink')
    .accentPalette('orange');
});
```
I was wondering if there was a similar thing for lumx. Also, is there a google groups for lumx ?

thanks

**Comment by jmls** [comment]
anyone ? ;)

**Comment by matmkian** [comment]
Hi, we need to work on it as we only have scss variables that are not used in our components...

**Comment by matmkian** [comment]
We're working on this enhancement. Soon a new release of LumX with real documentation and major enhancements. Keep an eye on https://twitter.com/lumapps.

**Comment by wkeizer** [comment]
+1

**Comment by matmkian** [comment]
In the last version, we've reworked and fixed a lot of things. If this issue is still happening, please re-open the issue. Thank you!
