### ISSUE TITLE
Any nodejs step by step example?

### ISSUE THREAD

**Issue by jdzuri** [lumapps/lumX#161]
Hi,

I try to use this framework with node.js as backend. Any step-by-step example?

I think that this framework documentation, in general, is very little and it's a pain because it looks very good.

Thanks!

**Comment by ThomasCrvsr** [comment]
Your nodeJS only have to serve static files of your front-end application (this is not really related to LumX). The front-end app will use angular and you will have to follow these steps to use LumX in your angular app : http://ui.lumapps.com/getting-started/installation

**Comment by matmkian** [comment]
@ThomasCrvsr +1
