### ISSUE TITLE
drag and drop

### ISSUE THREAD

**Issue by jmls** [lumapps/lumX#163]
are there any problems with using the drag and drop directives from https://github.com/codef0rmer/angular-dragdrop ? I cannot for the life of me get them to work using lumx

anyone managed to get drag and drop working with this framework ?
thanks

**Comment by tagazok** [comment]
Hi jmls,

We use https://github.com/marceljuenemann/angular-drag-and-drop-lists and it works nicely with lumx :)

**Comment by jmls** [comment]
@tagazok , thanks so much for the link. haven't come across this one before. Any special hints / tips that you have for making the two work together ?

**Comment by matmkian** [comment]
Hi,

We also use angular drag and drop lists on our project and it works perfectly with LumX, no special tips.
