### ISSUE TITLE
lx-date-picker with ng-disabled

### ISSUE THREAD

**Issue by siteslave** [lumapps/lumX#164]
I can't use ng-disabled for lx-date-picker, what can i do?

exp:
```jade
lx-date-picker(model="startDate", label="Start date", ng-disabled="true")
```

But I still able to click date picker.

**Comment by siteslave** [comment]
And, in version `0.2.51` I can set date to `lx-date-picker` but in version `0.3.9` I can't set date to `lx-date-picker`

Thanks.

**Comment by matmkian** [comment]
Hmmm, it seems strange as we use the date picker in our projects.
Can you show us your code?

Finally, we will add disabled state by getting out the input outside the directive.
Come soon :-)
