### ISSUE TITLE
I need a Demo / Example On Date Picker and Tabs

### ISSUE THREAD

**Issue by riyastir** [lumapps/lumX#165]
I can't make the date picker and Tabs working on my project

**Comment by matmkian** [comment]
Hi,

Can you give us an example?

You can see examples about these features here:
http://ui.lumapps.com/directives/date-picker
http://ui.lumapps.com/directives/tabs

**Comment by malexandre** [comment]
I'm closing the issue since we didn't have any news. Feel free to respond again, we'll answer.
