### ISSUE TITLE
Overriding palette colors

### ISSUE THREAD

**Issue by dhawken** [lumapps/lumX#171]
Could there be a way to override colors in an existing palette? This might be not allowed and I should just write my own, but I do like the handy bgc-* classes that reference palette entries. These are not overrideable so even though the palette colors are, none of these classes pick up values.

I can override the base palette colors and that seems to work in places where there are utility classes, but not palette entries.

Example:
I can do this in a custom file:
$red: #123456;
$red-400: #abccd;

I'm now able to use classes like "btn--red " and get the new values, but things like "bgc-red-400" are not overridden. Maybe the palette entries don't have !default on them on purpose and per spec, and the utility classes are easily reproduced, so maybe not a big deal.

**Comment by malexandre** [comment]
It's from the spec as you said. We may have some divergence as I've read on another issue, but it won't be accessible to override. But remaking your own is quite simple. If you want just a few colors, you just have to declare the `bgc-color` as you please.
