### ISSUE TITLE
Radio group button rendering incorrectly

### ISSUE THREAD

**Issue by acatcalledanarchy** [lumapps/lumX#173]
I don't know if it's just me but I've updated to the latest version and updated icons accordingly. However the radio button group renders as map pin:

![screen shot 2015-02-23 at 15 20 33](https://cloud.githubusercontent.com/assets/798187/6330368/8831518e-bb6f-11e4-97f9-8c3af3866713.png)

...which is the following icon listed here: http://materialdesignicons.com/
![screen shot 2015-02-23 at 15 18 18](https://cloud.githubusercontent.com/assets/798187/6330350/5ed082d8-bb6f-11e4-802f-7c63f1ea3a36.png)

which has the following reference in the CSS: 
![screen shot 2015-02-23 at 15 21 12](https://cloud.githubusercontent.com/assets/798187/6330376/9de334b6-bb6f-11e4-9fa4-d63128fc8ed2.png)

**Comment by acatcalledanarchy** [comment]
I've just had a quick look in

and it would appear that it should be:

```css
.mdi-radiobox-blank::before {
  content: "\f3b1";
}

.mdi-radiobox-marked::before {
  content: "\f3b2";
}```

**Comment by matmkian** [comment]
It's due to a recent update of the icon library we use.
It's now fixed. I close the issue.

**Comment by acatcalledanarchy** [comment]
Nice one **@matmkian**

**Comment by jameswyse** [comment]
@matmkian: This seems to have happened again, demo site shows telephone icons for radio buttons :D
