### ISSUE TITLE
Create a directive for Radio, Checkbox, and switch

### ISSUE THREAD

**Issue by iamgurdip** [lumapps/lumX#174]
First of all great work, thank you! I would like to suggest creating a directive for Radio button, Checkbox and switch.

Thanx.

**Comment by ThomasCrvsr** [comment]
Have you got a special motivation for having directives instead of just overwriting the style of native HTML5 component ?
IMHO, having directives doesn't bring more value than what's already done with the CSS.

**Comment by matmkian** [comment]
I agree with @ThomasCrvsr

**Comment by iamgurdip** [comment]
Having a directive would cut down on the amount of markup that needs to be created, similar to the way there is a directive for text-field. Currently i am using radio in ng-repeat, and for the Id's i have to be sure to create unique id's (granted it's not hard can use $index), but the directive could take care of that and even isolate the scope so there is no conflict.

**Comment by matmkian** [comment]
I think that when we can do it without javascript, it's lighter. But you're right, markup would be simpler, we'll think about it.

**Comment by matmkian** [comment]
It's done but not documented yet. Take a look to the source code or wait a little. We're working on this enhancement. Soon a new release of LumX with real documentation and major enhancements. Keep an eye on https://twitter.com/lumapps.
