### ISSUE TITLE
"data" is a reserved scope field for lx-select

### ISSUE THREAD

**Issue by dannylagrouw** [lumapps/lumX#175]
Maybe worth mentioning in the docs for lx-select: don't use "data" as a scope field, as in:

```xml
<lx-select ng-model="something" placeholder="Something" choices="data.somethings" floating-label>
```

I couldn't get this to work until I discovered that "scope.data" is also used by lx-select. Solved it by changing the name of my own data object:

```xml
<lx-select ng-model="something" placeholder="Something" choices="mydata.somethings" floating-label>
```

**Comment by nullart** [comment]
I got the same issue as well. 

This just shows, that $scope.data is a widely used. Can lumx change $scope.data to $scope.lxSelectData instead?

**Comment by AntiFreez** [comment]
See https://github.com/lumapps/lumX/issues/311

**Comment by malexandre** [comment]
There is still some data in the project, but they will be removed when we'll change the file containing them. They do not create problems anymore, but just to be sure we'll change them. Thank you!

**Comment by nullart** [comment]
awesome!
