### ISSUE TITLE
Use dialog as a confirm box

### ISSUE THREAD

**Issue by tagazok** [lumapps/lumX#180]
Hi,

I would like to use dialog to make a confirm delete box.
I have a list of elements and when I click "delete", I want the dialog box to ask for confirmation.
Is there a way to either send an object to the dialog box or have a callback with parameter (send back what button has been clicked for example).

Thanks

**Comment by marcosloic** [comment]
I did that for the mobile version, as the confirm dialog doesn't fit into my iPhone 5 screen.

Basically, create a function that opens the dialog, call it when you click on your delete button. Pass the item as an argument

```javascript
$scope.itemToDelete = {};

$scope.openDialog = function (item) {
		LxDialogService.open('myDialog');
        $scope.itemToDelete = item;
	}
```

Now you create a function that will delete the item when you click on "Yes"

```javascript
$scope.delete = function() {
    Do something here
    $scope.items.splice($scope.items.indexOf($scope.itemToDelete),1);
    $scope.itemToDelete = {};
}
```

It works, but it's dirty, as you have to manually reference the id of the dialog in your controller.

**Comment by malexandre** [comment]
Why do you not use the confirm box directly? It's exactly its purposes. You can see it here: http://ui.lumapps.com/services/notifications
