### ISSUE TITLE
Date-picker

### ISSUE THREAD

**Issue by Lejendarm** [lumapps/lumX#181]
Hello, I'm looking for a way to catch an event on change in the date-picker assigned model.
Is there a way to actually do that ? like passing a function "on-save" or something

**Comment by Mavlarn** [comment]
How about adding a $watch on that model?

**Comment by Lejendarm** [comment]
Thanks for the reply and you're right it will work, but I wanted to avoid watcher on my application, that's why asked for a way to pass directly a function to the lumx directive

**Comment by Argetloum** [comment]
Thanks for yours replies. 
I've just created a pull request that fix that issue. Just have to wait the build now ! :).
