### ISSUE TITLE
How to use with PHP?

### ISSUE THREAD

**Issue by sethrubenstein** [lumapps/lumX#183]
So probably a dumb question, I know almost nothing about Angular.
I'm trying to use Lumx in a WordPress project I've included all the dependencies and I've confirmed Angular is working by trying this simple Angular code: ` <input type="text" ng-model="yourName" placeholder="Enter a name here">
      <h1>Hello, {{ yourName }}!</h1>` and that works. However, when I try and use the lumx dropdown for example `<lx-dropdown>
    <button class="btn btn--m btn--black btn--flat" lx-ripple lx-dropdown-toggle>
        Dropdown toggle
    </button>

    <lx-dropdown-menu>
        <ul>
            <li><a class="dropdown-link" ng-click="dropdownAlert()">Notification</a></li>
            <li><a class="dropdown-link">Another action</a></li>
            <li><a class="dropdown-link">Something else here</a></li>
            <li class="dropdown-divider"></li>
            <li><span class="dropdown-link dropdown-link--is-header">Header</span></li>
            <li><a class="dropdown-link">Separated link</a></li>
        </ul>
    </lx-dropdown-menu>
</lx-dropdown>` It 1. doesnt do whats expected and 2. it actually displays that ul element as if angular isnt picking up on the lx-dropdown tag?

Can anyone help me?

**Comment by ThomasCrvsr** [comment]
Is that your entire code for the dropdown ? Or did you correctly include the code you posted in a <lx-dropdown> (with a button like in this example http://ui.lumapps.com/directives/dropdowns )
Have you included lumx as a module dependancy in your Angular app ?
