### ISSUE TITLE
ng-click not working on tabs

### ISSUE THREAD

**Issue by marcosloic** [lumapps/lumX#184]
Hey guys :-)

So I was trying to use the tabs along with ui-router to switch views. It didn't work as-is with the "ui-sref" attribute so I tried do to something with ng-click, but no matter what I try I can't make it work.

**Comment by siteslave** [comment]
+1

**Comment by malexandre** [comment]
I'll look into that later, but for now I can't. I'll get back as soon as I can.

**Comment by nelson687** [comment]
I have the same problem, tried to fork the project but didn't work yet

**Comment by philippeBchn** [comment]
Hi !

Pending solution you can set a var for active-tab and watch it to replace a ng-click.

**Comment by matmkian** [comment]
Sorry but won't fix.
