### ISSUE TITLE
How to get the value from the ng-model in multiple selects

### ISSUE THREAD

**Issue by Ceall8650** [lumapps/lumX#185]
I copy the example from the official site
index.html: 

    <div flex-item>
        <lx-select ng-model="selects.selectedPersons" placeholder="Lorem Ipsum" choices="people" multiple floating-label>
            <lx-select-selected>
                {{ $selected.name }} - {{ $selected.age }}
            </lx-select-selected>

            <lx-select-choices>
                {{ $choice.email }}
            </lx-select-choices>
        </lx-select>
    </div>

app.js : 

    $scope.people = [
      { name: 'Adam',      email: 'adam@email.com',      age: 10 },
      { name: 'Amalie',    email: 'amalie@email.com',    age: 12 },
      { name: 'Wladimir',  email: 'wladimir@email.com',  age: 30 },
      { name: 'Samantha',  email: 'samantha@email.com',  age: 31 },
      { name: 'Estefanía', email: 'estefanía@email.com', age: 16 },
      { name: 'Natasha',   email: 'natasha@email.com',   age: 54 },
      { name: 'Nicole',    email: 'nicole@email.com',    age: 43 },
      { name: 'Adrian',    email: 'adrian@email.com',    age: 21 }
    ];

    $scope.selectedPersons = [$scope.people[2], $scope.people[4]];

But, it did't show the default selections on the view. And when I change the selections , the value in the model did't change. How can I solve it?

**Comment by Ceall8650** [comment]
The View
1. There were two objs in the model, but it didn't show any tag.
![1](https://cloud.githubusercontent.com/assets/4955198/6498277/2787404c-c325-11e4-8bd7-15d08fd3ae49.png)

2.  When I selected a item , no new item  added to model.
![2](https://cloud.githubusercontent.com/assets/4955198/6498290/71087a4c-c325-11e4-90ca-82b3403a9afa.png)

3.  When I unselect the item, all objs in model were delete. 
![3](https://cloud.githubusercontent.com/assets/4955198/6498306/93208412-c325-11e4-9e28-0a009fc0788e.png)

Did any one have the same problem?Or any one know how toI solve it?

**Comment by AntiFreez** [comment]
I find typo. Default values are in $scope.selectedPersons, but ng-model="selects.selectedPersons".So, default values should be in $scope.selects.selectedPersons

**Comment by malexandre** [comment]
I'm closing this ticket, as there is a typo in the code of the first post causing the problem. And all is good in the demo site.
