### ISSUE TITLE
Date picker dialog service

### ISSUE THREAD

**Issue by demetriusnunes** [lumapps/lumX#187]
The date picker dialog should be available as a service that can be invoked on response to click events that are not from the lx-date-picker directive itself.

**Comment by ThomasCrvsr** [comment]
Could you develop the use case you have in mind for this ?

**Comment by malexandre** [comment]
I'm not sure about that. I can't see a use case for that.

**Comment by demetriusnunes** [comment]
Well, it's nice to decouple the dialog component from the input component.
Sometimes, I just want to launch the dialog from a small button and not have the date input visible all the time as the launcher for it (for instance, from a big list of items).
