### ISSUE TITLE
Date Picker minimum and maximum date Restriction

### ISSUE THREAD

**Issue by ganeshkumarj** [lumapps/lumX#189]
Hi,

    I just need to know that in datepicker is it possible to give minimum date and maximum date restriction?
Normally how we do in HTML 5

**Comment by AlvonnLimjoco** [comment]
lumX date-picker directive does not support date restrictions.

+1.  Having configurable minimum and maximum date/time restrictions is very useful indeed.

**Comment by bastienJS** [comment]
Its more than usefull. My user must be restricted with min/max date to stay within a certain planning year. I dont want to handle this with watchers. This logic should be encapsulated in the widget itself.

**Comment by malexandre** [comment]
This is in the plans, we'll get back once it's done.

**Comment by matmkian** [comment]
Date picker now has this feature.
