### ISSUE TITLE
Angular2 soon?

### ISSUE THREAD

**Issue by renege** [lumapps/lumX#193]

**Comment by malexandre** [comment]
We're looking at Angular2 from afar. There is 1.4 before hand. And we're also looking to ECMAScript 6. Thanks anyway!

**Comment by tom94zoe** [comment]
+1

**Comment by happyvig** [comment]
+1

**Comment by IAMtheIAM** [comment]
I was about to use Lumx, but then I realized it's written in angular1, and my project is angular2. Please update directives for angular2, thanks!

**Comment by akshath4u** [comment]
waiting for angular2 release
