### ISSUE TITLE
select search help text message

### ISSUE THREAD

**Issue by narayangowda** [lumapps/lumX#194]
can we customize this message 'Type minimum {{ minLength }} to search' to custom message. as this message is not valid for most scenarios. Eg: 'Type minimum 2 to search'  this doesn't sounds correct.

**Comment by yconoclast** [comment]
I think you can put whatever you want, just like this:

## Code
```
<li class="lx-select__help" ng-if="isHelperVisible()">
    <span ng-if="filterNeeded()">Testing message: {{ minLength }} chars</span>
    <span ng-if="hasNoResults() && !filterNeeded()">No results!</span>
</li>
```

## Result

![Image of Yaktocat](https://www.evernote.com/shard/s14/sh/a6754826-5349-4ffb-b923-35ead26017c9/005efa29f4f5dfdc788d3396f09d72cc/res/bfc43229-8416-4938-8701-adbd2a7de866/skitch.png)

**Comment by malexandre** [comment]
It's not customizable for now, but it must be. I have some work to do on the selects component, and this is one of the tasks.

**Comment by matmkian** [comment]
In the last version, we've reworked and fixed a lot of things. If this issue is still happening, please re-open the issue. Thank you!
