### ISSUE TITLE
Content of ng-repeat in scrollbar is not shown completely

### ISSUE THREAD

**Issue by yuyinitos** [lumapps/lumX#197]
When ng-repeat is within a scrollbar directive and the ng-repeat fills it with content (images in my case) the scrollbar doesn't scroll down to the end of the content.

**Comment by malexandre** [comment]
Thanks for reporting. I'll check that.

**Comment by matmkian** [comment]
Scrollbar will soon be deprecated as we choose to keep the browser scrollbar.
