### ISSUE TITLE
Setting invalid on the input field when the lx-text-field is has error

### ISSUE THREAD

**Issue by sagar-ganatra** [lumapps/lumX#198]
when the validation fails or when there's an error the generated content has the class 'text-field--is-valid' or 'text-field--has-error'. Notice that at this point the input field inside the lx-text-field has the class 'ng-valid'. This affects form validation:

 <form name="loginForm">

        <div flex-item>
            <lx-text-field
                           label="Username"
                           valid="user.userName.length > 0"
                           error="user.userName.length == 0 && !loginForm.userName.$pristine">
                <input type="text"
                       name="userName"
                       ng-model="user.userName"/>
            </lx-text-field>
        </div>
       <div flex-item>
            <button class="mt++ btn btn--l btn--blue btn--raised btn-submit" 
                    lx-ripple
                    ng-click="login()"
                    ng-disabled="loginForm.$invalid">
                Submit
            </button>
        </div>

</form>

Here loginForm.$invalid is never true.

**Comment by malexandre** [comment]
Valid and error are just here for the style of the input. If you want HTML5 validation, you'll need to use HTML5 validators. We're working on the documentation for that.
