### ISSUE TITLE
Wrong bourbon scss filepath

### ISSUE THREAD

**Issue by Serginho** [lumapps/lumX#199]
This issue ocurrs only if you use master.
In _lumx.scss [line 5](https://github.com/lumapps/lumX/blob/master/core/scss/_lumx.scss#L5 "line 5") bourbon scss is imported with a wrong path. Given that lumx scss is /bower_components/core/sccs/_lumx.scss, and bourbon is installed in bower_components/bourbon/... if we want to come back to bower_components root, we'll have to add another '../', so the correct path is 
> @import "../../../bourbon/app/assets/stylesheets/bourbon"

**Comment by Serginho** [comment]
I've been thinking about this problem and consider that bourbon shouldn't be imported into your css. If your CSS depends on Bourbon and you specified it in your bower.json as a dependency. My Grunt install and import that dependency in my main.scss, therefore your repository can't be used as a bower dependency.

**Comment by malexandre** [comment]
The file in the dist folder has the right path : https://github.com/lumapps/lumX/blob/v0.3.23/dist/scss/_lumx.scss

To just use lumx, it's best to get the last release instead of using the master. And if you still want to use the master, making a `gulp dist` will build the dist folder.

**Comment by Serginho** [comment]
Yes, dist version works fine. Thanks for your support
