### ISSUE TITLE
Directive "Select" Error when using just an array in the choices

### ISSUE THREAD

**Issue by g4mb4** [lumapps/lumX#201]
I'm having a problem when using select directive and giving just an array for the choices

![image](https://cloud.githubusercontent.com/assets/8481068/6610489/960f2da4-c825-11e4-8206-8c48763aae4c.png)

![image](https://cloud.githubusercontent.com/assets/8481068/6610494/a8e0e1f2-c825-11e4-83da-ba9460ea66f8.png)

![image](https://cloud.githubusercontent.com/assets/8481068/6610501/cd339afe-c825-11e4-9e4c-179a383cbe25.png)

I changed the choices variable into an array of objects and it works fine but I need it to be a simple array

**Comment by leppie** [comment]
I got this too, seems to be maybe AngularJS's fault for thinking a string is 'array like'.

My 'fix':

Search for `isArrayLike(collection)` in Angular.js. Change line to:

     if (isArrayLike(collection) && !(typeof(collection) === 'string')) {

**Comment by deel77** [comment]
I am having the same problem. Don't think that changing angular.js code is proper workaround.

**Comment by malexandre** [comment]
Maybe making a PR to angular is! :D
I've got the same error in a recent project, I'll try to see what I can do.

**Comment by matmkian** [comment]
In the last version, we've reworked and fixed a lot of things. If this issue is still happening, please re-open the issue. Thank you!
