### ISSUE TITLE
Custom Build

### ISSUE THREAD

**Issue by dmackerman** [lumapps/lumX#204]
Is there anyway to do a custom build? We really only need the dropdown component as we transition to angular material. Think it's doable?

**Comment by GustavoCostaW** [comment]
I have the same problem

**Comment by marcosloic** [comment]
Have you tried to include the dropdown directive (bower_components/lumx/modules/dropdown) and the related scss file in your own project?

**Comment by GustavoCostaW** [comment]
yep, it's not works.

**Comment by pdf13** [comment]
I have this problem too. I only need dropdown component.

**Comment by dongmingliy** [comment]
+1

**Comment by malexandre** [comment]
We'll try to make each components self living, but for now it's not the case. Maybe you can only load the components you need (see https://github.com/lumapps/lumX/blob/master/core/js/lumx.js) but being selective in the javascript might not be so direct. And for the CSS, you'll have to load all of lumx for now.
