### ISSUE TITLE
PR: bower dist does not exists

### ISSUE THREAD

**Issue by amohamedali** [lumapps/lumX#209]
HI,

We tried to follow the GuideLine to create a PR.
After commiting, we tried the "bower dist" command as described in the guideline.
The problem is, this command does not work and does not seem to exists :/
The permitted commands of bower are :+1: 

    cache                   Manage bower cache
    help                    Display help information about Bower
    home                    Opens a package homepage into your favorite browser
    info                    Info of a particular package
    init                    Interactively create a bower.json file
    install                 Install a package locally
    link                    Symlink a package folder
    list                    List local packages - and possible updates
    lookup                  Look up a package URL by name
    prune                   Removes local extraneous packages
    register                Register a package
    search                  Search for a package by name
    update                  Update a local package
    uninstall               Remove a local package
    version                 Bump a package version

Could you provide some help please?

**Comment by malexandre** [comment]
It's `gulp dist`, not bower. But anyway, I should remove this line as the dist folder must not be committed. It's better if you test the dist version before making a PR, but it's not in the repo, only in the releases.

**Comment by amohamedali** [comment]
Oh yeah get it thank you

**Comment by tagazok** [comment]
Ok thanks :)
We needed to test the gulp dist before the PR as we are also modifying (adding something to) the demo pages.

**Comment by tagazok** [comment]
Well, it's a hard path to the PR ! ^^
We have an "access denied" when we try to push :/

**Comment by malexandre** [comment]
You try to push directly to this repo ? The way a PR works is this one:
- Fork the repo on your account
- Do your work
- Push on your own Lumx repo
- On your branch (that might be the master of your Lumx repo if you want), click on "Pull request" (here : http://i.imgur.com/PFAg09M.png)
- Keep in mind that you have to make the PR regarding our master ;)

If you still have problem, maybe the Github documentation will be more helpful ([here](https://help.github.com/articles/fork-a-repo/) to fork, [here](https://help.github.com/articles/creating-a-pull-request/) to PR).

**Comment by amohamedali** [comment]
Thank you for your help my pull request is ready for the review now
