### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by Riverside14** [lumapps/lumX#212]
Hi,
 I've installed lumX with bower and it works perfectly. But when i want to use one of the directives it's doesn't work. I mean directives by code like :  "lx-dropdown" or "lx-text-field" That's the first time that i use this kind of framework, so i guess i missed one step during the installation, maybe that my server doesn't well configured. I don't know.
I use EasyPhP for my projects.
If anyone can help me, i suppose that's a stupid thing that i didn't do.

**Comment by malexandre** [comment]
It's pure javascript, so your server sould not change anything. How do you include Lumx in your HTML? There is no error on your console?

**Comment by Riverside14** [comment]
That's what i thought.
No error on console.
I include LumX exactly like this is recommended on "Get started".
I add nothing else, just lumX.
If i add a Button, it's work fine. But if i add a dropdown or something else, that's doesn't work
(Sorry for my english, i'm not fluent)

**Comment by malexandre** [comment]
Did you include Angular too? And did you declare your Angular app with Lumx dependency? If you could just past some of your main html file (the ng-app part, the JS includes), and the declaration for your Angular app, it would be easier for me to help you.

**Comment by Riverside14** [comment]
I include angular like that, but i think that's what i've missed : include Angular App with LumX dependency.
 You mean : ``` angular.module('myModule', ['lumx']); ```, right?
I'm not sure in which file put it 
```
<html lang="fr">
	<head>
		<meta charset="utf-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<meta name="description" content="" />
		<meta name="keywords" content="" />
		<title>Index</title>
		<link rel="stylesheet" href="lumx/dist/lumx.css">
		<link rel="stylesheet" href="mdi/css/materialdesignicons.css">
		<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:300,400,500,700">
	</head>
	<body>
		<p>Index</p>
	
		<script src="bower_components/jquery/dist/jquery.js"></script>
		<script src="bower_components/velocity/velocity.js"></script>
		<script src="bower_components/moment/min/moment-with-locales.js"></script>
		<script src="bower_components/angular/angular.js"></script>
		<script src="bower_components/lumx/dist/lumx.js"></script>
	</body>
</html>
```

**Comment by dhawken** [comment]
You would need a separate js file defining your app, or a script tag in the above file if you're just doing lumx evaluation.

**Comment by Riverside14** [comment]
you mean something like bellow in my ``` <head></head>``` ?
```
<script>
    angular.module('myModule', ['lumx']);
</script>
```

**Comment by malexandre** [comment]
Yes. Lumx is depending on Angular, and Angular needs you to create an Angular app. For example, this is from the official tutorial:

```html
<html ng-app="phonecatApp">
<head>
  ...
  <script src="bower_components/angular/angular.js"></script>
  <script src="js/controllers.js"></script>
</head>
<body ng-controller="PhoneListCtrl">

  <ul>
    <li ng-repeat="phone in phones">
      <span>{{phone.name}}</span>
      <p>{{phone.snippet}}</p>
    </li>
  </ul>

</body>
</html>
```

If I reuse your little HTMLsample, you'll need to do that:

```html
<html lang="fr" ng-app="myApp">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="" />
        <meta name="keywords" content="" />
        <title>Index</title>
        <link rel="stylesheet" href="lumx/dist/lumx.css">
        <link rel="stylesheet" href="mdi/css/materialdesignicons.css">
        <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:300,400,500,700">
    </head>
    <body>
        <p>Index</p>

        <script src="bower_components/jquery/dist/jquery.js"></script>
        <script src="bower_components/velocity/velocity.js"></script>
        <script src="bower_components/moment/min/moment-with-locales.js"></script>
        <script src="bower_components/angular/angular.js"></script>
        <script src="bower_components/lumx/dist/lumx.js"></script>
        <script>
            angular.module('myApp', ['lumx']);
        </script>
    </body>
</html>
```
(The `ng-app` on the html tag is important)

**Comment by Riverside14** [comment]
Yeah that's it! 
I knew it was a stupid thing, all is ok, i can work on it now.
Thank you so much !

**Comment by malexandre** [comment]
No problem! I'm closing the issue.
