### ISSUE TITLE
plan on adding keyboard actions on selects component

### ISSUE THREAD

**Issue by dohomi** [lumapps/lumX#215]
Hello,

I just find the selects component and it is really well done! Is there a plan on adding keyboard actions like keyUp/keyDown and enter for selection? Would be great, I guess many users are typing and want to navigate after their search directly to the element via keyboard.

Cheers,
Dominic

**Comment by cliren** [comment]
Keyboard navigation is required badly! +1

**Comment by cliren** [comment]
Authors, can you suggest an idea on how to add keyboard navigation for select component? We started using this feature and keyboard navigation has become very important. Appreciate your feedback.

**Comment by malexandre** [comment]
Hi!

We were a little occupied on our others projects lately, but the accessibility is still a big point for us. I think we'll work on the documentation first, but the a11y is the next big project. We'll get back to you as soon as we'll advance in this way.

**Comment by matmkian** [comment]
In the last version, we've reworked and fixed a lot of things. If this issue is still happening, please re-open the issue. Thank you!
