### ISSUE TITLE
Have a roadmap

### ISSUE THREAD

**Issue by theofidry** [lumapps/lumX#216]
I'm not yet an active user of lumX but although it's a project I'm keeping an eye on since I find it very interesting. Still, I find very unclear the roadmap and the issues handling is a total mess. Maybe using a tool like [waffle.io](https://waffle.io/) would help? A great example provided by StrongLoop: [waffle.io/strongloop/loopback/](https://waffle.io/strongloop/loopback/).

**Comment by malexandre** [comment]
Hi!

We were just overflowed with work recently, so yeah, the issues have been quite a mess. We're currently searching through the different solutions to be more clear on the work in progress, and maybe have a chat or something like this. Thanks for waffle.io, we'll check that.
