### ISSUE TITLE
Height refresh problem with lx-dropdown

### ISSUE THREAD

**Issue by corneadoug** [lumapps/lumX#217]
### Problem
lx-dropdown-menu makes heigh change for a few milliseconds, and can cause a scrollbar or container to flicker

### Environment
* lumx v.0.3.17
* Mac OsX 10.10.2
* Chrome 41.0.2272.89 (64-bit)

### How I did it
I realized it while having my lx-dropdown in a height: 100% container with overflow: auto, you would see a giant flicker on the whole container when lx-dropdown-menu is showing.

I then tried without the 100% height and the overflow: auto, but if the content is longer than your browser height, you will see that flicker on the web browser scrollbar.

### Repoducing
I would have loved to have a working jsfiddle, but I couldn't find any cdn version of lumx, in the mean time, I think this html should show the problem: http://jsfiddle.net/hjbesxjk/

### Possible problem
I think that the problem might come from the fact that the lx-dropdown-menu is moved from inside the lx-dropdown container to the body when shown

**Comment by malexandre** [comment]
Hi! You can use https://rawgit.com/ to simulate CDN for GitHub repo.

**Comment by corneadoug** [comment]
I tried to update my jsfiddle, but still couldn't make it work, so I find a different way:

http://ui.lumapps.com/directives/dropdowns

You will notice sometimes the scrollbar on the right to flicker when you click on the drop down button
(It's not all the times, and happens more often when we click on the white part of the button than the text)

It is not annoying in that case, but when it comes to limited height, it will cause a scrollbar to make a nice left and right jump while resizing containers.

If we add a bit of css to the site, it will become more obvious when that happens:

```
body, html {
 height: 100%;
}

.main {
  height: 80%;
  overflow: auto;
}
```

I get it maybe 1 out of 8 times on your website examples, but 9 out of 10 times on my app

**Comment by malexandre** [comment]
I'll recheck to see if there is still the problem as I've not been available at all lately. If it's still occurring, I'll check your PR.

**Comment by corneadoug** [comment]
Thanks, that would be nice.
I found plenty of other annoying behaviors with dropdowns and duck taped it locally, I will try latest version and create other issues/PR if they still exist.

**Comment by peterpisljar** [comment]
Hi,

i also have this issue .... and similar issue with some other components as well.

for example in your documentation the following components:
dropdown, select, tab, dialog, textfields, ....
and also buttons etc

they all cause the header to move a little (1 pixel lower then back up)

on my website, when the components are inside another thing sometimes the scrollbars appear for a short time.

**Comment by matmkian** [comment]
In the last version, we've reworked and fixed a lot of things. If this issue is still happening, please re-open the issue. Thank you!
