### ISSUE TITLE
Moment.js filter

### ISSUE THREAD

**Issue by theofidry** [lumapps/lumX#218]
It would be great to add moment.js as a filter. If it already is having an example in the doc would be appreciated!

**Comment by ThomasCrvsr** [comment]
Could do you write a use case for it ? I assume you mean make a filter using moment().format function ?

**Comment by theofidry** [comment]
Yes: to be able to format a date the way we want following [moments.js displaying format](http://momentjs.com/docs/#/displaying/).

**Comment by ThomasCrvsr** [comment]
Okay I see.
@matmkian @malexandre Do you think it could be relevant to have this ? And where could I put it in the actual architecture ? (Writing the filter won't be that hard I think)

**Comment by malexandre** [comment]
I think it would be useful. Not sure though if it as a place in lumx, but since we need Moment.js, why not. I'll see that later.

**Comment by matmkian** [comment]
Some libraries are already available. We won't provide this type of filter.
