### ISSUE TITLE
Searchfilter in data table

### ISSUE THREAD

**Issue by theofidry** [lumapps/lumX#219]
It would be great to have search filters available in tables. Kind of like http://www.datatables.net/examples/api/multi_filter.html !

**Comment by alihalabyah** [comment]
+1

**Comment by malexandre** [comment]
Hi!

I don't think that we will make a component for this, you can simply use the search filter and the data table together. It's meant to be combined.

**Comment by theofidry** [comment]
Yeah nevermind I found the Angular module for that (http://l-lin.github.io/angular-datatables/) :) and you're right it should be included in the framework, it's better to keep it in a separate module.
