### ISSUE TITLE
Color palette discrepancies?

### ISSUE THREAD

**Issue by doublemarked** [lumapps/lumX#220]
Hello -

Your color palette (core/scss/settings/_colors.scss) seems to differ somewhat from the Google spec (http://www.google.com.ua/design/spec/style/color.html#color-color-palette). Specifically, your 'light-blue' color palette seems to be Google's 'cyan' palette. The light-blue set is missing from LumX. 

I have not checked for other discrepancies.

**Comment by yconoclast** [comment]
I've created a PR to solve this

https://github.com/lumapps/lumX/pull/228

**Comment by malexandre** [comment]
I'll check the PR later this day. Thanks!

**Comment by matmkian** [comment]
Fixed!
