### ISSUE TITLE
Confirmation box template

### ISSUE THREAD

**Issue by alihalabyah** [lumapps/lumX#227]
Is there a way to change the template of the confirmation box? for example i want to add an extra button beside the `Ok`, `Cancel` ones.

**Comment by ThomasCrvsr** [comment]
As you can see here : https://github.com/lumapps/lumX/blob/master/modules/notification/js/notification_service.js#L171 the template is build internally and only take in account "ok" and "cancel" buttons so what you ask is not possible right now.
What kind of button do you want to add ? I don't know if it's relevant to add more choices in a confirm box.

**Comment by alihalabyah** [comment]
@ThomasCrvsr I just wanted to add an extra `More details` button connected with a custom whatever action but it's find i solved it in another way, thank you!
