### ISSUE TITLE
Error: EMFILE, too many open files 'modules/date-picker/views'

### ISSUE THREAD

**Issue by amrishodiq** [lumapps/lumX#230]
Hi guys,
I just clone this repo using git clone .... using My Mac. I'm pretty sure these softwares is in my laptop: 
Ruby: 2.0.0p247
Bower: 1.3.12
Python 2.7.5

I run npm install & bower install. Everything goes fine.
But when I run gulp serve, I have this error message:

Error: EMFILE, too many open files 'modules/date-picker/views'

And so on, it never continue.
I'm sorry, I'm new to this and I just wanna see how limx works.
I really don't know how to start, because I'm halted when just getting started.

Do I missed something? Maybe I need to install any other software?

**Comment by ThomasCrvsr** [comment]
Check these links : 
http://stackoverflow.com/questions/19981065/nodejs-error-emfile-too-many-open-files-on-mac-os
https://github.com/gruntjs/grunt-contrib-copy/issues/21#issuecomment-10840100

**Comment by malexandre** [comment]
The easy way is to not launch the watchers from gulp. I know that using atom and gulp at the same time I had to increment the limit of file open at the same time exactly like in the links from Thomas. But if you want, just launch gulp without watchers (`gulp build`) and then just the server (via `http-server` for example, a NPM package).
