### ISSUE TITLE
How do I add in my edges elements using classes

### ISSUE THREAD

**Issue by leonardovillela** [lumapps/lumX#231]
Hello Guys, Recently I started using the lumx in my project and am having some difficulties with the documentation , someone could help me ?

Note : The grid system documentation is very sparse

**Comment by ThomasCrvsr** [comment]
LumX uses flex for alignement. Maybe you can start here : http://ui.lumapps.com/css/flexbox

**Comment by malexandre** [comment]
I'm not sure I'm understanding your problem. The documentation needs rewriting, we think it too. But for your situation, I'll need more context to help you. What do you try to do exactly?

**Comment by matmkian** [comment]
We're working on this enhancement. Soon a new release of LumX with real documentation and major enhancements. Keep an eye on https://twitter.com/lumapps.
