### ISSUE TITLE
ng-model don't work in selects 

### ISSUE THREAD

**Issue by svzosorio** [lumapps/lumX#233]
![Screenshot](https://cloud.githubusercontent.com/assets/5873627/6896130/a417f3f4-d6ad-11e4-8e94-81877ba0d9a7.png)

**Comment by ThomasCrvsr** [comment]
Could you put the relevant sample of code you wrote for the screenshot you posted ?

**Comment by malexandre** [comment]
Same as Thomas. All my selects work fine with the ng-model.

**Comment by svzosorio** [comment]
I fix this error in my code, sorry and thanks.
