### ISSUE TITLE
input error: the error is writen over the label 

### ISSUE THREAD

**Issue by svzosorio** [lumapps/lumX#234]
![captura de pantalla 2015-03-30 a las 8 13 54 a m](https://cloud.githubusercontent.com/assets/5873627/6896879/4087044e-d6b5-11e4-8465-3f03df641f57.png)

```
<lx-text-field label="Estrato" error="addCustomerForm.stratum.$invalid">
                    <input type="number" name="stratum"
                            ng-model="mvm.customer.location.stratum" min="1" max="6"
                            required>
</lx-text-field>
```

**Comment by malexandre** [comment]
Hi!
I thought we had fix that. The reason is that you use HTML 5 validation, and in that case angular sets the ng-model to undefined when the value doesn't fit the validation (number in this case). It's fixed for an email but not for a number it seems. I'll look into it.

**Comment by matmkian** [comment]
In the last version, we've reworked and fixed a lot of things. If this issue is still happening, please re-open the issue. Thank you!
