### ISSUE TITLE
Changing tabs re-creates directives without raising $destroy

### ISSUE THREAD

**Issue by sondreb** [lumapps/lumX#235]
I have a lx-tabs control in a page where I have a custom directive within each of the tabs. I have verified that the controller and the link function are both called whenever I switch tabs. This means it re-creates the content somehow, yet without raising $destroy, which is a concern of mine.

When I navigate away from the current page (and controller), then $destroy is raised on the child directive and my directive is able to release resources. Yet if I change back and forth between tabs, I have a memory leak as each time a new directive instance is created, which loads some resources I need to release.

Is there some event or trigger I can implement in the directive or the tabs? Is there a way I can avoid re-creating the directive within the tabs when navigating? That would actually be the best behavior, as the user wouldn't have to load a lot of resources if they simply want to switch quickly between two tabs.

**Comment by malexandre** [comment]
Hi! We're investigating this, for now we're not sure why the scope is not destroyed. Thanks for reporting!

And from the top of my head I don't have a workaround, except something really ugly with a service remembering the scope, and on tab change destroying the previous scope.

**Comment by malexandre** [comment]
We fixed it by using ng-ifs, making sure the controller inside the tabs is destroyed. It should be better now.
