### ISSUE TITLE
How to send data to dialog?

### ISSUE THREAD

**Issue by admorphit** [lumapps/lumX#236]
Hi, it's not clear how to send/bind data to a dialog- assuming scope is shared between caller and dialog, but this doesn't work?

Can someone give an example on how to bind a variable to a field in a dialog?

**Comment by jmls** [comment]
it's just the same as a normal form ..

(I use the controllerAs syntax, my controller is always called "controller") 
```html
<lx-dialog class="dialog dialog--l" id="instanceLaunched" onclose="controller.closingDialog()">
<div class="dialog__header">
        <div class="toolbar bgc-light-blue-500 pl++">
            <span class="toolbar__label tc-white fs-title">
                {{controller.data.title}}
            </span>
        </div>
    </div>
...
</lx-dialog>
```

```javascript
//controller
function() {
    angular.module('NodeGloo')
        .controller('NgApplicationArrayController', NgApplicationArrayController)
    
    NgApplicationArrayController.$inject = [LxDialogService']

    function NgApplicationArrayController(LxDialogService ) {
      var controller = this;
     [snip]    
     controller.someButtonClicked = function() {
       LxDialogService.open('instanceLaunched');
    }
   [snip]
```

**Comment by admorphit** [comment]
Thanks, would be good to have this in the docs- ended up realising the dialog's scope is shared by the calling controller, in my case another directive's controller. A line in the examples page would save time.

**Comment by malexandre** [comment]
It's not really a LumX documentation, more of an Angular one. I can't see how it would have been in the documentation, but during our rework we'll try to think of a way.
