### ISSUE TITLE
tooltip z-index

### ISSUE THREAD

**Issue by teplov** [lumapps/lumX#238]
Hello!
When I add tooltips to the elements in the dialog, they are not visible. z-index values are the same. Increase the value for the tooltip. 

// Tooltip base styles
.tooltip {
	position: absolute;
	z-index: 9991; <<<<<<<<<<<<<<<<<<<<<
	border-radius: $base-round;
	opacity: 0;
	overflow: hidden;
	pointer-events: none;
}

**Comment by malexandre** [comment]
Hi! Thanks for reporting. We'll try to rework the z-index management to avoid those errors, but for now I'll just increase the z-index of the tooltips.

**Comment by matmkian** [comment]
LumX now has a depth management service.
