### ISSUE TITLE
How to implement a sidenav?

### ISSUE THREAD

**Issue by digitalcraftsman** [lumapps/lumX#239]
I would like to use the sidenav like the one on the project page. The documentation does not give any further information or examples about it.

**Comment by alannsiqueira** [comment]
I would like to use the sidenav like the one on the project page. The documentation does not give any further information or examples about it. [2]

**Comment by ThomasCrvsr** [comment]
This is a duplicate of https://github.com/lumapps/lumX/issues/38, as I did a sidenav on my current project I'll try to post an example today.

**Comment by ThomasCrvsr** [comment]
I gave it a go here : https://github.com/ThomasCrvsr/lumx-sidebar-example (though it's a quick implementation and it could be improved)

**Comment by digitalcraftsman** [comment]
Thanks for providing this example.
