### ISSUE TITLE
Adding helper classes for positioning items

### ISSUE THREAD

**Issue by digitalcraftsman** [lumapps/lumX#240]
It would be nice to have some helper classes in CSS to place elements like headlines, text or buttons on some stardard positions like left, right, middle, top and bottom.

**Comment by jsam** [comment]
+1

**Comment by malexandre** [comment]
Hi! There is already some helpers.
`clearfix`, `float-right`, `float-left`, `float-none`, or flexbox could help to position the element or the vertical alignment.
`text-left`, `text-center`, `text-right` are there to manage the alignment of text & inline-block elements.

**Comment by digitalcraftsman** [comment]
The helpers should work (combined).
