### ISSUE TITLE
lx-scrollbar breaks with ng-bind-* range of functions

### ISSUE THREAD

**Issue by charandas** [lumapps/lumX#245]
It seems `ng-bind-*` variety of functions seem to change the scroll height post html render.

Could this be the reason why `{{}}` databinding works, but `ng-bind-html` breaks?

Here is my [plunkr](http://plnkr.co/edit/4AHn865n2WSwuVVFTkzt?p=preview) to demonstrate the usecase with v0.3.25. i am basically trying to use a `prettify` filter to convert the output of angular `json` filter to HTML, but I lose scroll-ability.

Please take a look in your own time, and keep up the good work :+1:

**Comment by malexandre** [comment]
Thanks for reporting. The scrollbar needs a lots of rework but we have other priorities right now. We'll tell you as soon as we start working on it, but for now I think it's best to use classic scrollbar.

**Comment by matmkian** [comment]
Scrollbar will soon be deprecated as we choose to use the browser scrollbar.
