### ISSUE TITLE
floating label and icon?

### ISSUE THREAD

**Issue by cskiwi** [lumapps/lumX#246]
HI,

if you use:
````html
<lx-text-field label="First and last name" fixed-label="true" icon="account">
    <input type="text" ng-model="textFields.fixedFirstName">
</lx-text-field>
````
then you get with the icon nicly in front of it
![](http://i.imgur.com/SHbDPon.png)
and when doing:
````html
<lx-text-field label="Phone number" >
    <input type="text" ng-model="textFields.fixedLastName1">
</lx-text-field>
````
you get the floating label
![](http://i.imgur.com/ri3atKQ.png)

now what would one have to do to get both? so floating label and icon.
Letting the `icon="xx"` doesn't work :/
and setting `floating-label="false"` doesn't work either

**Comment by malexandre** [comment]
It might not be possible for the moment. I'll see with @matmkian, but I think it's not really "material design compliant" to have the label going up while the icon stay left. And moving the icon too will be disturbing. I'll get back to you.

**Comment by matmkian** [comment]
As this is not "material design compliant" we won't provide this feature.
