### ISSUE TITLE
Date picker: everthing disappear clicking on year

### ISSUE THREAD

**Issue by luclanet** [lumapps/lumX#247]
In the demo clicking on the year everything disappear.

http://ui.lumapps.com/directives/date-picker

![untitled-1](https://cloud.githubusercontent.com/assets/3264432/7274296/e6461412-e8fb-11e4-8853-42a28aedbfff.jpg)

**Comment by malexandre** [comment]
Thanks for reporting, and thanks for the PR! I'll watch all the PRs later, I'll test it and comment on it if needed.

**Comment by matmkian** [comment]
Fixed!
