### ISSUE TITLE
Tests?

### ISSUE THREAD

**Issue by dmitriz** [lumapps/lumX#248]
Was just checking your site, impressive work but couldn't find any tests?
Am I looking in the wrong direction? :-)

**Comment by malexandre** [comment]
We're not very good at tests. We're trying to improve, but for now, that's not in place.

**Comment by dmitriz** [comment]
Here is a small package I wrote: https://github.com/dmitriz/min-karma,
a single
```js
npm install min-karma
```
gets you fully functioning test environment with basic example.

It is really that simple!
