### ISSUE TITLE
How do i invoke ng-change event for select tag?

### ISSUE THREAD

**Issue by venkatesh87** [lumapps/lumX#249]
Below is my select tag. I want to trigger a method in my controller while selecting any value from select dropdown. Adding ng-change in the below select directive is not triggering the controller method. Please let me know the way to trigger the method.

<lx-select ng-model="client" placeholder="Choose Client" choices="clientList" floating-label
   <lx-select-selected
                       {{ $selected.clientDescription }}
     </lx-select-selected
      <lx-select-choices
		     {{ $choice.clientDescription }}
      </lx-select-choices
</lx-select

**Comment by mr-ndrw** [comment]
Adding __ng-change__ attribute and binding it with a function(remember about providing two parameters while you are binding - newValue and oldValue!) in the lx-select tag won't do you much good. lx-select expects __change__ atrribute, not __ng-change__.

**Comment by venkatesh87** [comment]
Thankyou it worked.
