### ISSUE TITLE
Disable tab

### ISSUE THREAD

**Issue by cliren** [lumapps/lumX#257]
How can we disable a tab?

**Comment by ThomasCrvsr** [comment]
I just looked at the source code quickly and I don't think we can do it for the moment.

**Comment by malexandre** [comment]
It's not in the code no. You can hide a tab, but not disable it for now. We'll see if we make it possible, but not for now.

**Comment by sava-vidakovic** [comment]
Not a great solution but you can do this hack in css:
```css
  pointer-events: none!important;
  cursor: default!important;
````

**Comment by simple-designs** [comment]
Was this ever worked on for disabling tabs?

**Comment by matmkian** [comment]
Tabs can now be disabled. Check the updated documentation :-)
