### ISSUE TITLE
Dropdowns do not unbind $window scroll and resize listeners when destroyed.

### ISSUE THREAD

**Issue by schreinbo** [lumapps/lumX#259]
We use the dropdown menu on a list of cards that are updated every few minutes, so the cards and dropdowns are destroyed and recreated each time the data is refreshed. We noticed that each time the data was refreshed we were getting large jumps in memory usage on our page. Digging into the objects retained in memory we saw that the dropdowns were binding scroll and resize events to the window object but never unbinding them upon destroy. 

So we moved the scroll/resize event function to a separate variable:

     var windowResizeEvent = function (){
            if ($scope.isDropped)
            {
                setDropdownMenuCss();
            }
        };

        angular.element($window).bind('resize, scroll', windowResizeEvent);

Then in the destroy event function unbind the $window event

     $scope.$on('$destroy', function()
        {
            angular.element($window).unbind('resize, scroll', windowResizeEvent);            
            dropdownMenu.remove();
            LxDropdownService.close($scope);
        });

After this change our memory usage stayed stable and the page was more performant. 

Alternately you could only bind the $window events when the dropdown is opened and then unbind after it is closed.

**Comment by malexandre** [comment]
Thanks for all this data! I'll manage it as soon as possible.

**Comment by matmkian** [comment]
In the last version, we've reworked and fixed a lot of things. If this issue is still happening, please re-open the issue. Thank you!
