### ISSUE TITLE
Maybe add this features.

### ISSUE THREAD

**Issue by jcirizar** [lumapps/lumX#26]
On the selects directives like here (http://ui.lumapps.com/directives/selects).
- On the first example when I start filtering by writing for example "am" it should be good that when you press the key "Enter/Return" the field fills-up with the first filtered result (in this case adam@email.com).

- Also after I choose "adam@email.com" by mistake or not. If I open the drop-down again the previous entered text for filtering remains there and there is no "X" for fast clearing the text field. (If your intention is to keep the text when re-opening the select, I would like the "X")

Sorry by my bad english, I hope this helps. Also Good Job.

**Comment by matmkian** [comment]
In the last version, we've reworked and fixed a lot of things. If this issue is still happening, please re-open the issue. Thank you!
