### ISSUE TITLE
Disable a select dropdown?

### ISSUE THREAD

**Issue by cliren** [lumapps/lumX#260]
This is high priority issue for us when editing cascading select controls (say country, state, city). State and city must be disabled before selecting a country, how can we achieve this? I have looked at the examples and source code and I don't think its implemented yet. Can anyone suggest a temporary solution with CSS to disable the select control?

**Comment by malexandre** [comment]
Hi!

It's one thing we need to make fast. For now there is a work-around really ugly, but it works. I use a disabled lx-text-field and a lx-select, and with a ng-if I display the right one. Like I said, really ugly, bit we did not had time to update the select for this.

**Comment by matmkian** [comment]
In the last version, we've reworked and fixed a lot of things. If this issue is still happening, please re-open the issue. Thank you!
