### ISSUE TITLE
Gulpfile.js - Not generating template javascript's properly

### ISSUE THREAD

**Issue by venkatesh87** [lumapps/lumX#261]
gulp tasks tpl:dropdown, tpl:search-filter, tpl:tabs not generating template javascript's properly. Template file dropdown_template.js don;t have any template names in it **a.put(' ',** 

Any one faced this same issue? 

```javascript
angular.module("lumx.dropdown").run(['$templateCache', function(a) { a.put('', '<div class="dropdown" ng-transclude="parent"></div>\n' +
    '');
	a.put('', '<div ng-transclude="1"></div>\n' +
    '');
	a.put('', '<div class="dropdown-menu dropdown-menu--{{ position }}" ng-class="{ \'dropdown__menu--is-dropped\': isDropped }">\n' +
    '    <div class="dropdown-menu__content" ng-transclude="2" ng-if="isDropped"></div>\n' +
    '</div>\n' +
    '');
	 }]);
```

**Comment by ThomasCrvsr** [comment]
I just tried two of the three tasks you mentionned and I don't have this problem... Did you change the gulpfile ? Could you check which version of gulp-templatecache is used in your repo ?

**Comment by venkatesh87** [comment]
No i didn't change anything on gulp file. 

gulp version - 3.8.11
gulp-templatecache - 0.0.3
Node.js - 0.10.35

**Comment by ThomasCrvsr** [comment]
Looks really weird. I run it  with the same config as yours and I don't have this problem... On which OS do you work ? It's awkward because you have the right content in the cached template...

**Comment by venkatesh87** [comment]
Yes it is so wierd. I'm using windows 7 OS. Also i noticed in few places we are renaming the path **/demo** to **' '** and **/js** to **' '**. If i don't change **/demo** to **\\demo**, it is not renaming the directory.

**Comment by ThomasCrvsr** [comment]
Have you tried to use gulp-templatecache besides this project ? I work on Mac, it may come from the platform. Could make a test project and use gulp-templatecache ?
Where did you find the renaming you mentionned ?
