### ISSUE TITLE
Can we consider this library safe to use as I don't see any responses from contributors on some of the important issues?

### ISSUE THREAD

**Issue by cliren** [lumapps/lumX#262]
-   keyboard navigation for controls. 
-   disabling controls (only few controls has this option now)
-   validation support (is this in the roadmap?)

**Comment by luclanet** [comment]
Is there a roadmap?

**Comment by cliren** [comment]
There is one here https://github.com/lumapps/lumX/blob/master/ROADMAP.md

**Comment by cliren** [comment]
Can someone update on the keyboard support for controls? Is it coming soon or  appreciate if you can suggest an alternative framework or solution.

**Comment by malexandre** [comment]
Hi!

We've been really overloaded this last three months, but we're going to try to improve the communication around lumx, and we'll start working on some big tasks we have to do (documentation, a11y for example).

**Comment by matmkian** [comment]
We're working on this enhancement. Soon a new release of LumX with real documentation and major enhancements. Keep an eye on https://twitter.com/lumapps.
