### ISSUE TITLE
Add a Gitter to the repo

### ISSUE THREAD

**Issue by ThomasCrvsr** [lumapps/lumX#263]
Everything is in the title : I thought it would be great if we add a [Gitter](https://gitter.im/) to the repo in order to improve communication between contributors :)

**Comment by malexandre** [comment]
I'll see about that. We need to improve the communication, but I need to see the options ^^.

**Comment by ThomasCrvsr** [comment]
Sure no problem ! Let me know about what you find :)

**Comment by matmkian** [comment]
A Gitter is now available :-)
