### ISSUE TITLE
Text fields in Dialog on touch screen

### ISSUE THREAD

**Issue by tadejongithub** [lumapps/lumX#267]
I have a Dialog with login form where two input fields are placed. When this dialog is opened on a touch screen (mobile devices) and a field gets focus the floating keyboard is opened but then immediately closed. This problem is not present when the form is outside the Dialog directive.

Does anybody have similar problem?

**Comment by tadejongithub** [comment]
I took a look at the source code of the Dialog directive and I found that there is a resize event binding which causes that virtual keyboard is disappearing. In fact this problem only occurs on Android with Chrome browser because iOS doesn't fire onResize event in any browser. I would recommend to remove this portion of code

<pre>
angular.element($window).bind('resize', function()
        {
            if (angular.isDefined(activeDialogId))
            {
                checkDialogHeight(activeDialogId);
            }
        });
</pre>

from "dialoge_directive.js" because everything is already trigged inside this interval:

<pre>
dialogInterval = $interval(function()
            {
                if (scopeMap[dialogId].element.outerHeight() !== dialogHeight)
                {
                    checkDialogHeight(dialogId);
                    dialogHeight = scopeMap[dialogId].element.outerHeight();
                }
            }, 500);
</pre>

**Comment by badoet** [comment]
any news on this? currently chrome in ios is still doing this.

**Comment by MasDevProject** [comment]
Why the issue is set as 'closed'? The problem is still there.

However thanks for Lumx, I love it
