### ISSUE TITLE
angular and LxDialogService service

### ISSUE THREAD

**Issue by jmls** [lumapps/lumX#269]
Sorry to have to raise this here, but I am in desperate need of some help ;)

I have 2 pages & controllers: a grid page and a details page

What I want to do is when the user clicks on an item in the grid,is for the details page to popup using  LxDialogService.

Whilst I have all of the pages and controllers running, I can't make the dialog appear - the screen goes to a blank page and then nothing shows. However, there is nothing in the console to show any errors

I have my dialog form defined as 

```html
<lx-dialog class="dialog dialog--l" id="modelDetailPopup" onclose="controller.closingDialog()">
```

and my controller does this

```Javascript
 LxDialogService.open("modelDetailPopup");
```
but I get nada ...

thanks ..

**Comment by jmls** [comment]
mmm. getting somewherer ... I am now getting this error

*TypeError: Cannot read property 'autoClose' of undefined*

the code in question is
```javascript
 if (angular.isUndefined(scopeMap[dialogId].autoClose) || scopeMap[dialogId].autoClose === 'true')
```

**Comment by malexandre** [comment]
Hi!

Can you please paste your HTML ?

**Comment by jmls** [comment]
thanks! 

```html
<lx-dialog class="dialog dialog--l" auto-close="true" id="modelDetailPopup" onclose="controller.closingDialog()">
    <div class="dialog__header">
        <div class="toolbar bgc-light-blue-500 pl++">
            <span class="toolbar__label tc-white fs-title">
                card title
            </span>
        </div>
    </div>
    <div flex-container="row">
        <div flex-item="2" flex-item-order="1"></div>
        <div flex-item="8" flex-item-order="2">
                    <div flex-container="row">
                        <div flex-item flex-item-order="1">
                            <div flex-container="column">
                               <div flex-item>
                                  <lx-text-field label="Name" disabled="false">
                                    <input type="text" ng-model="controller.data.item" name="name" id="name" 
                                </lx-text-field>
                              </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div flex-item="2" flex-item-order="3"></div>
    </div>
    
    <div class="dialog__actions">
        <button class="btn btn--m btn--black btn--flat" lx-dialog-close lx-ripple>ok</button>
    </div>
</lx-dialog>

**Comment by malexandre** [comment]
Is this view you're pasting already loaded when you click on the button/element that shows the dialog? The `lx-dialog` must be already loaded before it's open.

If you are using two different state (via ui-router or ng-route), you must think about the order of execution. I know that the FAQ from ui-router talk about that: [managing dialg with ui-router states](https://github.com/angular-ui/ui-router/wiki/Frequently-Asked-Questions#how-to-open-a-dialogmodal-at-a-certain-state).

**Comment by jmls** [comment]
the button is in controllerA and templateURLA - the button tells the router to load controllerB and templateURLB.

I expected that the router would have loaded the page first and then ran the controller - but I will check into that. Thanks
