### ISSUE TITLE
Mac/Firefox trackpad scroll not working

### ISSUE THREAD

**Issue by alihalabyah** [lumapps/lumX#271]
I have the latest Mac OS and Firefox browser, the scroll bar is not responding while using the trackpad

**Comment by malexandre** [comment]
Thanks for reporting. The scrollbar needs a lots of rework but we have other priorities right now. We'll tell you as soon as we start working on it, but for now I think it's best to use classic scrollbar.

**Comment by alihalabyah** [comment]
@malexandre Fair enough, thank you for the update!

**Comment by matmkian** [comment]
Scrollbar will soon be deprecated as we choose to use the browser scrollbar.
