### ISSUE TITLE
select field: problem on setting a default value

### ISSUE THREAD

**Issue by luclanet** [lumapps/lumX#272]
This is what I've

$scope.value = 'english';
$scope.options = [{
'k' : 'english',
'label': 'English'
},{
'k' : 'italian',
'label': 'Italiano'
}];

How can I create a select with those data? I've tring using a filter without any problem but it breaks the final value. I can't see a solution without forking the code.

**Comment by malexandre** [comment]
Hi!

It would help to have the HTML you use. But I think the `ng-model` is `value` and the choices are `options`. Do you use `model-to-selection` and `selection-to-model` ? This is the parameters used to manage the ng-model without using the whole object. It's missing some documentation, and I hope we'll find time really soon to work on the site.

But more important in your code, I see you used primitive type directly in the $scope, and that is something to avoid in Angular. Plus, "value" and "options" are already used in javascript, so it's best to avoid using them. It would work better with something like this:

```js
$scope.selectData = {
    model: 'english',
    choices: [{
        'k' : 'english',
        'label': 'English'
    }, {
        'k' : 'italian',
        'label': 'Italiano'
    }]
};
```

**Comment by luclanet** [comment]
It was pseudo-code :) The model it's more complicated than that, it's more similar to your example.

Anyway I've also tried with model-to-selection and selection-to-model but I can't access to the choises from inside those functions.

The select must work with those function in $rootScope to be used everywhere without changes.

**Comment by malexandre** [comment]
Ok. I'd like to see a little more example of your code please. I really don't have any problem for that. I don't use $rootScope.
