### ISSUE TITLE
uiview inside LxDialog

### ISSUE THREAD

**Issue by MrViSiOn** [lumapps/lumX#275]
Hi!

Is it possible to embed uiview inside a lumx dialog?

                    <lx-dialog class="dialog dialog--l mb" id="new-resource2" auto-close="true">
                        <div class="dialog__content bgc-light-blue-500 mb">
                            <div ui-view="new-resource"></div>
                        </div>
                    </lx-dialog>

This example doesn't fire ui-view... any idea?

**Comment by malexandre** [comment]
Hi!

The content of the dialog is transcluded inside the directive. This means that the ui-view won't be managed. But why don't you put all your dialog code inside your ui-view? It works like that, it's exactly how I use it.

**Comment by MrViSiOn** [comment]
Yep, you right... Intention of doing that ways is because that template is
used in other place... but anyway. Good poing

Thank you
