### ISSUE TITLE
Dropdowns links http redirect

### ISSUE THREAD

**Issue by Ener-Getick** [lumapps/lumX#278]
The links in the dropdowns activates a http redirect instead of a route redirect.

I don't know if it's wanted but I don't think so.
The bug is in your own site http://ui.lumapps.com/ for example: with a mobile display you are redirected when you click on a link of the dropdown menu (in the top right corner).

I found this problem on Firefox 37 and Chromium 41. I didn't try other browsers.

**Comment by xlhl77** [comment]
I found this problem too.
the bug is in lx-dropdown-menu directive , we can see click event of element : 
````
456                 element.on('click touchend', function(event) 
457                 { 
458                     event.stopPropagation(); 
459 
 
460                     scope.$apply(function() 
461                     { 
462                         ctrl.toggle(); 
463                     }); 
464                 }); 
````
row 458 :event.stopPropagation() prevent event goto angular, so $locationchangestart can't be fired.

delete this row ,solved! :+1:

**Comment by matmkian** [comment]
In the last version, we've reworked and fixed a lot of things. If this issue is still happening, please re-open the issue. Thank you!
