### ISSUE TITLE
select not working

### ISSUE THREAD

**Issue by jmls** [lumapps/lumX#282]
Maybe it's me .. but I just can't seem to get lx-select to show some items

so, this is the code:

```javascript
<div>
        {{controller.method}}
        {{controller.definitions.method.allowedValues}}
        <lx-select ng-model="controller.method" placeholder="method" choices="controller.definitions.method.allowedValues" floating-label>
            <lx-select-selected>
                {{ $selected.name }}
            </lx-select-selected>

            <lx-select-choices>
                {{ $choice.name }}
            </lx-select-choices>
        </lx-select>
```

and this is the result

![screenshot from 2015-05-30 09 03 47](https://cloud.githubusercontent.com/assets/929523/7896256/d6d5fd40-06aa-11e5-8c18-39291e60187f.png)

the method select does not drop down, and there are no options to see, and you can't enter any information. 

What am I missing ?

**Comment by ablagoev** [comment]
Hello,

Which version of angular are you using? In 1.4+ there is a problem with the select component.

You can try out my fork and see if the patch corrects the problem:

https://github.com/ablagoev/lumX/tree/lx-select-angular-1.4

1. Clone the repo
2. Install the dependencies through npm install && bower install
3. Install gulp if you don't have it (npm install -g gulp)
4. Build a distribution version of the project (gulp dist)
5. The build can be found in the dist/ folder

**Comment by shprink** [comment]
Thanks @ablagoev ! The filter errors are gone but it seems I still have problems with Ng-model. Digging...

**Comment by malexandre** [comment]
Hi!

I see the problem. You set the variable `controller.method` to `GET`, but it's not a choice available. It should be set to `{ name: 'GET' }`, which is a choice available. Or else you can use `selection-to-model` and `model-to-selection` to convert the object into text and the text into the object.

For example, in your controller or service:
```js
$scope.textToObjectMethod = function(data, callback)
{
    callback({ name: data });
};

$scope.objectMethodToText = function(data, callback)
{
    callback(data.name);
};
```

And in your DOM:
```html
<lx-select ng-model="controller.method" placeholder="method" floating-label
           choices="controller.definitions.method.allowedValues"
           model-to-selection="textToObjectMethod(data, callback)"
           selection-to-model="objectMethodToText(data, callback)">
    <lx-select-selected>
        {{ $selected.name }}
    </lx-select-selected>

    <lx-select-choices>
        {{ $choice.name }}
    </lx-select-choices>
</lx-select>
```

**Comment by danielyankowski** [comment]
I had a similar problem, the dropdown didn't show. The reason was Bootstrap's CSS, which I already had in the project :)

**Comment by angeldaniel-adcm** [comment]
how did you fix the problem without removing bootstrap's css?

**Comment by danielyankowski** [comment]
I'm not sure, but as far as I remember, lumx dropdown's visibility is based on the 'opacity' property, while bootstrap's is the 'display', so try to give 'display:block' to .dropdown__menu--is-dropped or something like that.

**Comment by radonyizsolt** [comment]
Is there any solution for this problem?

**Comment by danielyankowski** [comment]
I'm not sure, but as far as I remember, lumx dropdown's visibility is based on the 'opacity' property, while bootstrap's is the 'display', so try to give 'display:block' to .dropdown__menu--is-dropped or something like that.

**Comment by angeldaniel-adcm** [comment]
There is a solution, but you have to edit class in lumx.css or boostratp.css (i recomendo bootstrap), if you do so just remember the name of class that you assigned when you use it.
Example:
change .dropdown__menu--is-dropped TO : dropdownBST__menu--is-dropped
at bootstrap.css

and when using dropdown tag just remember that you named dropdownBST
