### ISSUE TITLE
Button doesn't work with Firefox

### ISSUE THREAD

**Issue by marcosloic** [lumapps/lumX#286]
Hello :-)

I've been testing my app on the latest version of Firefox (38, I think) on OS X (Everything up to date). I've got several buttons on my menu, that are laid this way

```
<button class="btn btn--xl btn--grey-300 btn--icon" lx-ripple lx-tooltip="Aliments" tooltip-position="bottom">
     <a ui-sref="alimentation">
           <i class="mdi mdi-food-apple"></i>
     </a>
</button>
```

It works fine on Chrome and Safari, both desktop and iPad, as I can't trigger a page change, but it won't do anything on Firefox.

**Comment by matmkian** [comment]
A link inside a button?

**Comment by matmkian** [comment]
In the last version, we've reworked and fixed a lot of things. If this issue is still happening, please re-open the issue. Thank you!
