### ISSUE TITLE
search box: is this how it's supposed to look?

### ISSUE THREAD

**Issue by kilianc** [lumapps/lumX#288]
Shouldn't the `( x )` be all the way down right?
![hwuayjux3sfs47gufizay2zgr4vbpvrww0enep6cdxy](https://cloud.githubusercontent.com/assets/385716/8020395/c4421372-0c2b-11e5-98cc-58510b36b334.png)

**Comment by matmkian** [comment]
You should set the filter width with the filter-width attribute. You can specify percent or px values.
