### ISSUE TITLE
Using select boxes, when you scroll the component where the select is located it moves too.

### ISSUE THREAD

**Issue by franciscopuyo** [lumapps/lumX#289]
If I have a scrolleable column for example, and i have a form there with a select box (a provide for lumx one), it moves with the scroll too and doesn't get stuck on its place. I actually thought it was my css but, looking at the dom, the select is out of the column tag.

In addition i've tried adding the onscroll attribute to the column tag binded to this function:

var fixLumxSelects = function(column) {
        var top;
        var height = $(container).scrollTop();

        var newTop;
        $(collumn).parents('body').find('.lx-select__choices').each(function() {
            top = ($(this).css('top'));
            if (top != 'auto') {

                //Cut 'px' string, I sum the values and put it again

                top = top.substr(0,top.length - 3);
                newTop =  parseFloat(height).toFixed(3) - parseFloat(top).toFixed(3);
                newTop = newTop + 'px';
                console.log(newTop);

                //Apply the new top attribute:
                $(this).css('top', newTop);
                $(this).css('top',newTop);
            }
        });
    };

I tried summing and resting but it seems that lumx library is modifying the value too. Do you have a solution for my issue?

Thanks, Francisco

**Comment by malexandre** [comment]
Hi!

The problem comes from the dropdown I think. But I'm not sure à follow. We have modal that stays put while the site scrolls down, and the select/dropdown inside the modal don't move with the scroll. Can you give us a gif, or better, a jsfiddle/some way to reproduce the bug ?

**Comment by franciscopuyo** [comment]
Hi, I tried to reproduce it in jsfiddle but i couldn't find the online lumx library to append it to my code, and it seems someone delete the select demo from lumx site and I've already modify my website

In the example of the page, the select didn't move because it was on the main container of the site.
Try creating a column with a scroll (Set the an specific height to the main container and a higher one to the column). Add some divs to make the select move when you scroll.

Open it to see the options, scroll and you'll find the problem.

The cause is this:
When you open the select field, the options div is created under the body tag with position: absolute and the same distance to the top (css top attribute) of the select input.
That's ok if the select is allocated into the site main container, but if it is into another div with an independent scroll of the body element, when you scroll,  the top position related to the body top is different that the position related to this div (or any element that contained it).
So i think that the solution should be: 
When someone opens the select, the options div must be created inside the select parent tag, not inside the body tag, so the position would be related to it.

I don't know if I was clear, anything you didn't understand tell me. If you have the library as an online resource tell me and I create de jsfiddle.

**Comment by matmkian** [comment]
In the last version, we've reworked and fixed a lot of things. If this issue is still happening, please re-open the issue. Thank you!
