### ISSUE TITLE
Change datepicker language

### ISSUE THREAD

**Issue by eduardmartinez** [lumapps/lumX#290]
Hi. I installed LumX with Bower and then I concat the files with Grunt (grunt-bower-concat) and everything works fine. But when I use the datepicker directive and I want to change the language using the "locale" attribute, it doesn't change. How could I solve it?

**Comment by matmkian** [comment]
In the last version, we've reworked and fixed a lot of things. If this issue is still happening, please re-open the issue. Thank you!
