### ISSUE TITLE
Dropdown content width

### ISSUE THREAD

**Issue by Donovan-Ensicaen** [lumapps/lumX#294]
Hi, 

This is my first issue which is not really one. This is just an UI improvement :).

I think it would be better if the content on the dropdown-menu would be at the same size that the dropdown label. If there are only little words in the dropdown, the result is not really nice : 

![capture d ecran 2015-06-20 a 16 03 41](https://cloud.githubusercontent.com/assets/5382059/8269049/7ba97cb8-1766-11e5-809a-447d60b9814c.png)

What do you think?

**Comment by malexandre** [comment]
Hi!

It's one of the only component with the full documentation done. You can see "width" in the API description at the bottom: http://ui.lumapps.com/directives/dropdowns
If you set width to "full", it will take the whole button.
