### ISSUE TITLE
Checkbox needs id

### ISSUE THREAD

**Issue by Devqon** [lumapps/lumX#297]
I placed a checkbox on my html, but it didn't work. After a few minutes I saw that the only difference with the example was that it had an id. Why is this? Why does it need to have an id to make it work?

```
<div class="checkbox">
    <input type="checkbox" id="remember" name="remember" class="checkbox__input"
               ng-model="login.user.remember" />
    <label for="remember" class="checkbox__label">Remember me</label>
</div>
```

**Comment by matmkian** [comment]
It needs to have an id because the label is the trigger and target the input with the id.

**Comment by matmkian** [comment]
You now have a directive to handle checkboxes.
