### ISSUE TITLE
UI optimization required for year selection

### ISSUE THREAD

**Issue by pranav1877** [lumapps/lumX#307]
When I click on year to change it shows a big list starting from 1915 to 2015, but the way UI is presented I am not able to do the selection of 2000.

![image](https://cloud.githubusercontent.com/assets/7945697/8741067/0521aa3c-2c71-11e5-8a50-ad79dc0b9a39.png)

**Comment by jmijmi** [comment]
+1

**Comment by malexandre** [comment]
Hi!

I've fixed it yesterday. Thanks for the issue.
