### ISSUE TITLE
lx-select is broken if ng-model contains "data" property

### ISSUE THREAD

**Issue by AntiFreez** [lumapps/lumX#311]
Due to prototypal inheritance of scopes this example will be broken: 
```
<lx-select ng-model="data.selected" choices="provider">
   ...
</lx-select>
```
because "data" object already exists in lx-select scope and "selected" will be setted to this "data" object. May be we should use prefixes for lx-select scope properties to protect component scope (lx$data or something else) or shouldn't bind system properties to component scope.

**Comment by malexandre** [comment]
Hi! Thanks for reporting. I'm currently working on it. I didn't thought of that when changing to inherirtance. I already fixed dialog, dropdown, and almost finished tabs. I'll fix select right after.

**Comment by AntiFreez** [comment]
It's very very good! Thank you =) 
I'm new to lumx to make pull requests, but lumx is very interesting for me.

**Comment by malexandre** [comment]
I'm deploying a new release right now. You can see the fixes here:
d80b6a0accf778ce194c3340c67e0eb5e84c0669
623c36b59a1ed6300bd150fcfc87eab5c1ce8593
8ee703145d4b16eff66c3259997a59e8014bcfc0

Thanks again, I'm closing this issue.

**Comment by malexandre** [comment]
Oh and by the way, it was an error in my code, but be sure to avoid using "data" in your scopes. It's a commonly used property in all the frameworks, and you can have some errors because of that. I know that previously I'v had errors with angular, and renaming my "data" to "ctrlData" in my scope fixed everything.

**Comment by AntiFreez** [comment]
Thank you again =) I know, but also think that using prefixes is common pattern which helps end users to forget about property names. In my projects i avoid "data", "info" and their friends =)
