### ISSUE TITLE
ripple.height is not a function

### ISSUE THREAD

**Issue by JuanSomniis** [lumapps/lumX#312]
Hi, I'm use ionic framework and I include lumX, everything works fine, but the wave efect not, when I click the button the following error appears : 'TypeError: ripple.height is not a function'

**Comment by malexandre** [comment]
Hi! Do you have jQuery?

**Comment by JuanSomniis** [comment]
Yes, I do

<script src="lib/jquery/dist/jquery.js"></script>
        <script src="lib/velocity/velocity.js"></script>
        <script src="lib/moment/min/moment-with-locales.js"></script>
        <script src="lib/lumx/dist/lumx.js"></script>

**Comment by malexandre** [comment]
In your code snippet, there is no jQuery. And this error really means that you do not have jQuery.

**Comment by JuanSomniis** [comment]
Sorry I already edited

**Comment by malexandre** [comment]
There is no error in your console? No 404 in your Network data too?

**Comment by JuanSomniis** [comment]
No, all is fine, it does not work

**Comment by malexandre** [comment]
I need more information. This error is very classic, it means that angular uses jqLite instead of jQuery. jqLite does not have the height method, but jQuery does. So I need more information to understand why your jQuery is not loaded.

**Comment by JuanSomniis** [comment]
Well, I'm using ionic framework, this means, the angular was included before everything, just the lumx included before the body closing tag, I don't know if this affect

**Comment by malexandre** [comment]
Maybe Angular sets itself in jqLite mode because it's loaded before jQuery then. But I don't know at all the ionic framework. It's the same problem as here in fact: https://github.com/lumapps/lumX/issues/186

I can't help you for now, and @Argetloum is not here before tomorrow. I'm closing this issue because it's a duplicate, but if @Argetloum has the answer, he'll post it here tomorrow (we're GMT+2).

**Comment by JuanSomniis** [comment]
@matmkian Hey, I've fixed it or I think, I include the Jquery before Ionic, something like that 
    < script src="lib/jquery/dist/jquery.js"></script>
    < script src="lib/ionic/js/ionic.bundle.js"></script>
