### ISSUE TITLE
no /dist directory in repo

### ISSUE THREAD

**Issue by dkebler** [lumapps/lumX#321]
your "main" bower entry in bower.json points to files that do not exist in your repo.

lumx.js can be found at core/js/   is that what you intended?
lumux.css is no where in the repo.

I already have a pull request and can fix this if you confirm lumx.js in core/js is ok and provide a lumx.css in your repo somewhere.

 "main": [
    "dist/lumx.css",
    "dist/lumx.js",

**Comment by matmkian** [comment]
Fixed on last version :-)
