### ISSUE TITLE
Scrollbar Issue

### ISSUE THREAD

**Issue by sebakerckhof** [lumapps/lumX#324]
I wanted to just use the scrollbar directives in my project that uses ui.bootstrap.
I have dropdown menu, which I want to limit in size and at the lumx scrollbar to.
However, the scrollbar either doesn't appear or is incorrectly sized.

See: http://plnkr.co/edit/FBaCx1u7lg2oDNwwo0mW?p=preview (make sure to have the preview pane wider than 1024px)

**Comment by matmkian** [comment]
Scrollbar will soon be deprecated as we choose to use the browser scrollbar.
