### ISSUE TITLE
Flexbox "row" issue

### ISSUE THREAD

**Issue by mirabalj** [lumapps/lumX#327]
¿Why flexbox container style "row" work like column in mobile devices?.
Angular Material resize the flex.
![captura de pantalla de 2015-08-19 16 50 55](https://cloud.githubusercontent.com/assets/48406/9370263/99f21952-4694-11e5-95fb-ca95241e7e22.png)

**Comment by AntiFreez** [comment]
See https://github.com/lumapps/lumX/issues/302
