### ISSUE TITLE
DatePicker model & null value

### ISSUE THREAD

**Issue by Piou2fois** [lumapps/lumX#331]
Hi
For the model I use to have ng-model or data-ng-model but for the datepicker we have to use "model" alone. Is there any way to update this ?
Another point, when the value in the model is null (working with sql database), Invalid date is shown and there is no way to modify the value at all.

**Comment by Piou2fois** [comment]
Another point for the datepicker : if I have a form with many fields, TAB brings me to the following instead for the datepicker, it jumps it.

**Comment by Piou2fois** [comment]
And another problem : after the pick of a date, the model is an empty object with no value in it. value is not transfered to the model

**Comment by matmkian** [comment]
Fixed on last version :-)
