### ISSUE TITLE
STILL not solution for datepicker for FireFox?

### ISSUE THREAD

**Issue by angeldaniel-adcm** [lumapps/lumX#332]
is there any solution for the datepicker issue with firefox??? I don't find any answer in all the post

**Comment by wfpaisa** [comment]
work in label datapicker.. :S

**Comment by JuanSomniis** [comment]
Well I have a some idea, you need remove the disabled and ng-disabled attributes to the input
This is the normal input 
```HTML
<input disabled="disabled" class="ng-pristine ng-untouched ng-valid ng-scope text-field__input" ng-model="selected.model" ng-disabled="true" type="text">
```
The funcitonal input is this
```HTML
<input  class="ng-pristine ng-untouched ng-valid ng-scope text-field__input" ng-model="selected.model"  type="text">
```
But I don't know how remove these, I tried to set a id in input (directive) but this remove when is render

**Comment by angeldaniel-adcm** [comment]
I FOUND the solution for FIREFOX with DATEPICKER. 

First of all you need the NO min version of LUMX.js, Go To line 3919~ and set ng-disabled to true and write readonly in the input tag like this:

`<input type="text" ng-model="selected.model" readonly ng-disabled="false">`

**Comment by JuanSomniis** [comment]
+1
Oh men thanks, it works perfectly

**Comment by Krzysztof-Padol** [comment]
You can also try to fix it by using CSS bypass:

```
.lx-date-input input.text-field__input {
	pointer-events: none;
}
```

**Comment by jmijmi** [comment]
<b>Krzysztof-Padol</b>
Thank's perfect and clear solution :+1:

**Comment by Almar** [comment]
submitted pull request #392

**Comment by matmkian** [comment]
Fixed on last version :-)
