### ISSUE TITLE
Example dialog

### ISSUE THREAD

**Issue by Borjahen** [lumapps/lumX#336]
Sorry for my bad English.

I'm trying to put a dialog with the button and open it but does not work me the example of the official website.

I copied the HTML code of this page: http://ui.lumapps.com/directives/dialogs

And under the code I put the script:

<*script>
$ scope.opendDialog = function (DialogID)
{
     LxDialogService.open (DialogID);
};

$ scope.closingDialog = function ()
{
     LxNotificationService.info ('Dialog closed!');
};
</* script>

I want to know how to do it

Thank you very much to all :)

**Comment by languorous001** [comment]
In angular controller you should add LxDialogService and LxNotificationService in function

example angular.module('').controller(function ($scope, LxDialogService, LxNotificationService) {})

**Comment by Borjahen** [comment]
Thank you very much for the help but I am a novice in LumX. Where do I put this code?

Thanks again
