### ISSUE TITLE
Is there any documentation for lumX?

### ISSUE THREAD

**Issue by crossdsection** [lumapps/lumX#342]
I'm having issue understanding lx-select tag, I went through this( http://ui.lumapps.com/directives/selects ) URL and followed whatever is written. 

I have questions like - 
What $selected expects? What $choice expects?

I initialized the choices argument to the scope element I wanted to use, I set ng-model in the scope as written in the bottom to undefined but still it is not working.

**Comment by Piou2fois** [comment]
http://stackoverflow.com/questions/27651125/lumx-lx-select-not-updating-ng-model
Hope it could help

**Comment by matmkian** [comment]
We've just released LumX v1.0.0rc1. A real documentation is now available :-)
