### ISSUE TITLE
Integrate date-picker with ng-validation

### ISSUE THREAD

**Issue by omrzljak** [lumapps/lumX#344]
When we use NG from validation (https://docs.angularjs.org/guide/forms) datepicker input field is not validated. 

For example is we have a required date filed and user lx-date-picker , ng-validate will not validate it because generated <input name> value in date-picker.html is not set.

My proposal is to extend attributes of lx-date-picker with attributes needed for date validation https://docs.angularjs.org/api/ng/input/input%5Bdate%5D ..

For example : 
- By adding attributes inputname and required, we could uses 
```
<lx-date-picker model="voucher.validTo" label="{{'jogatnamesApp.voucher.entity.validTo' | translate}}"
                                                fixed-label="false" inputname="{{'validTo'}}" required="{{true}}"></lx-date-picker>

```

Needed changes in date-picker_directive.js (add two attributes in scope directive declarataion

```
    .directive('lxDatePicker', function()
    {
        return {
            restrict: 'AE',
            controller: 'lxDatePickerController',
            scope: {
                model: '=',
                label: '@',
                fixedLabel: '&',
                allowClear: '@',
                icon: '@',
                inputname: '@',
                required: '@'
            },
            templateUrl: 'date-picker.html',
```

And in date-picker.html 
```
 <input type="text" ng-model="selected.model" name="{{ inputname }}" required="{{ required }}" ng-disabled="true">
```

This is example adding input.name and input.required attributes. To be complete all attributes could be added.

**Comment by matmkian** [comment]
We've just released LumX v1.0.0rc1. Date picker can now be used as a service or with a transcluded regular input text.
