### ISSUE TITLE
Primary and Accent Colors are not referenced in SASS

### ISSUE THREAD

**Issue by aotearoan** [lumapps/lumX#350]
Hi,

I have overridden the default primary and accent colors with our color palette but these are not used at all in the SASS.

Digging deeper I see that specific colors are referenced, e.g.

```sass
    .text-field__label {
        color: $blue-500;
    }
```

It would make sense to use only the user defined accent and primary colors in your SASS so they're easier to work with.

**Comment by matmkian** [comment]
We've just released LumX v1.0.0rc1. This new version fixes the issue, so I'm closing it.
