### ISSUE TITLE
lx-select multiselect mode dropdown scroll position resets

### ISSUE THREAD

**Issue by priithansen** [lumapps/lumX#351]
When using long list with lx-select in multiple mode with checboxes modifing any selection resets the list scroll position to start making batch selects quite inconvinient. I suspect it's got something to do with  ngrepeat having to redigest all the list but other then that have no idea where to start looking for the fix.

**Comment by matmkian** [comment]
We've just released LumX v1.0.0rc1. This new version fixes the issue, so I'm closing it.
