### ISSUE TITLE
Any LX tag works !

### ISSUE THREAD

**Issue by Tibicenas** [lumapps/lumX#354]
<lx-search-filter
<lx-dropdown>
<lx-dropdown-menu>

That tags don't works, i just installed lumx, created the index.html, add the scripts, and everything perfect.

I try the http://ui.lumapps.com/css/toolbars  copy and paste the code, and find some problem with all "lx" tag :-1: 

Saw all the browsers and same error, and the libraries are loaded, i missed something ?

**Comment by JuanSomniis** [comment]
You added the lumx module ? 


```javascript

angular.module('myModule', ['lumx']);
```
