### ISSUE TITLE
about lx-text-field : why use transclude?

### ISSUE THREAD

**Issue by xlhl77** [lumapps/lumX#355]
my code : 
````
<lx-text-field label="model">
<input type="text" ng-model="prod.model" mm-auto-complete>
</lx-text-field>
````
i found my directive mm-auto-complete execute link function 2 times! so , I change lx-text-field directive,delete transclude.

ok, mm-auto-complete execute link function 1 time.

why use transclude? what usage is it ?

**Comment by matmkian** [comment]
We use transclude to keep all Angular ng-* expressions available on default text input.
