### ISSUE TITLE
Changing color of templates

### ISSUE THREAD

**Issue by holtjonathan** [lumapps/lumX#360]
Is there a way to customize the color schemes of the various templates?  Like radio buttons and such?  For instance, I don't prefer the default colors for most of the templates and I want to change them so they better match my website.  I have tried adding the various attributes (like the ones that work with buttons) but it doesn't seem to change anything.

Is this possible?

**Comment by holtjonathan** [comment]
Wow...it seems like LumX is crappily supported.  130+ open issues and hardly any comments from the creator?  Making me not want to back this.

**Comment by matmkian** [comment]
You can specify primary and accent colors with hues for each one in your sass project. All switches color will be set according to the accent color. We apologize for the lack of support these times, we're going to release a majors release of LumX very soon.

**Comment by holtjonathan** [comment]
I'm not super familiar with sass projects.  Where is this at?  Thanks for the comment and I'm looking forward to the new Lumx version!

**Comment by matmkian** [comment]
We've just released LumX v1.0.0rc1. This new version fixes the issue, so I'm closing it.
