### ISSUE TITLE
switch tabs to ng-show instead of ng-if

### ISSUE THREAD

**Issue by erapoport** [lumapps/lumX#362]
I'd like to put some non-angular things in a tab, but since the tab html is added and removed from the DOM, it becomes difficult, because attached events disappear, references get lost, etc.

Therefore I'm suggesting to change the `tab.html` template to use `ng-show` instead of `ng-if`, or make it configurable in some way.

**Comment by erapoport** [comment]
Also, related to the same issue - I modified the tab template for ng-show for now, and now I see another problem.

My controller tries to find an element within the one of the tabs in its linking function, but the element is not there unless I put the code in a `$timeout`. Why do the tabs need an async step?

**Comment by matmkian** [comment]
We've just released LumX v1.0.0rc1. I suggest to use the ng-disabled param instead of ng-if/ng-show that may cause some troubles.
