### ISSUE TITLE
Text fields are blurred on dialog resize

### ISSUE THREAD

**Issue by jefvel** [lumapps/lumX#365]
Here's a gif showing what happens: http://i.imgur.com/rlMkjzr.gifv
This is mostly an issue when opening dialogs on cell phones, and trying to type stuff into textfields.
If you do that the on screen keyboard pops up, resizing the window and blurring the textfield, which closes the keyboard immediately.

**Comment by wkeizer** [comment]
I'm having this exact same issue.

**Comment by matmkian** [comment]
Thanks for reporting the issue. I'm going to take a look!

**Comment by matmkian** [comment]
Hi, it's now fixed in the last version of LumX :-)
