### ISSUE TITLE
Some components & Effects not working

### ISSUE THREAD

**Issue by PhentomPT** [lumapps/lumX#375]
When trying to use some components like the dropdowns and inputs don't work.
Button clicking effect does not work too.
Floating action buttons work fine.

Installed via Bower with the steps you provide.
Version is:
- bower cached        git://github.com/lumapps/lumX.git#0.3.96
- bower validate      0.3.96 against git://github.com/lumapps/lumX.git#*

Screenshot:
![lumx-not-working](https://cloud.githubusercontent.com/assets/8815300/11318742/c43687aa-9056-11e5-9095-fd8189ba884c.png)

**Comment by matmkian** [comment]
It seems like you have some conflicts with your CSS or another framework.
