### ISSUE TITLE
Text Input with Label on the top and Icon

### ISSUE THREAD

**Issue by mirabalj** [lumapps/lumX#376]
I try show the input text with icon and text label on top, but is not possible, and the demo not show any example.

Is possible?

Only show the label inside the input
```
<lx-text-field label="Phone number" fixed-label="true" icon="phone">
      <input type="text" ng-model="textFields.fixedLastName">
</lx-text-field>
```

Show the label on the top but don't show the icon (obviously)
```
<lx-text-field label="Phone number">
      <input type="text" ng-model="textFields.fixedLastName">
</lx-text-field>
```

Thanks in advance.

**Comment by matmkian** [comment]
As described in Google guidelines (https://www.google.com/design/spec/components/text-fields.html#text-fields-single-line-text-field), it's not possible, so it's not possible with LumX too :-)
