### ISSUE TITLE
Check if dialog has been opened

### ISSUE THREAD

**Issue by remiemalik** [lumapps/lumX#378]
Hi,

Is it possible to create a get method to access the variable lxDialogIsOpened?

Would like to open a dialog with a progress bar (LxProgressService.circular) and start the progress bar when dialog has been opened. 

Can create a initial method through a pull request, if required.

Kind regards,

Remie

**Comment by badoet** [comment]
currently i interface the LxDialog service with my own service that keep tracked of opened modal dialog.
this could b one solution to go around the waiting time for the master to be updated. (has not been for the past 3 months)
