### ISSUE TITLE
Sidebar directive

### ISSUE THREAD

**Issue by zieemer** [lumapps/lumX#38]
Hi

I've notice that sidebar exist on your  http://ui.lumapps.com/ but there in nothing about it in documentation. 
Are there any plans to implement it ?

**Comment by justingosan** [comment]
:+1: on this feature request.

In the meantime, I'm using the sidebar code from the [main site](http://ui.lumapps.com/getting-started/installation).

**Comment by tagazok** [comment]
Hi @justingosan 
I don't know if this is a secret, but you can have a look at this project : https://github.com/lumapps/lumX-gdg
There is a really nice sidebar! ;)

**Comment by justingosan** [comment]
Thanks for pointing that out @tagazok. Never knew this project existed. The code here is very similar to the one found in the main demo site.

Service: https://github.com/lumapps/lumX/blob/master/demo/js/sidebar.js
CSS: https://github.com/lumapps/lumX/blob/master/demo/scss/modules/common/_modules.common.sidebar.scss
Partials: https://github.com/lumapps/lumX/tree/master/demo/includes/sidebar

**Comment by malexandre** [comment]
Hi!
We're a little late on some things, we had a lot of works on our other projects and could not find enough time to go forward on LumX as we wished. I want to make some ground work this week-end to help everyone one the team in the future.

**Comment by tagazok** [comment]
Then, have a nice week-end. Hope to see the "expand row" like in Inbox component you demonstrated 2 months ago at the GDG in Paris ^^

**Comment by matmkian** [comment]
Hi, we're going to put some layouts in LumX website.
You'll find a navbar in one of them. Be patient, it will come soon :-)

**Comment by dominikbulaj** [comment]
Some time ago (~2-3 weeks) I installed LumX via Bower (LumX v0.2.54) it had SidebarService. Today (2nd project) I did the same and got Lumx 0.3.9 and Sidebar is missing. Also I can't find it on your repository. Has it be removed? Why? It worked just great!

**Comment by malexandre** [comment]
Ah, didn't expected that. There was a bug in our gulpfile, the javascripts of our demo was included in the lib, which is not what we want. The sidebar is not included into Lumx for now. By fixing the bug, the sidebar service is not in the file anymore. If you want it, it's just this:

```js
var sidebar = angular.module('Sidebar', []).service('SidebarService', function()
{
    var sidebarIsShown = false;

    function toggleSidebar()
    {
        sidebarIsShown = !sidebarIsShown;
    }

    return {
        isSidebarShown: function()
        {
            return sidebarIsShown;
        },
        toggleSidebar: toggleSidebar
    };
});
```

**Comment by Ehesp** [comment]
Can anyone explain how to properly put the sidebar in? It's a main feature!

**Comment by alannsiqueira** [comment]
I NEEED SIDEBAR HAHAHA

**Comment by alannsiqueira** [comment]
... Can anyone explain how to properly put the sidebar in? It's a main feature! [2]

**Comment by malexandre** [comment]
You can see an example by @ThomasCrvsr in the #239.

**Comment by vipulsaxena** [comment]
I guess it's been a year now.. No sidebar! Are you guys really working on this thing?

I prefered lumx only because of pre processors, otherwise there's nothing better than https://material.angularjs.org/#/ or polymer :)
