### ISSUE TITLE
lx-text-field with autofocus throws [$rootScope:inprog] error in angular-bootstrap modal

### ISSUE THREAD

**Issue by dizel3d** [lumapps/lumX#381]
The problem is that **angular-bootstap** emits focus event from digest phase. Focus and blur are synchronous events and listeners are called in digest phase too. In that case, listeners should not call `$digest()`. The trouble in [text-field_directive.js#L44](https://github.com/lumapps/lumX/blob/6033fe51b7f679bf970e42a80c3dc2e4f3cef573/modules/text-field/js/text-field_directive.js#L44).

**Comment by matmkian** [comment]
We've just released LumX v1.0.0rc1. This new version fixes the issue, so I'm closing it.
