### ISSUE TITLE
label for select field

### ISSUE THREAD

**Issue by tagazok** [lumapps/lumX#39]
Hi,

Another one for the one in charge of the select component :)
In text fields, we have a label.
But, for the select, there is not. So, I have to create a label and the field next to it as I used to do with bootstrap. It works well but I was wondering if it would be possible to find a beautiful way to include a label with the select component (maybe a css engineer could find a way ^^)

**Comment by malexandre** [comment]
It's done! There is no animation since the dropdown hide the label when the select is open, but there is a label now.
