### ISSUE TITLE
Is Lumx still alive?

### ISSUE THREAD

**Issue by dandanknight** [lumapps/lumX#391]
Hi, Commits and answers to issues, even pretty fundamental ones such as validation of the lx-datepicker seem to be very much on the decline since mid last year.
Is this project still being maintained? Does it have a road map?
Lumx is so very much smoother and nicer to use than Angular Material, but I fear that they are being left behind.
Forgive me if I have misread the situation, I'm a great fan of your work.

**Comment by matmkian** [comment]
Yes, it's still alive ;-) Check the branch rework/all and wait for the version 1.0 that should be available on february :-) We're fixing all issues, improving performances and adding more parameters.

**Comment by dandanknight** [comment]
Excellent! Thank you. I look forward to it :-)
