### ISSUE TITLE
lx-text-field doesn't change ng-model

### ISSUE THREAD

**Issue by FernandoFranco** [lumapps/lumX#400]
```
<!-- Doesn't Change -->
<lx-text-field lx-label="Name">
    <input type="text" ng-model="name">
</lx-text-field>

<!-- Change -->
<input type="text" ng-model="name">

<span ng-bind="name"></span>
<span>{{ name }}</span>
```

**Comment by malexandre** [comment]
Hi !

It's important to avoid primitive type directly in the scope, as said by the angular team.

> If you use ng-model there has to be a dot somewhere. If you don't have a dot, you're doing it wrong.

It's linked to the scope inheritance and javascript (you can search "dot in ng-model" on google/(stackoverflow)[http://stackoverflow.com/questions/17606936/angularjs-dot-in-ng-model]). The lx-text-field directive uses transclusion & isolated scope, which create new scopes. If you use this "mantra", you'll avoid problem like this, and the lx-text-field will work.

**Comment by FernandoFranco** [comment]
Thanks, it works for me
