### ISSUE TITLE
Missing information on how to use code examples

### ISSUE THREAD

**Issue by expilo** [lumapps/lumX#401]
In the new documentation there is no information how  to use javascript example code snippets of lumx' components in an Angular app. A minimal complete Angular app code example with lumx component code would be useful.

**Comment by malexandre** [comment]
Hi!

I'm not sure what you mean. If we check the JS example for the dialog: http://ui.lumapps.com/components/dialog

There is a full controller, the ony thing missing is the app declaration (which is here if you check the source: http://ui.lumapps.com/app.js, and is also documented here: http://ui.lumapps.com/getting-started/installation).

What do you think is missing?

**Comment by expilo** [comment]
Sorry for my ignorance, I don't understand the syntax of example app. Where exactly should I put the example snippett to make it work?
