### ISSUE TITLE
Others directives dont work inside dropdown

### ISSUE THREAD

**Issue by playUruguay** [lumapps/lumX#402]
Hi, i want to load another directives inside the dropdown like ng-file-upload or lightbox but not loaded.

Thanks

**Comment by malexandre** [comment]
Hi!

What do you mean by "don't work"? I just tried using a lx-text-field in the dropdown, it works well. Did you stop the propagation of the click around your directive? Remember that a dropdown closes itself when it detects a click inside its lx-dropdown-menu. You must stop the propagation if you need to have a form in it.
