### ISSUE TITLE
ng-controller not binding to lumx dropdown

### ISSUE THREAD

**Issue by ZhangMYihua** [lumapps/lumX#404]
Hey guys, I'm trying to call ng-controller on the lx-dropdown-menu element but it seems that I can't access my scope variables inside of the dropdown.

For example:

The Html
`<lx-dropdown-menu ng-controller="NotificationsCtrl">`
  `{{ testMessage }}`
`</lx-dropdown-menu>`

The controller
`angular.module('angularApp').controller('NotificationsCtrl', function(){`
 ` $scope.testMessage = "Lorem Ipsum"`
`}`

But the testMessage won't load into it. 

Can you advise?

**Comment by malexandre** [comment]
Hi!

`lx-dropdown-mennu` is a directive with its own scope, and its content is transcluded and thus does not have access to its scope. The solution would be to create a div inside the `lx-dropdown-mennu`, and apply the ng-controller to this div:

```html
<lx-dropdown-menu>
    <div ng-controller="NotificationsCtrl">
        {{ testMessage }}
    </div>
</lx-dropdown-menu>
```

**Comment by ZhangMYihua** [comment]
Ahhhh I see! thank you!
