### ISSUE TITLE
Bower installs version 0.3.96

### ISSUE THREAD

**Issue by wambugu-waweru** [lumapps/lumX#405]
Hey, am trying to install lumx via bower but am getting **version 0.3.6** but it says on bower's website that it has been updated 20 hours ago _(at the time)_. How to I get the **version 1.0.0 **?

**Comment by malexandre** [comment]
Hi,

As said in the issue #397, the 1.0.0 is only a release candidate, and bower does not use it as the default version. But you can install it with `bower install lumx#v1.0.0rc1`.
