### ISSUE TITLE
Input Label doesn't work

### ISSUE THREAD

**Issue by hamidyfine** [lumapps/lumX#406]
Hi,
I'm new to lumx. It's really nice and I'm using it in my latest project.
But, I have problem with inputs. 
I create input text with this code: 
```html
<div flex-item>
    <lx-text-field lx-label="Fist name">
        <input type="text">
     </lx-text-field>
</div>
```
but after runnig the page, it just showing an input filed without label.
What did i miss?

**Comment by malexandre** [comment]
Hi!

What do you mean by an input filed without label ? On the demo it works quite well. Can you provide a screenshot. Here's a gif to show the demo:
![lx-label](https://cloud.githubusercontent.com/assets/1535967/13466328/c782a022-e099-11e5-9200-977b0f0471bb.gif)

**Comment by hamidyfine** [comment]
@malexandre This is what happened in my project.

![lumxinput](https://cloud.githubusercontent.com/assets/7509480/13485581/aaa44fac-e11e-11e5-8dbc-ca3f92a63940.gif)

**Comment by hamidyfine** [comment]
I compared my code with LumX demo. the difference is in the ng-bind-hmtl.
after running my code, in the label tag, there is:
`ng-bind-html="label | unsafe"`
that this is not in the demo.

**Comment by malexandre** [comment]
Can you paste your code please? I'm not sure where this ng-bind is.

**Comment by hamidyfine** [comment]
I upload my project in this address:
[http://www.hamikar.com/demo/lx/](url)

I think i missed something because many of the components are not working like `lx-icon` , `lx-tabs` , `lx-theme` (for the input) and some others that i checked so far.

**Comment by malexandre** [comment]
Ok, I see the problem. There is a lot of javascript error, but the most important one I think is this one:
`Uncaught ReferenceError: DemoSelectController is not defined`. You define the function DemoSelectController inside your file demo.js but use it in index.html. But you use a closure for your JS file, so the index.html does not know the function DemoSelectController.

The solution would be to put your app declaration inside the file demo.js:
angular.module('Hamikar', ['lumx']).controller('DemoSelectController', DemoSelectController);

**Comment by hamidyfine** [comment]
Thanks so much for your solution.
I do what you say and most of the js errors solved. But now, in generate one error on load and when i click on the input:
`TypeError: Cannot read property '$modelValue' of undefined`

What is it about? what should I do for this?
Thanks.

**Comment by jmijmi** [comment]
You must set ng-model for your input fields.
```
<lx-text-field lx-label="Company" lx-allow-clear="true">
    <input type="text" ng-model="vm.textFields.floating.company">
</lx-text-field>
```

**Comment by malexandre** [comment]
Thank you @jmijmi, I think this is the problem too.

**Comment by hamidyfine** [comment]
Thank you @jmijmi for you reply.
I set `ng-model` but it doesn't work.

**Comment by hamidyfine** [comment]
I worked on it and solve the error above (`TypeError: Cannot read property '$modelValue' of undefined`) Thanks @jmijmi for give me the clue for that.
Now, there is no error on the page but the problem in still there!!! input without label!
I check the codes and notice that, this tag is assigned to label:
`ng-bind-html="label | unsafe"`

what is that? and what can cause this?

**Comment by maxlabelle** [comment]
I have the same problem, I run lumx with nwjs, but the labels don`t work.

https://gyazo.com/8bfcdab36f68d6cfae5f7555b14555a1

https://gyazo.com/c6e4a298dcc769830c590f1b99035a6e

**Comment by sincerekamal** [comment]
yes, I'm getting this problem too.. please help to resolve...

**Comment by blairwinans** [comment]
FYI - I ran into this issue with the v0.3.96 release that is currently installer via bower—but when manually downloading the current RC it seems to work as expected in the demo.
