### ISSUE TITLE
LX Dialog not rendering the lx-dialog-* directives inside

### ISSUE THREAD

**Issue by vajnorcan** [lumapps/lumX#410]
I must be doing something wrong but I seem to be unable to find it, or maybe I've misunderstood the concept of lx-dialog and its directives.

At the top level of my views hierarchy (ui-router), I have this 

```
<lx-component>
		<lx-dialog id="settingsDialog" lx-auto-close="true">
			<lx-dialog-header>
				Settings
			</lx-dialog-header>
			<lx-dialog-content>
				I'm the content
			</lx-dialog-content>
			<lx-dialog-footer>
				...
			</lx-dialog-footer>
		</lx-dialog>
	</lx-component>
```

But once I open the dialo via the dialog service, the directives are not rendered:
![image](https://cloud.githubusercontent.com/assets/5698035/13586562/c9d8d30c-e515-11e5-927d-7a617bd12b57.png)

It also seems like the css, isn't the dialog missing some extra classes, as the result is that the "dialog-filter" is above the dialog itself, thus dimming it. There are no other clashing css's. Any ideas? thanks

**Comment by matmkian** [comment]
What i the <lx-component> wrapping your dialog?
