### ISSUE TITLE
Tabs in v1.0.0rc2 have lost the ripple effect

### ISSUE THREAD

**Issue by monzonj** [lumapps/lumX#413]
tabs in v1.0.0rc2 have lost the ripple effect that was there in 0.3.9

**Comment by monzonj** [comment]
HTML is there, what's missing is the CSS

**Comment by monzonj** [comment]
@each $key, $color in $colors {
  .tabs--theme-light.tabs--color-#{$key} {
    .ripple {
      background-color: darken($color, 20%);
    }
  }

  .tabs--theme-dark.tabs--color-#{$key} {
    .ripple {
      background-color: lighten($color, 20%);
    }
  }
}


That will do the trick. I used 20% because the 50% you use in buttons is rather too much?

**Comment by jmcarayol** [comment]
The problem persists in v1.0.0rc3.

**Comment by matmkian** [comment]
Thanks for reporting! We've fixed the issue. Wait for the v1.0.0rc4 release :-)
