### ISSUE TITLE
Datepicker how to select a date themselves after close?

### ISSUE THREAD

**Issue by jackswei** [lumapps/lumX#417]
After ask, Datepicker how to select a date themselves after close?

**Comment by matmkian** [comment]
I'm not sure to understand your question?

**Comment by jackswei** [comment]
like http://www.material-ui.com/#/components/date-picker ,see Ranged example(This example allows you to set a date range, and to toggle autoOk, and disableYearSelection)

**Comment by matmkian** [comment]
As you can see in the documentation, you can specify a date range available for selection.
