### ISSUE TITLE
Cannot pass in class or id to button

### ISSUE THREAD

**Issue by stephenycchang** [lumapps/lumX#418]
Since the update, we can no longer pass in a class or id to the button directive.

eg.
`<lx-button lx-type="raised" class="foo">Button</lx-button>`

will render

```
<button ng-transclude="" lx-ripple="" lx-type="raised" class="btn btn--m btn--primary btn--raised" style="position: relative; overflow: hidden;">
  <span class="ng-scope">
    Button
  </span>
</button>
```

**Comment by matmkian** [comment]
Thanks for reporting! We've fixed the issue. Wait for the v1.0.0rc4 release :-)
