### ISSUE TITLE
Dying project

### ISSUE THREAD

**Issue by monzonj** [lumapps/lumX#423]
Hey,
In web technologies world, having a library that doesn't get any kind of love for weeks or months is a clear symptom of death. Many great tools appear every day and hoping this one just sticks "because" is delusional.

This project not only gets minimum attention, but it has too few people looking over the issues or pull requests (actually nobody). There isn't even a discussion group for the community to help themselves.

Come'on guys, give it to the community or involve yourselves a little more.

Cheers,

**Comment by violacase** [comment]
I am concerned also. The projects demo is a great joy to play with and the scaffolding environment looks very professional. After I installed and the latest version I'm getting a lot of errors. What a pitty...

**Comment by matmkian** [comment]
@violacase Can you give us examples of issues you're experiencing?
@monzonj The project is not dead. First of all, this is a framework that we use for large projects. We wanted to make our own framework to suit our needs. We've decided to let it open for users who want to have an alternative to other angular frameworks. We have a lot of works so we can't be as available as you want, we're sorry. We do our best to maintain the quality of the library. If it doesn't suit your needs, i suggest you to try other available frameworks.

**Comment by monzonj** [comment]
That's fair enough. So you are saying this is not a framework for the community but something you offer as it is.

It is important to know this, because it is not at the same level as other material frameworks where they do worry about their community. Here you don't.

That's fine, I suppose.

**Comment by mtorres0612** [comment]
Is this Framework way better than Angular Material?

One of the advantages of this over AM is its performance in IE11. Other items? Still learning to know.

If this fully tops AM, I might be using this framework. So hoping this project won't 'DIE'.

Thanks!
