### ISSUE TITLE
Angular 2 compatibility

### ISSUE THREAD

**Issue by kpakozz96pyc** [lumapps/lumX#424]
Hi! We all know that Angular2 is coming. Are you going to have support of it, or some plan of migration?
If I'm going to update my current project from 1.x to 2.x Angular version will it be good idea to start using your framework?

**Comment by matmkian** [comment]
Hi, we're going to work on an Angular2 version of the framework. Unfortunately i can't give you a date. I think it won't be available before this fall.

**Comment by Codicode** [comment]
any news about an Angular 2 version of Lumx ?

**Comment by serak** [comment]
ya we would like an update on the progress

**Comment by SkyzohKey** [comment]
Up ? 

_Sent from my WIKO LENNY3 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by clementprevot** [comment]
We don't have any ETA for the Angular2/4 version of LumX.
We currently don't have any resource to work on this topic.

We will keep you informed as soon as we start to work on it.

**Comment by SkyzohKey** [comment]
I could participate if you explain me what the basics would be :p

**Comment by clementprevot** [comment]
We basically set some basis of the LumX² architecture but we didn't do much.
So I'm afraid we can't take any help from the community for the moment as we are not sure ourselves where and how we are going to do it.

**Comment by SkyzohKey** [comment]
I guess you'll have to redefine every component as a ng2 one, then rewrite the directives and so on, looks simple to me, just seems to be boring to do. But hey! lumx is awesome and ng2 is too :p

**Comment by SkyzohKey** [comment]
Would you accept if I try to do a port for ng2 ?

**Comment by clementprevot** [comment]
You can of course do your own port of LumX to ng2/4, but we will not support it here. We have some plan on what we want to do, what tools we want to use. But we haven't decided on how we will do it.

We hope to be able to begin working on this subject after this summer.

**Comment by SkyzohKey** [comment]
Ok seems fine. I'll try porting it, even if that's just for the lulz ;)

**Comment by clementprevot** [comment]
I wish you to have fun with this :wink:
