### ISSUE TITLE
serach-filter on open mode :wrong layout

### ISSUE THREAD

**Issue by xlhl77** [lumapps/lumX#426]
````
    <div class="toolbar">
        <span class="toolbar__label fs-title">title</span>

        <div class="toolbar__right">
            <lx-search-filter>
                <input type="text" ng-model="options.cond" >
            </lx-search-filter>

            <lx-button lx-color="blue" href="/customer/edit" >button one</lx-button>
            <lx-button lx-color="blue" href="/customer/order" >button two</lx-button>
        </div>
    </div>
````
 the button will be changed to two row.

remove css : search-filter--open-mode : width:100%,it runs!

**Comment by matmkian** [comment]
I'm not sure to understand... Can you provide a screenshot of your problem?

**Comment by xlhl77** [comment]
![search-filter](https://cloud.githubusercontent.com/assets/11374799/14284121/c34e7e1e-fb78-11e5-977c-e5a553853bd2.png)

**Comment by matmkian** [comment]
That's because you have not enough space. You have to specify the lx-width attribute to be sure that the search filter won't take to much space when open. Otherwise, you can specify the css flex-shrink attribute to zero on your buttons.
