### ISSUE TITLE
flex-container column not working on IE 11

### ISSUE THREAD

**Issue by angeldaniel-adcm** [lumapps/lumX#427]
As the title says, when I use flex container column, the flex item it's not displaying as it should be.
it is display in the same place  ( 1 over other 1)

**Comment by angeldaniel-adcm** [comment]
Edit: the explanation on the site (http://ui.lumapps.com/css/flexbox) seems to be wrong. When declaring a flex-container="column"
the following div don't need the "flex-item" declaration (which is why IE 11 fail to load the column correctly)

**Comment by matmkian** [comment]
Thanks for reporting! We've updated our documentation. Wait for the v1.0.0rc4 release :-)
