### ISSUE TITLE
No ripple effect in button and also error on clicking it

### ISSUE THREAD

**Issue by sincerekamal** [lumapps/lumX#428]
I have used the
````
<lx-button lx-type="raised">Button</lx-button>
````
above code from [Component: Button](http://ui.lumapps.com/components/button) . It is displayed correctly, but there is no ripple effect when I click that button. Instead I'm getting the below error in the console

<img width="1280" alt="screen shot 2016-04-06 at 12 03 19 pm" src="https://cloud.githubusercontent.com/assets/3885228/14307854/a5806a1a-fbef-11e5-8376-b6cdc83724ef.png">

**Comment by matmkian** [comment]
Have you correctly called jQuery library?

**Comment by stephenycchang** [comment]
@sincerekamal 
I had the same problem, but it turns out that you just have to make sure jQuery loads before this framework.

**Comment by marioCoder94** [comment]
Hello I had the same problem but I fixed it including first JQuery and after Angular
