### ISSUE TITLE
Double-clicking outside dialog to close causes error

### ISSUE THREAD

**Issue by MelissaFrechette** [lumapps/lumX#436]
When you double-click when closing a dialog by clicking outside, an error is thrown: "Uncaught TypeError: Cannot read property 'element' of undefined”

This error occurs even on the example components dialogs on the lumx website.

I looked into it a little, to see if it was something I could fix, myself, and it looks like the _dialogId get's cleared with the first click, but the handler for closing the dialog lingers for a bit longer, leaving the second click to pass an undefined _dialogId

**Comment by matmkian** [comment]
Thank you for reporting the issue. I'll take a look when i'll have time.

**Comment by matmkian** [comment]
Hi, last LumX release fix the error :-)
