### ISSUE TITLE
can't get my ng-model in lx-text-field

### ISSUE THREAD

**Issue by sayaa** [lumapps/lumX#437]
Hi, 

I used lx-text-field with the last version of lumx. something like : 

`<lx-text-field lx-label="Company" lx-allow-clear="true">
        <input type="text" ng-model="test">
 </lx-text-field>`

when I fill the input and then click a button which console log $scope.test, it shows undefined

but if I store it in an object, for example : `ng-model="obj.test"` it shows the value I entered in my input.

In previous version of lumx I was able to access the model even if it is not stored in an object. 
Can anyone explain me why? 
And is it possible to access my model without using an object? If so, how can I do it pliz?

**Comment by matmkian** [comment]
It's an Angular good practice to store your model into an object. Don't bind primitive element to angular ng-model.
