### ISSUE TITLE
Support for determinate progress bars. 

### ISSUE THREAD

**Issue by Danielku15** [lumapps/lumX#438]
The progress components currently only support the indetermined state. I would really like to show some absolute progress values. Is there already something planned? Since the indeterminate animation is way more complicated than the absolute value indicator I assume it's not too much work. 

See angular-material for some examples: 

https://material.angularjs.org/latest/demo/progressCircular
https://material.angularjs.org/latest/demo/progressLinear

**Comment by matmkian** [comment]
Hi, we'll soon need this component in our product. Stay in touch!

**Comment by matmkian** [comment]
As promised, the determinate progress bars are available in v1.0.5 :-)
