### ISSUE TITLE
Lexerr in Angular 1.5 due to 'Â' character on load prevents animations

### ISSUE THREAD

**Issue by aj-newton** [lumapps/lumX#444]
Error: [$parse:lexerr] Lexer Error: Unexpected next character  at columns 654-654 [Â] in expression [{ 'text-field--error': lxTextField.error,
                 'text-field--fixed-label': lxTextField.fixedLabel,
                 'text-field--has-icon': lxTextField.icon,
                 'text-field--has-value': lxTextField.hasValue(),
                 'text-field--is-active': lxTextField.isActive,
                 'text-field--is-disabled': lxTextField.ngDisabled,
                 'text-field--is-focus': lxTextField.isFocus,
                 'text-field--theme-light': !lxTextField.theme || lxTextField.theme === 'light',
                 'text-field--theme-dark': lxTextField.theme === 'dark',
                 'text-field--valid': lxTextField.validÂ }].

Animations would stop working altogether.

Fixed by replacing the 'Â' with a space in both lumx/dist/lumx.js and lumx/dist/lumx.min.js (it is the only 'Â' in both files)

**Comment by aj-newton** [comment]
Fix in pull: #445

**Comment by elund121** [comment]
+1
