### ISSUE TITLE
It is possible to clear an lx-select filter on choice selection?

### ISSUE THREAD

**Issue by ciclick** [lumapps/lumX#446]
Hi, 

it is possible to clear the filter and the choices of an lx-select when I click on a list option?

Thank you!

**Comment by matmkian** [comment]
You mean in single or multiple mode?

**Comment by ciclick** [comment]
In single mode, with filter

**Comment by matmkian** [comment]
You can update your choices array with the lx-select ng-change method. However, you can't clear the filter.
