### ISSUE TITLE
lxDropdown undefined error on new 1.0.6 Lumx

### ISSUE THREAD

**Issue by badoet** [lumapps/lumX#448]
Im upgrading from "0.3.96" to 1.0.6.

But the new lxDropdown doesnt seems to work well
Error text that i get: 
Uncaught TypeError: Cannot read property 'lxDropdown' of undefined

```
angular.element('.dropdown').each(function(index, dropdownElem)
                {
                    console.log(angular.element(dropdownElem));
                    console.log(angular.element(dropdownElem).scope());
                    if (angular.isDefined(angular.element(dropdownElem).scope().lxDropdown) && angular.element(dropdownElem).scope().lxDropdown.isOpen)
                    {
                        angular.element(dropdownElem).scope().lxDropdown.closeDropdownMenu();
                    }
                });
```

its on this line: angular.isDefined(angular.element(dropdownElem).scope().lxDropdow

i use the html code in the demo.html and its still not working.
help?

**Comment by badoet** [comment]
UPDATE:

After 4 hours of debugging i figured out what is the problem:

`$compileProvider.debugInfoEnabled(false);`
this line will break lxDropdown module!
lets put in a fix so that it dont rely on the ng-scope attributes in the DOM element..

**Comment by matmkian** [comment]
Hmmm, very interesting!
We're going to disable debug mode for one of our product.
So i will take a look and give you a feedback.

**Comment by matmkian** [comment]
You can now disable debug mode as we don't get the scope from an html node anymore.
