### ISSUE TITLE
Reduce tab navigation height

### ISSUE THREAD

**Issue by muffinjello** [lumapps/lumX#451]
Hello,

I was wondering if there was any hidden attribute or easy way to change the height of the [tab navigation](http://ui.lumapps.com/components/tabs) buttons. Right now, they look like they're 48px tall, but I'd like to condense them a bit - perhaps to 36px?  Does this break material design spec, if they're that small? (I'm making a editor app, rather than a single page website.)

Or should I just hack them to be smaller with CSS (if even possible?)

**Comment by matmkian** [comment]
As we follow the Google Material Design documentation, you can't reduce the height of tab navigation buttons. However, you can do it with a CSS hack.
