### ISSUE TITLE
LxSelectChoicesController injection error

### ISSUE THREAD

**Issue by Aditya-Sh** [lumapps/lumX#488]
Hello,

I am getting an error using Select component of lumx. Error id below
`LxSelectChoicesController is not using explicit annotation and cannot be invoked in strict mode`.

This is probably because somewhere injection hasn't been done correctly.

Update: 
This is due to wrong controller name while injecting.
Line no 3171 of lumx.js in dist.
Controller name should be `LxSelectChoicesController` and not `LxSelectSelectedController`

Using version 1.0.0

**Comment by arnaudvalle** [comment]
Hello there, I'd suggest you try to upgrade your lumx version as it doesn't look like it's an issue in the more recent versions.
