### ISSUE TITLE
Is there a pagination component provided?

### ISSUE THREAD

**Issue by luckyadam** [lumapps/lumX#49]
I thought a pagination component could be very common in the projects, will you consider adding it to lumx in the future?

**Comment by matmkian** [comment]
Thanks for your support, we really appreciate :-)
As Google Material Design Guidelines never speaks about that component, we're not going to provide it on LumX. But I think that it can be a good idea to provide a separate UI library with custom components like pagination or carousel.

**Comment by kataynoi** [comment]
infinite scroll  it good
