### ISSUE TITLE
Radion button gets wrong selected

### ISSUE THREAD

**Issue by publicroot** [lumapps/lumX#491]
I just want to report a bug. You can see it in the docs:

http://ui.lumapps.com/components/radio-button

Refresh browser or enter the page, click a radio button and you can see, the button one over the clicked one gets selected (or the last one, if you click the first one).
If you click a second time, than everthing works as expected.

**Comment by vanilla-thunder** [comment]
can confirm this.
when no radio is preselected, the first selected radio is alwys not the one i clicked on.
tested with 1.5.11 and 1.5.13
