### ISSUE TITLE
Floating action button leaving artifacts on screen

### ISSUE THREAD

**Issue by michaelryancaputo** [lumapps/lumX#52]
After clicking the 'Floating action button' to trigger an action, it's leaving floating artifacts of the label, noticed this on Chrome on and iPhone 6+ and also on the latest Chrome Canary for OSX. Screen shots attached. 1st one, is before clicked, 2nd one is after clicked "remove song" label still remains.

![img_0547](https://cloud.githubusercontent.com/assets/80901/5454936/e66a57ec-8504-11e4-89f0-edcea9f4c721.PNG)

![img_0546](https://cloud.githubusercontent.com/assets/80901/5454935/e6658b22-8504-11e4-9a69-4eb0f11e5a79.PNG)

**Comment by matmkian** [comment]
Floating action buttons has been completly reworked. Bug Fixed !

**Comment by michaelryancaputo** [comment]
:+1:
