### ISSUE TITLE
lx-Tabs please help!

### ISSUE THREAD

**Issue by IvoFacundo** [lumapps/lumX#536]
Hi, I'm new to this framework, and I was seeing tutorials from a person using this framework, in 2015, I'm implementing lumx in a project, but I get a erro in the console.

**TypeError: element.parent(...).index is not a function**
![console](https://user-images.githubusercontent.com/13089746/27890432-0c47bcae-61c9-11e7-878f-998d9e0decbb.png)
![st](https://user-images.githubusercontent.com/13089746/27890433-0c6cf924-61c9-11e7-9b91-d2c4dcf6c412.png)

## In the second pic, the first lx-label doesn't matter, i fix that to "Posts" and the error still :S

I know it's to be used lx-tab, but i dont know how to implement in my proyect.

Where can I find some examples of usage?

Please help!

(sorry for my english) :)

**Comment by clementprevot** [comment]
Hi @IvoFacundo,

You can find all the documentation and tons of example in the [LumX website](http://ui.lumapps.com). Please check the [Components/Tabs section](http://ui.lumapps.com/components/tabs) of the documentation to learn more about Tabs. You can click on the "<>" button on the top right corner of each example to see the HTML and JS code of them.

If you still have an issue using LumX, don't hesitate to update your issue.

**Comment by stiv15** [comment]
Hola @IvoFacundo,
Estoy viendo que es el mismo ejemplo pero con las librerías actualizadas de angular y de lumx,
lo solucione ajustando el orden de los scripts de js
`	
	<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>

	<script src="https://cdnjs.cloudflare.com/ajax/libs/velocity/1.2.2/velocity.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment-with-locales.min.js"></script>
	
	<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.6/angular.min.js"></script>
	<script src="https://code.angularjs.org/1.6.6/angular-route.min.js"></script>

	<script src="js/lumx.js"></script>
	<script src="js/app.js"></script>
	<script src="js/services.js"></script>
	<script src="js/controllers.js"></script> `

Saludos espero que sirva.

**Comment by arnaudvalle** [comment]
Hello there,

seems like @Vits84 's proposed answer is completely valid and works so I will close this issue now.

Many thanks,
