### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by tagazok** [lumapps/lumX#54]
Hi !
I see a lot of questions about new features (pagination, etc) in the issues.

Last week, at the GDG meetup, you mentioned that you might make your roadmap public.
As, like a lot of people, am waiting for certain components (such as expand row when clicking to load content as I saw in the demo the other day ^^), I am wondering if you still plan to make it public?

**Comment by malexandre** [comment]
Hi!

Sorry for the delay, the holidays and other stuffs made me late. Here's the roadmap: https://github.com/lumapps/lumX/blob/master/ROADMAP.md.

**Comment by tagazok** [comment]
Just a bit of harassment, the open/expand a list item à la inbox by google is stil arriving really soon? ^^

Can't wait to use this amazing feature in my projects :D
