### ISSUE TITLE
Scrollbar doesn't work in Firefox

### ISSUE THREAD

**Issue by ilyakam** [lumapps/lumX#55]
[The Scrollbar example](http://ui.lumapps.com/directives/scrollbar) does not work in Firefox (_version 34.0_)
It works fine in Chrome (_version 39.0.2171.95_).

Running on Mac OS 10.9.5

**Comment by matmkian** [comment]
The scrollbar component will be deprecated in the next major release as we choose to use the native browser scrollbar.
