### ISSUE TITLE
Can I use lumx along with angular-material?

### ISSUE THREAD

**Issue by demetriusnunes** [lumapps/lumX#57]
Are the 2 projects compatible to be used in the same application?

**Comment by sondreb** [comment]
I'm working on a Chrome App where I'm using both angular-material and LumX. The dropdown list was the reason why I ended up using LumX together with angular-material, and right now I'm primarily only using the sidebar feature of angular-material. Both UI frameworks implements the CSS a little differently, I kinda hope that all of the material UI frameworks eventually implements the same style.

**Comment by matmkian** [comment]
Hi, thank you very much for your feedback!
The sidebar will be provided when we'll pu some layout examples into LumX website.

**Comment by tagazok** [comment]
Any idea when these layout examples will be available? ^^

**Comment by sagar-ganatra** [comment]
I'm also waiting for this layout example to be available, is this going to change how FlexBox is designed in lumx. Also very keen to see sidebar making into the next release. Any date of it's release?

**Comment by jmijmi** [comment]
+1

**Comment by SeidiJr** [comment]
+2

**Comment by Benew** [comment]
Good question. I'm mostly interested in the date / time pickers from LumX
