### ISSUE TITLE
IE 10 select not opening when clicking on label

### ISSUE THREAD

**Issue by danniehansen** [lumapps/lumX#576]
**Motivation for or Use Case**
Some of our users uses IE 10. Which results in them not being able to choose anything from our select elements when clicking on the label element. What i found out is that it's because of a pointer-events CSS property. Which is a non-standard property. How we solved this at other places we needed to use pointer-events within our own core is to forward the click even through the element to the one below.

**lumX Version(s)**
Happening on all v1.0.4 which we're using (i know it's old) but also on the latest v1.6.18.

**Browsers and Operating System:**
Windows 8, IE 10

**Reproduce the Error**
Open http://ui.lumapps.com/components/select & click on the label for the select. Here you'll notice that when clicking on the label it-self it won't trigger the select dropdown. http://jmp.sh/A2dFyvd

**Comment by akinjide** [comment]
**lumX Version(s)**
v1.7.23

Try that version using the affected browser IE 10, looks good on Safari v11.0.3

**Comment by clementprevot** [comment]
Thanks @akinjide for answering to this issue.
However please keep in mind that we only provide support for the last two version of all majors browser.
It means that, in the case of IE, we only support IE11 and Edge.

I hope that the latest version of LumX will solve your problem
