### ISSUE TITLE
Dropdown broken on mobile devices

### ISSUE THREAD

**Issue by alexandre-nicolas** [lumapps/lumX#598]
Hi,

It seems that the dropdown component ignore touch events on mobile devices : 

* If I touch a menu item, the dropdown closes. There isn't any wave effect. If a click-able element is behind the dropdown, this element is considered as clicked/touched.
* Can't swipe to scroll on large list, dropdown closes.
* Can't select any item in Select field.

**Step to reproduce** : 
* Try the Select/Dropdown demos with a browser emulating touch events (FF and Opera tested) or with a mobile device.

NB : The select "Basic usage" works almost fine on my phone (Chrome 65), can't scroll though.

I did not take time to dig into the code. Problem has happened somewhere between 1.6.15 and 1.7.26. 1.6.15 was broken aswell as I couldn't select any _overflown_ element.

Thanks in advance

**Comment by philippeBchn** [comment]
Hi @alexandre-nicolas,

Yesterday we released the 1.7.30. This version updates the dropdown logic to improve the support of the mobile (specially iOS 10/11).

I hope this version will fix your troubles.
