### ISSUE TITLE
_canceled always true when closing a dialog

### ISSUE THREAD

**Issue by StephaneConqDGC** [lumapps/lumX#621]
Hi,

Each time I close my Dialog, I try to catch the event in my JS. 
![image](https://user-images.githubusercontent.com/44082925/47513569-ca851b80-d87e-11e8-8fea-ae455dfe1b72.png)

This works, but I want to use the _canceledparameter. And this parameter is always "true", however I close my dialog.
![image](https://user-images.githubusercontent.com/44082925/47513316-42067b00-d87e-11e8-9f20-9df13706feb5.png)
In the documentation, there is no difference between the OK button and the Cancel button.

How can I make the difference between closing the button with Cancel or OK ?

Thanks in advance.

**Comment by clementprevot** [comment]
Hi @StephaneConqDGC 

You should not always use `lx-dialog-close`.
This one always close the dialog as a cancel.

Instead, you should bind a `ng-click` on your "OK" button to a function that will call `LxDialogService.close(dialogId[, isCanceled, params])`.

Hope this helps.
