### ISSUE TITLE
Design choices for Dialog and Progress components

### ISSUE THREAD

**Issue by demetriusnunes** [lumapps/lumX#64]
Please, turn Dialog into a service and Progress into a directive (a la angular-material). It just makes much more sense this way.

**Comment by matmkian** [comment]
Hi, we would be very interested if you can contribute to LumX with your wrappers? Thank you!

**Comment by emadgh** [comment]
1+ :+1: 

It would be really good if someone could write a more advanced Dialog Service for lumX. 
Thank you.

**Comment by priithansen** [comment]
Needed to replace

scope.element = element;
scope.parent = element.parent();

with

scope.lxDialogIsOpened = false;
scope.lxDialogElement = element;
scope.lxDialogParent = element.parent();

to get @demetriusnunes example to work. If I could figure out how to use controller as syntax with that option while defining the izDialog.show controller option in closure I would be a happy camper :)
