### ISSUE TITLE
Enhancements for Thumbnail

### ISSUE THREAD

**Issue by ThomasBurleson** [lumapps/lumX#70]
Here are some suggestions to possibly consider:

- Move the logic to compare old !== new values into the controller
- Instead of watching the internal `init` variable to gather changes for src, width, and height. Why use $timeout() to async call call ctrl.update(element, attrs); which would check for changed values.
- Cache the image loads in an ImageService registry 
> AFAIK, the `img.onload()` will only fire the first time the browser loads the image. So a cache is necessary to cross-reference load success with src url. This way other thumbnails with the same url will not use the `onload()` callback.

Also I am curious why this approach was not used:

```html
<lx-thumbnail 
     ng-src="{{item.srcURL}}" 
     lx-thumbnail-width="{{item.width}}" 
     lx-thumbnail-height="{{item.height}}" 
  />
```

**Comment by jameswyse** [comment]
:+1:  I was trying to use `.thumbnail--is-loading` to show a loading indicator but it doesn't work after the first page load :/

**Comment by matmkian** [comment]
Thumbnails are no more available in LumX v1.
