### ISSUE TITLE
Make lumX available via npm with browserify

### ISSUE THREAD

**Issue by itkach** [lumapps/lumX#74]
First of all, I'd like to say thank you for this project. It is already far better than angular-material (widget set, look out of the box, performance) and hopefully will continue to improve.

I would love to be able to use lumx via npm+browserify, without bower. It's rather unfortunate that there is no consensus on packaging and dependency management for the frontend development. It appears (to my novice eye) that npm+browserify and bower are two top choices at the moment, and it also appears that npm and browserify are both very versatile and [ready to evolve to support frontend more](http://blog.npmjs.org/post/101775448305/npm-and-front-end-packaging) while bower is rather naive (nothing wrong with that, it's just that it doesn't do enough). 

Initially I started my new project with angular-material and I was able to get all javascript dependencies set up with browserify, having single `<script>` element in index.html to load browserify-produced bundle. 
I found angluIar-material lacking and was very glad to discover lumX. Trying to set it up with browserify I ran into to two problems. One of course is the topic of this issue - lumX doesn't seem to be available as npm module. Another is that even though all lumX's dependencies are available as npm modules, velocity.js ('velocity-animate' in npm registry) is expected to be a jquery plugin (dropdown menu element is looking for .velocity() method) and for some reason velocity doesn't register as jquery plugin when these components are loaded via browserify's `require()`. It appears that [velocity.js itself no longer requires jquery](http://julian.com/research/velocity/#dependencies) and mere "presence" of jquery doesn't make it register as plugin. 

I was able to get lumX (0.2.11) to work by adding all the dependencies as `<script>` elements, but using `<script>` and relying on browser globals feels like a step backwards compared to using modules with `require()`.

**Comment by jasonaden** [comment]
+1 I know that the NPM guys have started making the transition to handling front-end libraries as well. This is why Google has started publishing Angular (and all it's related modules) on both NPM and Bower.

**Comment by kentcdodds** [comment]
+1, please do this. I'm not using browserify. I'm using webpack. It's amazing. I highly recommend it. Either way, I can use webpack to get my bower packages, but I much rather have everything use npm. Please publish a version on npm :-) I recommend [this method](https://medium.com/@kentcdodds/how-to-distribute-your-angularjs-module-e04d4dd58ddc)

**Comment by vlopez5** [comment]
+1
I think npm is evolving to support front-end and I am already using it for front-end dependencies.
Please do this.

**Comment by kentcdodds** [comment]
Note, [the angular team](https://github.com/angular/angular.js/pull/10732#issuecomment-75225380) is going to do `module.exports = 'moduleName'`, so I highly recommend that this project does the same so when I `require('lumX')` it gives me the name of the module, not the module itself.

**Comment by theofidry** [comment]
+1, regardless of potential use of browserify, npm is as much used as bower for front-end packages management. And if you're on another stack than nodejs and already have a package manager, like bundler for Ruby or Composer for PHP, since npm is required for Bower, it's makes 3 package managers... And seriously Bower doesn't provide any feature that npm does not have.

And since the package.json is very similar to the bower.json, it's really easy to publish!

**Comment by ShMcK** [comment]
+1, also using Webpack. Luckily, all of the LumX Bower dependencies have existing npm modules already.  For anyone with a similar issue, you can load the LumX dependency with the [`imports-loader`](https://github.com/webpack/imports-loader).

```javascript
 global.$ = global.jQuery = require('jquery');
  require('jquery.transit');
  require('velocity-animate');
  require('angular');
  global.moment = require('moment');
  require('imports?angular!./bower_components/lumx/dist/lumx.js');
```

**Comment by siteslave** [comment]
+1, please do this.

**Comment by leandroz** [comment]
+1

**Comment by lukeed** [comment]
I have a full gulp-browserify bundle for LumX that I was planning on submitting soon. 
Will allow us to get up and running quickly, and dramatically cut down the gulp file

**Comment by malexandre** [comment]
Sorry, I really was deep in other project, I'll try to manage this ASAP.

**Comment by Ir1sh** [comment]
+1

**Comment by kilianc** [comment]
NPM is gonna be pretty much the "de facto" standard way to distribute browser modules, so this should be published there as well

**Comment by kilianc** [comment]
p.s. not just browserify, the same thing that's on bower should be on npm as well

**Comment by carlos-** [comment]
+1 Webpack prefers NPM (CommonJS)

**Comment by nwrman** [comment]
+1 for NPM!

**Comment by notrab** [comment]
+1 👌

**Comment by t8g** [comment]
+1

**Comment by vcardins** [comment]
+1

**Comment by DavidDudson** [comment]
+1 - The only reason I need bower at the moment is Lumx, all other dependencies are bundles using Webpack and NPM

**Comment by enpfeff** [comment]
+1

**Comment by aberenyi** [comment]
+1

**Comment by dishui** [comment]
+1

**Comment by kilianc** [comment]
+1

**Comment by carmen-mvp** [comment]
So I was able to `npm install lumx` but it doesn't pull down the right release, it doesn't include the dist/ dir, can you update the version for npm?

**Comment by Igogrek** [comment]
Any updates on this? Basically all of the client-side dependencies you can think of are already in the NPM.

**Comment by hbthanki** [comment]
Hats off guys !!!
Only using Webpack + NPM. Now I need bower for just Lumx. 
Please do this !

**Comment by marc-antoinepelletier** [comment]
It seems someone published your framework on npm https://www.npmjs.com/package/lumx , I'd really like to have the possibility to get lumX from npm as well.

Any news on it ?

**Comment by marc-antoinepelletier** [comment]
@kentcdodds Any chance you can share with us how you manage to use lumx bower with webpack ?

**Comment by kentcdodds** [comment]
Unfortunately not, it's been a long time since I've used Bower and I strongly recommend against using Bower these days.

**Comment by marc-antoinepelletier** [comment]
No worries, but indeed I just discover this https://github.com/bower/bower/issues/2298#issuecomment-302792690
cc @malexandre I think this should be a good enough reason for lumX to be on NPM as well no ?

**Comment by arnaudvalle** [comment]
For info, lumx is now available on npm: https://www.npmjs.com/package/official-lumx 

😮
