### ISSUE TITLE
Allow the use of multiple progress on the same page

### ISSUE THREAD

**Issue by demetriusnunes** [lumapps/lumX#79]
As it is, the progress component is a "global" page component, specially because the .hide method doesn't take any identifier/container.

In a page where there are multiple operations going on (for instance, when you're uploading multiple files) it is necessary to have more than on independent progress components.

**Comment by malexandre** [comment]
Hi! Sorry for the late answer, I've got overwhelmed. So yeah, it's in the works to be able to have multiple progress.

**Comment by tagazok** [comment]
Having multiple progress works, you just have to specify different ids.
However, I am facing a problem. I can display several progress on my page but I can't specify which one to hide :/
LxProgressService.linear.hide();

**Comment by matmkian** [comment]
It's now possible as each progress has its own directive.
