### ISSUE TITLE
Date picker events

### ISSUE THREAD

**Issue by tagazok** [lumapps/lumX#80]
Hi !
In my application, I usually trigger an action when a field changes.
To do that, is simply use the ng-blur directive.
I used to use an input type="date" until you released your date picker.
the native input date worked well except that it was really ugly.
Unfortunately, I can't reproduce the same behaviour with your date picker.

There are 2 things I can't reproduce : 
- open the date picker when it has focus (when pressing tab from the previous field in my form, it should get the focus and open)
- bind an event such as ng-blur when the value is updated without having to watch it.

Do you thinks this could be possible?

**Comment by malexandre** [comment]
Hi! Sorry for the late answer.

Yeah it's possible, and definitely something we'll do when updating the date picker component. It's not for right now though.

**Comment by MilosStanic** [comment]
I would also like have ability to pass a function call to datepicker which would execute on "ok" button pressed. 
May I direct your attention to a nice MD datepicker project:
https://github.com/SimeonC/md-date-time

Take a look at available options. 

Thanks a lot.

**Comment by dannylagrouw** [comment]
+1 for either a function call on "ok" pressed or support of the ng-change attribute.

**Comment by matmkian** [comment]
In the last version, we've reworked and fixed a lot of things. If this issue is still happening, please re-open the issue. Thank you!
