### ISSUE TITLE
Add a timepicker directive

### ISSUE THREAD

**Issue by bastienJS** [lumapps/lumX#82]
I would need timepicker directive :-)

**Comment by malexandre** [comment]
It's in the works to go with the datepicker. Soon!

**Comment by rriemann** [comment]
:+1: – I'm waiting for it as well.

**Comment by tenphi** [comment]
:+1: musthave

**Comment by jmijmi** [comment]
+1

**Comment by Codicode** [comment]
+1 ... still waiting

**Comment by matmkian** [comment]
Duplicate #276
