### ISSUE TITLE
Add a datepicker with popup option

### ISSUE THREAD

**Issue by bastienJS** [lumapps/lumX#83]
I need a datepicker with popup option. This is also usefull for mobile first.

I want to validate the a choosen date and give immediate response over the datepicker-Textfield with a red validation message. With your datepicker shown as a "dialog" you cover everything on the screen.
Also opening and closing a datepicker like a dialog is too much distortion for the user IMHO.

**Comment by malexandre** [comment]
Hi!

The datepicker we made is directly from the [MD spec](http://www.google.fr/design/spec/components/pickers.html). I don't think we'll have a dropdown version. But it will be updated to manage some validation like an interval for example.

**Comment by bastienJS** [comment]
That does not make sense. When I simply want to change a date then I do not want to be distorted by a fading popup dialog...
