### ISSUE TITLE
Pressing enter after opening dialog

### ISSUE THREAD

**Issue by cranst0n** [lumapps/lumX#89]
On the demo page, after clicking the **Open Dialog** button, each press of the **[Enter]** key causes the backdrop to darken and it doesn't go away after closing the dialog.

It looks as though each key press adds:

```html
<div class="dialog-filter dialog-filter--is-shown"></div>
```

**Comment by cvrebert** [comment]
Yeah, the focus remains on the "Open Dialog" button even after the dialog appears, so you're really just activating that button again when you click Enter like that.

**Comment by malexandre** [comment]
Hi! Thank you for reporting the issue. I'll close this ticket to keep the #91 opened by @cvrebert.
