### ISSUE TITLE
Disabled <a>s are still clickable

### ISSUE THREAD

**Issue by cvrebert** [lumapps/lumX#90]
For example, if I have:
```html
<a class="btn btn--m btn--black btn--flat btn--is-disabled" href="/foobar.html">Button</a>
```
Although the button visually looks disabled, I can still click on the link and will get taken to `/foobar.html`. This is annoying/unintuitive, although somewhat understandable. At the least, it seems like this caveat is worth mentioning in the docs.

**Comment by malexandre** [comment]
Hi!

You're right, it should be at least said in the docs. I'll try to figure a way to manage it anyway, I think with a directive it would be possible. Thanks for the report!

**Comment by matmkian** [comment]
Our buttons are only styles with CSS, no directive here. So we can't prevent default behavior. I think yiu should create a custom directive that prevent default behavior.

**Comment by cvrebert** [comment]
You could use `pointer-events: none`
