### ISSUE TITLE
Dialogs & alert/confirm boxes don't capture/manage focus

### ISSUE THREAD

**Issue by cvrebert** [lumapps/lumX#91]
Somewhat related to #69, the alert/confirm boxes demoed on http://ui.lumapps.com/services/notifications and the dialogs demoed on http://ui.lumapps.com/directives/dialogs don't capture focus, so:
(a) If you click a button that opens such a box, that button remains focused when the box appears. You can even press the spacebar a few times to make multiple boxes show at once, and then you run into another problem, which is that you can only dismiss the top box; clicking the buttons in the other boxes doesn't dismiss them.
(b) By pressing Tab, you can "escape" the box and focus other UI elements on the page under the box (which makes it a non-modal modal dialog box...)

**Comment by malexandre** [comment]
Hi!

Thanks for the report. We'll be fixing that as soon as possible.

**Comment by maaronking** [comment]
Having one dialog that opens another will land you in same predicament as mentioned by @cvrebert.

**Comment by clementprevot** [comment]
Hi @cvrebert,

The problem you mentionned in your "(a)" has been fixed for confirm & alert by PR #328.
I'll fix this same problem for dialog very soon.

I will also give the focus to the dialog/confirm/alert so that you don't need to first click the box to get the focus and then click the button

**Comment by matmkian** [comment]
Bug fixed!
