### ISSUE TITLE
Scrolling in dialog eventually scrolls underlying page

### ISSUE THREAD

**Issue by cvrebert** [lumapps/lumX#93]
1. Open the dialog box on http://ui.lumapps.com/directives/dialogs
2. Click the "+" button many times, until the dialog's content becomes scrollable
3. Using your scrollwheel/touchpad, scroll within the modal dialog
4. If you continue scrolling after reaching the top/bottom of the dialog's content, the underlying page will start to scroll.

Tested in OS X Chrome.

**Comment by malexandre** [comment]
Yep, it's linked to your #91 I think. If the modal were a real modal, then the scroll would not propagate to the entire window. We'll fix that.

**Comment by franciscopuyo** [comment]
The same is happening with selects tags and dropdownlists

https://github.com/lumapps/lumX/issues/289

**Comment by matmkian** [comment]
Bug fixed!
