### ISSUE TITLE
Esc key doesn't dismiss Alert box

### ISSUE THREAD

**Issue by cvrebert** [lumapps/lumX#94]
In Zurb Foundation and in Bootstrap, by default, pressing the Esc key will close a modal dialog (although both frameworks offer an option to disable this for when we need the user to make an explicit decision/choice before exiting the dialog). This is nice for accessibility and general UX.
lumX doesn't currently seem to implement this convention.

**Comment by malexandre** [comment]
We'll be working in accessibility and some ergonomics soon. It's important. But for now lumX is almost not usable by keyboard (and that is not okay).

**Comment by clementprevot** [comment]
Fixed by PR #325
