### ISSUE TITLE
The code of the prgress in the dist/lumx.js must be old

### ISSUE THREAD

**Issue by luckyadam** [lumapps/lumX#95]
Hi,I just found that the code in the dist/lumx.js must be old,it still use CSS3,but in the progress componet,it begins to use SVG.

**Comment by malexandre** [comment]
Hi!

You're sure? The dist folder in the repo is not the one in the release. We don't want to have the "dist" commit in our history as it's not important. So we make it with a tag oustide all branches. But the release doesn't use the CSS version anymore (see http://ui.lumapps.com/services/progress).

**Comment by luckyadam** [comment]
Sorry,I had made a mistake.Once again sorry for the late reply!
