### ISSUE TITLE
Date Picker Broken

### ISSUE THREAD

**Issue by dg1202** [lumapps/lumX#96]
I've tired many times, throwing different things at the date picker directive, but I can't get it to work at all. Am I missing something, or is this just broken?  

I have an app defined and using other directives without problems. The directive is straight from the example  
`<lx-date-picker model="datepicker.date" label="Pick a date"></lx-date-picker>`  

I even tried to instantiate an datepicker object on the $scope, but that didn't do anything either. There are no logs in the console with errors either.  

Installed lumx via bower.  
  
![screen shot 2015-01-03 at 8 27 27 am](https://cloud.githubusercontent.com/assets/2365581/5602642/664ecf80-9322-11e4-9f12-00631fba4d1d.png)

![screen shot 2015-01-03 at 8 25 53 am](https://cloud.githubusercontent.com/assets/2365581/5602640/4137cc1a-9322-11e4-84eb-6b54cda28b37.png)

**Comment by malexandre** [comment]
Hi!
Is it normal that all your bower package are from `bower_components` but not lumX (`lib/lumx.js`)? If there is no logs, with the result DOM you showed, I think you must have an old lumX version.

Side note: We're not including the version number at the start of the lumX file, it would help in your case. I'm going to do it right now.

**Comment by dg1202** [comment]
Yea, I did indeed pull from bower the first time. So I was trying a few different versions manually pulled down, to see if something broke in a build. 

Ill give it another go later and pull it all from bower again and see what happens. Thanks for the reply!

**Comment by dg1202** [comment]
Updated bower components to latest build, and everything works today! Closing =)

**Comment by malexandre** [comment]
Good!
